// Usage: node editor/run_v01.js   Editor v0.1 acceptance: G1-G10 (pre-registered in witness_log/HYPOTHESES.md before this file existed). Needs system Chrome (CHROMIUM env) and the venv python with psd-tools (PYTHON env).
const fs = require('fs'), path = require('path'), http = require('http'), { spawnSync } = require('child_process'), { exportLog } = require('./export_psd.js');
const ROOT = path.join(__dirname, '..'), OUT = path.join(__dirname, 'out'); fs.mkdirSync(OUT, { recursive: true }); const rec = [], fails = [], num = {};
const chk = (id, name, value, cmp, limit) => { const pass = cmp === '<=' ? value <= limit : cmp === '>=' ? value >= limit : value === limit; rec.push({ id, name, value, cmp, limit, pass }); if (!pass) fails.push({ id, name, value, cmp, limit }); };
const med = (a) => a.slice().sort((x, y) => x - y)[a.length >> 1], pct = (a, p) => a.slice().sort((x, y) => x - y)[Math.min(a.length - 1, Math.floor(a.length * p))];
const b64 = (u8) => Buffer.from(u8).toString('base64'), same = (a, b) => Buffer.compare(Buffer.from(a), Buffer.from(b)) === 0;
(async () => {
  require('child_process').execFileSync(process.execPath, [path.join(__dirname, 'build_dist.js'), path.join(OUT, 'dist')], { stdio: 'pipe' });
  const { chromium } = require('playwright-core'), srv = http.createServer((q, r) => { const f = path.join(ROOT, decodeURIComponent(q.url.split('?')[0])); if (!f.startsWith(ROOT) || !fs.existsSync(f) || fs.statSync(f).isDirectory()) { r.writeHead(404); return r.end(); }
    r.writeHead(200, { 'content-type': f.endsWith('.js') ? 'text/javascript' : f.endsWith('.html') ? 'text/html' : 'application/octet-stream' }); fs.createReadStream(f).pipe(r); }).listen(0, '127.0.0.1'); await new Promise((r) => srv.on('listening', r));
  const base = 'http://127.0.0.1:' + srv.address().port, br = await chromium.launch({ executablePath: process.env.CHROMIUM || '/opt/pw-browsers/chromium', args: ['--no-sandbox'] });
  const open = async (url, init) => { const pg = await br.newPage({ viewport: { width: 1400, height: 900 } }), errs = []; pg.on('pageerror', (e) => errs.push(e.message)); pg.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); }); pg.setDefaultTimeout(120000); if (init) await pg.addInitScript(init); await pg.goto(url); await pg.waitForFunction(() => window.__ed); pg.errs = errs; return pg; };
  const info = (pg) => pg.evaluate(() => { const c = document.getElementById('c'), r = c.getBoundingClientRect(), v = document.getElementById('view').getBoundingClientRect(), m = new DOMMatrix(getComputedStyle(c).transform); return { l: r.left, t: r.top, w: r.width, h: r.height, vl: v.left, vt: v.top, e: m.e, f: m.f, a: m.a, bs: parseFloat(c.style.width) }; });
  const toScreen = (b, u, v) => [b.l + u * b.w, b.t + v * b.h];
  const drag = async (pg, pts) => { await pg.mouse.move(...pts[0]); await pg.mouse.down(); for (const p of pts.slice(1)) await pg.mouse.move(...p, { steps: 8 }); await pg.mouse.up(); };
  const hexOf = (c) => '#' + c.map((v) => v.toString(16).padStart(2, '0')).join('');

  // ---- page A: G8 shortcuts, G1 eyedropper, G2 zoom/pan mapping, G7 cursor, G10 big brush
  const A = await open(base + '/editor/index.html'); let b = await info(A);
  { const seq = []; for (const k of ['1', '2', '3', '4', '5', 'i']) { await A.keyboard.press(k); seq.push(await A.evaluate(() => window.__ed.params.tool)); } await A.keyboard.press('1');
    await A.fill('#size', '40'); await A.dispatchEvent('#size', 'input'); await A.keyboard.press('['); const s1 = await A.evaluate(() => window.__ed.params.size); await A.keyboard.press(']'); const s2 = await A.evaluate(() => window.__ed.params.size);
    await A.evaluate(() => window.__ed.onChange(() => {})); const n0 = await A.evaluate(() => window.__ed.ops.length); await A.keyboard.press('Control+z'); const n1 = await A.evaluate(() => window.__ed.ops.length);
    chk('G8', `keys 1-5, I select tools ${seq.join(',')}; [ -> ${s1}, ] -> ${s2} from 40; Ctrl+Z does nothing below the initial ops (${n0} -> ${n1})`, JSON.stringify(seq) === JSON.stringify(['hard', 'soft', 'smudge', 'erase', 'blur', 'pick']) && s1 === 36 && s2 === 40 && n1 === n0, '==', true); }
  { await A.evaluate(() => { const c = document.getElementById('color'); c.value = '#cc2211'; c.dispatchEvent(new Event('input')); }); await A.keyboard.press('1'); await A.fill('#size', '30'); await A.dispatchEvent('#size', 'input');
    await drag(A, [toScreen(b, 0.2, 0.3), toScreen(b, 0.5, 0.35), toScreen(b, 0.7, 0.3)]); const nOps = await A.evaluate(() => window.__ed.ops.length);
    await A.evaluate(() => { const c = document.getElementById('color'); c.value = '#000000'; c.dispatchEvent(new Event('input')); }); await A.keyboard.press('i'); const [px, py] = toScreen(b, 0.5, 0.35); await A.mouse.click(px, py);
    const r = await A.evaluate(([x, y]) => { const ed = window.__ed, c = document.getElementById('c').getBoundingClientRect(), cx = Math.floor((x - c.left) * ed.W / c.width), cy = Math.floor((y - c.top) * ed.W / c.height), d = ed.displayRGBA8(cx, cy); return { input: document.getElementById('color').value, shown: d, ops: ed.ops.length }; }, [px, py]);
    const want = hexOf(r.shown.slice(0, 3)); num.G1 = { picked: r.input, displayed: want }; chk('G1', `eyedropper set the colour to the displayed pixel (${r.input} vs ${want}) and added no log entry (${nOps} -> ${r.ops})`, r.input === want && r.ops === nOps, '==', true); }
  { // G2: ctrl+wheel zoom about a point, pan with Space+drag, then paint through two screen positions
    await A.keyboard.press('1'); b = await info(A); const [zx, zy] = toScreen(b, 0.3, 0.6).map(Math.round);   // wheel events carry whole-pixel coordinates in Chrome (first run used a fractional anchor and drifted 1 px)
    const canvasAt = (bb, x, y) => [((x - bb.vl - bb.e) / (bb.a * bb.bs)) * 1024, ((y - bb.vt - bb.f) / (bb.a * bb.bs)) * 1024];
    const before = canvasAt(b, zx, zy); await A.mouse.move(zx, zy); await A.keyboard.down('Control'); for (let i = 0; i < 4; i++) await A.mouse.wheel(0, -100); await A.keyboard.up('Control'); const bz = await info(A), after = canvasAt(bz, zx, zy);
    const zoomPct = Math.round(bz.a * bz.bs / 1024 * 100); chk('G2', `ctrl+wheel zoom to ${zoomPct}% keeps the canvas point under the cursor fixed (moved ${Math.hypot(after[0] - before[0], after[1] - before[1]).toFixed(2)} px)`, Math.hypot(after[0] - before[0], after[1] - before[1]) <= 1 && bz.a > 2, '==', true);
    await A.keyboard.down(' '); await A.mouse.move(700, 450); await A.mouse.down(); await A.mouse.move(640, 410, { steps: 5 }); await A.mouse.up(); await A.keyboard.up(' '); const bp = await info(A);
    const s1 = [bp.vl + 300, bp.vt + 250], s2 = [bp.vl + 520, bp.vt + 330], e1 = canvasAt(bp, ...s1), e2 = canvasAt(bp, ...s2); const nb = await A.evaluate(() => window.__ed.ops.length); await drag(A, [s1, s2]);
    const lg = await A.evaluate(() => { const o = window.__ed.ops.at(-1); return { n: window.__ed.ops.length, p0: o.pts[0], p1: o.pts.at(-1), op: o.op }; }); const d0 = Math.hypot(lg.p0[0] - e1[0], lg.p0[1] - e1[1]), d1 = Math.hypot(lg.p1[0] - e2[0], lg.p1[1] - e2[1]);
    num.G2 = { zoomPct, panDx: bp.e - bz.e, d0, d1 }; chk('G2', `after zoom ${zoomPct}% and a pan of ${(bp.e - bz.e).toFixed(0)},${(bp.f - bz.f).toFixed(0)} px, a stroke's first/last logged points are ${d0.toFixed(2)} / ${d1.toFixed(2)} canvas px from the expected positions (independent CSS-matrix maths)`, lg.n === nb + 1 && d0 <= 0.5 && d1 <= 0.5 && bp.e !== bz.e, '==', true); }
  { // G7 cursor at 200%: set size 40, fit then zoom to ~200%
    await A.keyboard.press('0'); await A.fill('#size', '40'); await A.dispatchEvent('#size', 'input'); await A.click('#zin'); await A.click('#zin'); await A.click('#zin'); const bb = await info(A); await A.mouse.move(bb.vl + 300, bb.vt + 300); await A.mouse.move(bb.vl + 310, bb.vt + 305);
    const c = await A.evaluate(() => { const e = document.getElementById('cursor'), r = e.getBoundingClientRect(); return { shown: getComputedStyle(e).display, w: parseFloat(e.style.width), canvasW: document.getElementById('c').getBoundingClientRect().width }; }); const want = 2 * 40 * c.canvasW / 1024;
    await A.mouse.move(700, 20); const hidden = await A.evaluate(() => getComputedStyle(document.getElementById('cursor')).display); num.G7 = { shown: c.shown, w: c.w, want, hidden };
    chk('G7', `brush cursor visible over the canvas with diameter ${c.w.toFixed(1)} px (expected ${want.toFixed(1)}), hidden outside (${hidden})`, c.shown === 'block' && Math.abs(c.w - want) <= 2 && hidden === 'none', '==', true); }
  { // G10 big brush at high zoom
    await A.keyboard.press('2'); await A.fill('#size', '120'); await A.dispatchEvent('#size', 'input'); await A.keyboard.press('0'); for (let i = 0; i < 3; i++) await A.click('#zin'); const bb = await info(A); await A.evaluate(() => { window.__ed.moveMs.length = 0; });
    await A.mouse.move(bb.vl + 150, bb.vt + 150); await A.mouse.down(); for (let i = 0; i < 60; i++) await A.mouse.move(bb.vl + 150 + i * 8, bb.vt + 150 + Math.sin(i / 5) * 90); await A.mouse.up(); const ms = await A.evaluate(() => window.__ed.moveMs.slice());
    num.G10 = { n: ms.length, median: med(ms), p95: pct(ms, 0.95), max: Math.max(...ms) }; chk('G10', `size-120 soft stroke at high zoom: handler median ${med(ms).toFixed(1)} ms, p95 ${pct(ms, 0.95).toFixed(1)} ms, max ${Math.max(...ms).toFixed(1)} over ${ms.length} moves`, med(ms) <= 16 && pct(ms, 0.95) <= 33, '==', true); }

  // ---- G4 PNG, G5 PSD (page A's current painting)
  { const png = await A.evaluate(async () => { const ed = window.__ed, bytes = await ed.exportPNG(), bmp = await createImageBitmap(new Blob([bytes], { type: 'image/png' })), oc = document.createElement('canvas'); oc.width = bmp.width; oc.height = bmp.height; const cx = oc.getContext('2d'); cx.drawImage(bmp, 0, 0);
      let s = 777, bad = 0; const rnd = () => (s = (Math.imul(s, 1664525) + 1013904223) >>> 0) / 4294967296, live = document.getElementById('c').getContext('2d'); for (let i = 0; i < 200; i++) { const x = (rnd() * ed.W) | 0, y = (rnd() * ed.W) | 0, p = cx.getImageData(x, y, 1, 1).data, q = live.getImageData(x, y, 1, 1).data; if (p.some((v, k) => v !== q[k])) bad++; } return { bad, w: bmp.width, bytes: bytes.length }; });
    chk('G4', `exported PNG (${png.bytes} bytes, ${png.w} px wide) equals the canvas for 200 random pixels`, png.bad, '==', 0); }
  { const got = await A.evaluate(() => { const ed = window.__ed, psd = ed.exportPSD(); let s = ''; for (let i = 0; i < psd.length; i += 0x8000) s += String.fromCharCode.apply(null, psd.subarray(i, i + 0x8000)); return { b64: btoa(s), log: ed.save() }; });
    const bytes = Buffer.from(got.b64, 'base64'), node = await exportLog(got.log); chk('G5', `in-page PSD (${bytes.length} bytes) is byte-identical to the Node exporter's file for the same log`, same(bytes, node.bytes), '==', true);
    const psdPath = path.join(OUT, 'v01_page.psd'); fs.writeFileSync(psdPath, bytes); const meta = { W: node.W, layers: node.layers.map((l, i) => { const f = path.join(OUT, `v01_layer${i}.rgba`); fs.writeFileSync(f, l.rgba); return { mode: l.mode, opacity: l.opacity, rgba: f }; }), display: path.join(OUT, 'v01_display.rgba') }; fs.writeFileSync(meta.display, node.display); fs.writeFileSync(path.join(OUT, 'v01_meta.json'), JSON.stringify(meta));
    const py = spawnSync(process.env.PYTHON || 'python3', ['-I', path.join(__dirname, 'check_psd_editor.py'), psdPath, path.join(OUT, 'v01_meta.json')], { encoding: 'utf8' }); if (py.status !== 0) { console.error(py.stderr); process.exit(2); } const R = JSON.parse(py.stdout.trim().split('\n').pop()); num.G5 = R;
    chk('G5', `psd-tools reads the page-made file: ${R.layers} layers, profile ${R.profile_resource}, layer pixel diff max ${Math.max(...R.layer_max_diff)}, merged diff max ${R.merged_max_diff}`, R.layers === node.layers.length && R.profile_resource && Math.max(...R.layer_max_diff) <= 1 && R.merged_max_diff <= 1, '==', true); }

  // ---- G3 autosave / restore / new canvas
  { await new Promise((r) => setTimeout(r, 700)); const before = await A.evaluate(() => ({ h: window.__ed.hashes(), n: window.__ed.ops.length, saved: window.__saved })); await A.reload(); await A.waitForFunction(() => window.__ed); const after = await A.evaluate(() => ({ h: window.__ed.hashes(), n: window.__ed.ops.length }));
    chk('G3', `after a reload the painting is restored (${before.n} ops saved -> ${after.n} ops; hashes equal ${before.h.comp.slice(0, 8)} / ${after.h.comp.slice(0, 8)})`, before.n === after.n && before.h.comp === after.h.comp && JSON.stringify(before.h.layers) === JSON.stringify(after.h.layers) && before.saved === before.n, '==', true);
    await A.click('#newc'); await A.click('#newc'); const nw = await A.evaluate(() => ({ n: window.__ed.ops.length, stored: localStorage.getItem('psd-oplog-editor-v1') })); chk('G3', 'New canvas (two clicks) resets to the 3 initial ops and clears the saved copy', nw.n === 3 && nw.stored === null, '==', true); }
  chk('G3', 'page A (all of the above) had no page errors', A.errs.length, '==', 0); await A.close();
  { const S2 = await open(base + '/editor/index.html', () => { Storage.prototype.setItem = () => { throw new Error('quota exceeded (test)'); }; }); const bb = await info(S2); await drag(S2, [toScreen(bb, 0.2, 0.2), toScreen(bb, 0.6, 0.5)]); await S2.keyboard.press('Control+z'); await S2.keyboard.press('Control+Shift+z'); await new Promise((r) => setTimeout(r, 700));
    const ok = await S2.evaluate(() => ({ n: window.__ed.ops.length, psd: window.__ed.exportPSD().length, saved: window.__saved })); chk('G3', `with localStorage.setItem throwing: paints (${ok.n} ops), undo/redo, exports a ${ok.psd}-byte PSD, 0 page errors`, ok.n === 4 && ok.psd > 1000 && S2.errs.length === 0, '==', true); await S2.close(); }

  // ---- G6 file:// for index.html and the built dist
  for (const [name, url] of [['editor/index.html', 'file://' + path.join(__dirname, 'index.html')], ['dist/index.html', 'file://' + path.join(OUT, 'dist', 'index.html')]]) {
    const F = await open(url), bb = await info(F); await drag(F, [toScreen(bb, 0.2, 0.3), toScreen(bb, 0.6, 0.5), toScreen(bb, 0.7, 0.2)]); const got = await F.evaluate(() => { const ed = window.__ed, psd = ed.exportPSD(); let s = ''; for (let i = 0; i < psd.length; i += 0x8000) s += String.fromCharCode.apply(null, psd.subarray(i, i + 0x8000)); return { b64: btoa(s), log: ed.save(), n: ed.ops.length }; });
    const node = await exportLog(got.log); chk('G6', `${name} from file://: paints (${got.n} ops), 0 page errors, in-page PSD identical to the Node exporter's`, F.errs.length === 0 && got.n === 4 && same(Buffer.from(got.b64, 'base64'), node.bytes), '==', true); await F.close(); }
  await br.close(); srv.close();
  const out = { n_checks: rec.length, gate: fails.length ? 'FAIL' : 'PASS', fails, numbers: num, checks: rec, node: process.version, cpus: require('os').cpus()[0].model };
  fs.writeFileSync(path.join(OUT, 'v01.json'), JSON.stringify(out, null, 1)); console.log(JSON.stringify({ ...out, checks: undefined }, null, 1)); process.exit(fails.length ? 1 : 0);
})();
