// Usage: node editor/run_select.js   Level 1c selection: S1-S8 (pre-registered in witness_log/HYPOTHESES.md before this file existed). Needs system Chrome (CHROMIUM), PYTHON with numpy.
const fs = require('fs'), path = require('path'), http = require('http'), crypto = require('crypto'), { spawnSync } = require('child_process');
const S = require('../stack.js'), Br = require('../filters/brush.js'), Bl = require('../filters/blur.js'), LO = require('./layer_ops.js'), SO = require('./select_ops.js'), GOLD = require('./golden_s3.json'), GLOG = require('./golden_s3_log.js');
const ROOT = path.join(__dirname, '..'), OUT = path.join(__dirname, 'out'), rec = [], fails = [], num = {}; fs.mkdirSync(OUT, { recursive: true });
const chk = (id, name, value, cmp, limit) => { const pass = cmp === '<=' ? value <= limit : cmp === '>=' ? value >= limit : value === limit; rec.push({ id, name, value, cmp, limit, pass }); if (!pass) fails.push({ id, name, value, cmp, limit }); console.error((pass ? 'ok   ' : 'FAIL ') + id + ' ' + name); };
const rng = (seed) => { let s = seed >>> 0; return () => (s = (Math.imul(s, 1664525) + 1013904223) >>> 0) / 4294967296; }, r2 = (x) => Math.round(x * 100) / 100, r4 = (x) => Math.round(x * 1e4) / 1e4, J = JSON.stringify;
const base = (st, o) => (o.op === 'blur' ? Bl.applyOp(st, o) : Br.applyOp(st, o)), applyOp = (st, o) => (LO.apply(st, o) || SO.apply(st, o, base) ? undefined : base(st, o));
const hashes = (st) => ({ comp: S.hashF32(S.composite(st)), layers: Object.keys(st.L).map((k) => S.hashF32(st.L[k].pix)) });
(async () => {
  // ---- S3 golden (recorded from the pre-selection code before select_ops.js existed)
  { const st = S.newState(256); for (const o of GLOG) applyOp(st, o); chk('S3', 'fixed 12-op log without selection == golden hashes recorded before this change', J(hashes(st)) === J(GOLD), '==', true); }
  // ---- S1 inside == unselected result, outside == untouched
  { const W = 256, rnd = rng(11); let badIn = 0, badOut = 0, nops = 0, insideChanged = 0;
    const baseLayer = () => { const st = S.newState(W); S.apply(st, { op: 'layer', id: 0, mode: 'normal', opacity: 1, mask: false }); const r = rng(3); for (let i = 0; i < 90; i++) S.apply(st, { op: 'dab', layer: 0, x: r4(r() * W), y: r4(r() * W), r: r4(4 + r() * 40), c: [r4(r()), r4(r()), r4(r())], a: r4(0.3 + r() * 0.7) }); return st; };
    const SELS = [{ kind: 'rect', x0: 40, y0: 60, x1: 200, y1: 180 }, { kind: 'ellipse', x0: 30, y0: 30, x1: 220, y1: 170 }, { kind: 'rect', x0: 40, y0: 60, x1: 200, y1: 180, inv: 1 }, { kind: 'ellipse', x0: 30, y0: 30, x1: 220, y1: 170, inv: 1 }];
    for (const sel of SELS) for (let t = 0; t < 10; t++) { const kinds = ['hard', 'soft', 'erase', 'blur', 'smudge'], k = kinds[t % 5], n = 3 + ((rnd() * 20) | 0), pts = []; for (let i = 0; i < n; i++) pts.push([r2(rnd() * W), r2(rnd() * W)]);
      const o = k === 'smudge' ? { op: 'smudge', layer: 0, pts, r: 6 + rnd() * 18, s: r4(0.2 + rnd() * 0.8) } : k === 'blur' ? { op: 'stroke', layer: 0, kind: 'blur', pts, r: 6 + rnd() * 18, s: r4(0.3 + rnd() * 0.7) } : { op: 'stroke', layer: 0, kind: k, pts, r: 6 + rnd() * 30, c: [r4(rnd()), r4(rnd()), r4(rnd())], a: r4(0.3 + rnd() * 0.7) };
      const A = baseLayer(); base(A, o); const B = baseLayer(), C = baseLayer(); applyOp(C, { op: 'sel', kind: sel.kind, x0: sel.x0, y0: sel.y0, x1: sel.x1, y1: sel.y1 }); if (sel.inv) applyOp(C, { op: 'sel', kind: 'invert' }); applyOp(C, o); nops++;
      const m = C.sel.mask; for (let i = 0; i < W * W; i++) { const src = m[i] ? A.L[0].pix : B.L[0].pix; for (let c = 0; c < 4; c++) if (C.L[0].pix[i * 4 + c] !== src[i * 4 + c]) { if (m[i]) badIn++; else badOut++; } if (m[i] && A.L[0].pix[i * 4] !== B.L[0].pix[i * 4]) insideChanged++; } }
    num.S1 = { ops: nops, insidePixelsThatChanged: insideChanged }; chk('S1', `${nops} strokes (hard/soft/erase/blur/smudge) x 4 selections: channel values differing from the unselected result INSIDE`, badIn, '==', 0); chk('S1', 'channel values differing from the untouched layer OUTSIDE', badOut, '==', 0); chk('S1', 'negative control: the ops do change pixels inside the selection (test can see a change)', insideChanged > 1000, '==', true); }
  // ---- S5 mask vs independent numpy
  { const W = 256, boxes = [['rect', 0, 0, 256, 256], ['ellipse', 0, 0, 256, 256], ['rect', 10, 10, 11, 200], ['ellipse', 10, 10, 12, 200], ['ellipse', 30, 30, 220, 170], ['ellipse', 5, 100, 250, 101], ['ellipse', 100, 3, 103, 250], ['rect', 17, 33, 190, 77], ['ellipse', 17, 33, 190, 77], ['ellipse', 64, 64, 192, 192], ['ellipse', 1, 1, 255, 255], ['ellipse', 99, 17, 100, 18]];
    fs.writeFileSync(path.join(OUT, 'sel_boxes.json'), J({ W, boxes })); const py = spawnSync(process.env.PYTHON || 'python3', ['-I', path.join(__dirname, 'check_select_mask.py'), path.join(OUT, 'sel_boxes.json')], { encoding: 'utf8' }); if (py.status !== 0) { console.error(py.stderr); process.exit(2); }
    const ref = JSON.parse(py.stdout.trim()); let bad = 0; boxes.forEach(([k, x0, y0, x1, y1], i) => { const m = SO.maskOf(k, x0, y0, x1, y1, W), cnt = m.reduce((a, b) => a + b, 0), sha = crypto.createHash('sha256').update(m).digest('hex'); if (cnt !== ref[i].count || sha !== ref[i].sha256) bad++; });
    num.S5 = ref.map((r) => r.count); chk('S5', `${boxes.length} boxes (full canvas, 1-px wide, off-centre): mask count + sha256 equal the independent numpy float64 implementation`, bad, '==', 0); }
  // ---- S8 cost
  { const W = 1024, st = S.newState(W); S.apply(st, { op: 'layer', id: 0, mode: 'normal', opacity: 1, mask: false }); const pts = Array.from({ length: 100 }, (_, i) => [r2(100 + i * 8), r2(300 + 150 * Math.sin(i / 8))]);
    const time = (o, withSel) => { const ts = []; for (let k = 0; k < 5; k++) { const s2 = S.newState(W); S.apply(s2, { op: 'layer', id: 0, mode: 'normal', opacity: 1, mask: false }); if (withSel) applyOp(s2, { op: 'sel', kind: 'ellipse', x0: 100, y0: 100, x1: 900, y1: 700 }); const t0 = performance.now(); applyOp(s2, o); ts.push(performance.now() - t0); } return ts.sort((a, b) => a - b)[2]; };
    const hard = { op: 'stroke', layer: 0, kind: 'hard', pts, r: 20, c: [0.2, 0.3, 0.8], a: 1 }, sm = { op: 'smudge', layer: 0, pts, r: 20, s: 0.6 }; const r = { hard: [time(hard, false), time(hard, true)], smudge: [time(sm, false), time(sm, true)] }; num.S8 = r;
    chk('S8', `1024^2 100-point hard stroke: ${r.hard[0].toFixed(1)} ms without vs ${r.hard[1].toFixed(1)} ms with selection (limit 3x + 25 ms floor for the layer copy)`, r.hard[1] <= 3 * r.hard[0] + 25, '==', true); chk('S8', `smudge: ${r.smudge[0].toFixed(1)} vs ${r.smudge[1].toFixed(1)} ms`, r.smudge[1] <= 3 * r.smudge[0] + 25, '==', true); }
  // ---- browser
  const { chromium } = require('playwright-core'), srv = http.createServer((q, r) => { const f = path.join(ROOT, decodeURIComponent(q.url.split('?')[0])); if (!f.startsWith(ROOT) || !fs.existsSync(f) || fs.statSync(f).isDirectory()) { r.writeHead(404); return r.end(); }
    r.writeHead(200, { 'content-type': f.endsWith('.js') ? 'text/javascript' : f.endsWith('.html') ? 'text/html' : 'application/octet-stream' }); fs.createReadStream(f).pipe(r); }).listen(0, '127.0.0.1');
  await new Promise((r) => srv.on('listening', r)); const base_ = 'http://127.0.0.1:' + srv.address().port, br = await chromium.launch({ executablePath: process.env.CHROMIUM || '/opt/pw-browsers/chromium', args: ['--no-sandbox'] });
  const open = async (o = { viewport: { width: 1400, height: 900 } }) => { const ctx = await br.newContext(o), pg = await ctx.newPage(); pg.errs = []; pg.on('pageerror', (e) => pg.errs.push(e.message)); await pg.goto(base_ + '/editor/index.html'); await pg.waitForFunction(() => window.__ed); pg.ctx = ctx; return pg; };
  const pg = await open(); const ev = (f, a) => pg.evaluate(f, a);
  await ev(() => { window.cur = () => window.__ed.hashes(); window.ref = (ops) => Editor.refold(JSON.parse(JSON.stringify(ops)), 1024); });
  const cur = () => ev(() => window.cur()), ref = () => ev(() => window.ref(window.__ed.ops));
  // S2 live under selection == refold, every tool
  for (const shape of ['rect', 'ellipse']) { await ev((shape) => { const e = window.__ed; e.reset(); e.addLayer(); e.params.layer = 1; e.params.size = 30; e.params.color = [0.8, 0.2, 0.2]; e.params.flow = 1; if (shape === 'rect') e.select('rect', 200, 150, 700, 600); else e.select('ellipse', 200, 150, 700, 600);
      const zig = (y) => Array.from({ length: 24 }, (_, i) => [100 + i * 35, y + (i % 2) * 120]); for (const tool of ['hard', 'soft', 'erase', 'smudge', 'blur']) { e.params.tool = tool; const pts = zig(180 + 40 * ['hard', 'soft', 'erase', 'smudge', 'blur'].indexOf(tool)); e.begin(...pts[0]); for (const p of pts.slice(1)) e.move(...p); e.end(); } }, shape);
    chk('S2', `live strokes of all 5 tools crossing a ${shape} selection boundary: layer + composite hashes == refold(log)`, J(await cur()) === J(await ref()), '==', true);
    chk('S2', `${shape}: dirty compositor bit-equal to full composite`, await ev(() => { const a = window.__ed.D.back, b = Stack.composite(window.__ed.st); for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false; return true; }), '==', true); }
  // S4 exact state
  { await ev(() => { const e = window.__ed; e.reset(); e.addLayer(); e.params.layer = 1; e.params.tool = 'hard'; e.params.size = 30; e.params.color = [0.1, 0.5, 0.9]; });
    const h0 = await cur(); await ev(() => window.__ed.select('rect', 300, 300, 600, 600)); chk('S4', 'a selection alone changes no pixel', J(await cur()) === J(h0), '==', true);
    await ev(() => { const e = window.__ed; e.begin(10, 10); e.move(200, 50); e.end(); }); const n1 = await ev(() => window.__ed.ops.length); chk('S4', 'a stroke fully outside the selection is logged but changes 0 pixels', J(await cur()) === J(h0) && n1 === 6, '==', true);
    await ev(() => { const e = window.__ed; e.begin(250, 450); e.move(650, 450); e.end(); }); const h1 = await cur(); const ops1 = await ev(() => window.__ed.ops.length);
    await ev(() => { const e = window.__ed; e.undo(); e.undo(); e.undo(); }); chk('S4', 'undo x3 (stroke, outside stroke, selection) == pre-selection hashes and no selection', J(await cur()) === J(h0) && (await ev(() => !window.__ed.st.sel)), '==', true);
    await ev(() => { const e = window.__ed; e.redo(); e.redo(); e.redo(); }); chk('S4', 'redo x3 == hashes after the stroke, selection restored', J(await cur()) === J(h1) && (await ev(() => !!window.__ed.st.sel)), '==', true);
    const sv = await ev(() => window.__ed.save()); await ev(() => window.__ed.reset()); await ev((s) => window.__ed.load(s), sv); chk('S4', 'save -> load: hashes equal, selection present, log length equal', J(await cur()) === J(h1) && (await ev(() => !!window.__ed.st.sel)) && (await ev(() => window.__ed.ops.length)) === ops1, '==', true);
    await ev(() => window.__ed.invertSel()); await ev(() => { const e = window.__ed; e.begin(50, 50); e.move(150, 80); e.end(); }); chk('S4', 'invert then paint inside the old region logs and refolds equal', J(await cur()) === J(await ref()), '==', true); }
  // S7 export unaffected
  { await ev(() => { const e = window.__ed; e.reset(); e.addLayer(); e.params.layer = 1; e.params.tool = 'hard'; e.params.size = 40; e.params.color = [0.9, 0.3, 0.1]; e.begin(100, 100); e.move(800, 700); e.end(); e.select('ellipse', 200, 200, 800, 800); });
    const withSel = Buffer.from(await ev(async () => Array.from(await window.__ed.exportPSD()))); await ev(() => window.__ed.clearSel()); const noSel = Buffer.from(await ev(async () => Array.from(await window.__ed.exportPSD()))); chk('S7', `PSD bytes (${withSel.length}) identical with and without an active selection`, Buffer.compare(withSel, noSel) === 0, '==', true); }
  chk('S2', 'no page errors (desktop)', pg.errs.length, '==', 0); await pg.ctx.close();
  // S6 phone
  { const ph = await open({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 3, isMobile: true, hasTouch: true }); const cdp = await ph.ctx.newCDPSession(ph); const T = (t, pts) => cdp.send('Input.dispatchTouchEvent', { type: t, touchPoints: pts.map(([x, y, id]) => ({ x, y, id })) }), sleep = (ms) => new Promise((r) => setTimeout(r, ms));
    const n = () => ph.evaluate(() => window.__ed.ops.length), cv = () => ph.evaluate(() => { const r = document.getElementById('c').getBoundingClientRect(); return { x: r.left, y: r.top, w: r.width, h: r.height }; });
    await ph.evaluate(() => { window.__ed.reset(); window.__ed.addLayer(); }); const tb = ph.locator('#tools button[data-tool="select"]'); const vis = await tb.isVisible(); chk('S6', 'Select tool button is visible on the phone layout', vis, '==', true); await tb.tap(); await sleep(150);
    const c = await cv(), p = (u, v) => [c.x + u * c.w, c.y + v * c.h]; let n0 = await n(); await T('touchStart', [[...p(0.2, 0.2), 1]]); for (let i = 1; i <= 8; i++) await T('touchMove', [[p(0.2, 0.2)[0] + i * c.w * 0.06, p(0.2, 0.2)[1] + i * c.h * 0.06, 1]]); await T('touchEnd', []); await sleep(150);
    const sel = await ph.evaluate(() => window.__ed.st.sel && { kind: window.__ed.st.sel.kind, box: window.__ed.st.sel.box }); chk('S6', 'a one-finger drag with Select logs exactly one sel entry', (await n()) - n0 === 1 && !!sel && sel.kind === 'rect', '==', true);
    const exp = [0.2 * 1024, 0.2 * 1024, (0.2 + 0.48) * 1024, (0.2 + 0.48) * 1024]; chk('S6', 'selection box matches the finger path within 3 canvas px', sel ? Math.max(...sel.box.map((v, i) => Math.abs(v - exp[i]))) <= 3 : false, '==', true);
    const sizes = await ph.evaluate(() => ['s-rect', 's-ell', 's-inv', 's-clr'].map((id) => { const r = document.getElementById(id).getBoundingClientRect(); return [Math.round(r.width), Math.round(r.height)]; })); chk('S6', 'Rect / Ellipse / Invert / Clear buttons >= 44 px both ways', sizes.every(([w, h]) => w >= 44 && h >= 44), '==', true);
    await ph.locator('#tools button[data-tool="hard"]').tap(); await sleep(100); n0 = await n(); await T('touchStart', [[...p(0.05, 0.5), 1]]); for (let i = 1; i <= 10; i++) await T('touchMove', [[p(0.05, 0.5)[0] + i * c.w * 0.09, p(0.05, 0.5)[1], 1]]); await T('touchEnd', []); await sleep(200);
    const px = await ph.evaluate(() => { const l = window.__ed.st.L[window.__ed.params.layer].pix, a = (x, y) => l[(y * 1024 + x) * 4 + 3]; return { out: a(60, 512), inside: a(500, 512), box: window.__ed.st.sel.box }; }); chk('S6', `a following stroke respects the selection (alpha outside ${px.out}, inside ${px.inside.toFixed(2)})`, px.out === 0 && px.inside > 0, '==', true);
    await ph.locator('#s-inv').tap(); await sleep(100); chk('S6', 'Invert tap logs +1 and flips the mask', (await n()) - n0 === 2 && (await ph.evaluate(() => window.__ed.st.sel.inv)), '==', true);
    n0 = await n(); await ph.locator('#s-clr').tap(); await sleep(100); chk('S6', 'Clear tap logs +1 and removes the selection', (await n()) - n0 === 1 && (await ph.evaluate(() => !window.__ed.st.sel)), '==', true);
    const v = await ph.evaluate(() => { const r = document.getElementById('view').getBoundingClientRect(); return [r.left + r.width / 2, r.top + r.height / 2]; }); n0 = await n(); await T('touchStart', [[v[0] - 40, v[1], 1]]); await T('touchStart', [[v[0] - 40, v[1], 1], [v[0] + 40, v[1], 2]]); await sleep(60); await T('touchEnd', []); await sleep(200);
    chk('S6', 'two-finger tap undoes the Clear (-1 entry, selection back)', n0 - (await n()) === 1 && (await ph.evaluate(() => !!window.__ed.st.sel)), '==', true); chk('S6', 'no page scroll', await ph.evaluate(() => document.documentElement.scrollHeight <= innerHeight), '==', true); chk('S6', 'no page errors (phone)', ph.errs.length, '==', 0); await ph.ctx.close(); }
  await br.close(); srv.close();
  const out = { n_checks: rec.length, gate: fails.length ? 'FAIL' : 'PASS', fails, numbers: num, checks: rec, node: process.version }; fs.writeFileSync(path.join(OUT, 'select.json'), J(out, null, 1)); console.log(J({ ...out, checks: undefined }, null, 1)); process.exit(fails.length ? 1 : 0);
})().catch((e) => { console.error(e); process.exit(2); });
