// Usage: node editor/run_photo.js   Level 1d photo import: I1-I7 (pre-registered in witness_log/HYPOTHESES.md before this file existed). Needs system Chrome (CHROMIUM), PYTHON with psd-tools+numpy, lcms-wasm.
const fs = require('fs'), path = require('path'), http = require('http'), { spawnSync } = require('child_process');
const S = require('../stack.js'), IO = require('./img_ops.js'), { exportLog } = require('./export_psd.js');
const ROOT = path.join(__dirname, '..'), OUT = path.join(__dirname, 'out'), rec = [], fails = [], num = {}; fs.mkdirSync(OUT, { recursive: true });
const chk = (id, name, value, cmp, limit) => { const pass = cmp === '<=' ? value <= limit : cmp === '>=' ? value >= limit : value === limit; rec.push({ id, name, value, cmp, limit, pass }); if (!pass) fails.push({ id, name, value, cmp, limit }); console.error((pass ? 'ok   ' : 'FAIL ') + id + ' ' + name); };
const rng = (seed) => { let s = seed >>> 0; return () => (s = (Math.imul(s, 1664525) + 1013904223) >>> 0) / 4294967296; }, J = JSON.stringify, F = Math.fround, q8 = (v) => Math.max(0, Math.min(255, Math.floor(v * 255 + 0.5)));
(async () => {
  // ---- I1 blob -> layer exact (node, engine level)
  { const W = 128, r = rng(5), blob = new Uint8Array(W * W * 4); for (let i = 0; i < W * W; i++) { const k = r(), a = k < 0.2 ? 0 : k < 0.6 ? 255 : 1 + ((r() * 254) | 0); blob[i * 4 + 3] = a; for (let c = 0; c < 3; c++) blob[i * 4 + c] = a === 0 ? 0 : (r() * 256) | 0; }
    const st = S.newState(W); st.blobs = new Map([[S.sha256(blob), blob]]); S.apply(st, { op: 'layer', id: 0, mode: 'normal', opacity: 1, mask: false }); IO.apply(st, { op: 'img', id: 1, sha: S.sha256(blob) }); const pix = st.L[1].pix; let bad = 0, opq = 0, semi = 0, maxSemi = 0;
    for (let i = 0; i < W * W; i++) { const a = F(blob[i * 4 + 3] / 255); if (pix[i * 4 + 3] !== a) bad++; for (let c = 0; c < 3; c++) if (pix[i * 4 + c] !== F(F(blob[i * 4 + c] / 255) * a)) bad++;
      const A = blob[i * 4 + 3]; for (let c = 0; c < 3; c++) { const back = A > 0 ? q8(F(pix[i * 4 + c] / pix[i * 4 + 3])) : 0, d = Math.abs(back - blob[i * 4 + c]); if (A === 0 || A === 255) opq += d; else { semi++; maxSemi = Math.max(maxSemi, d); } } }
    num.I1 = { semiPixels: semi, maxSemiDiff: maxSemi }; chk('I1', 'every float pixel equals the formula bitwise (128^2 random incl. alpha 0 / 255 / semi-transparent)', bad, '==', 0); chk('I1', 'quantised back to RGBA8: total difference on alpha 0 / 255 pixels', opq, '==', 0); chk('I1', `quantised back: max difference on ${semi} semi-transparent pixels`, maxSemi, '<=', 1);
    const t = (o, W2 = W) => { try { IO.apply(st, o); return 'no throw'; } catch (e) { return 'throw'; } }; chk('I1', 'missing blob / existing id / wrong size all throw', [t({ op: 'img', id: 5, sha: 'ff' }), t({ op: 'img', id: 1, sha: S.sha256(blob) }), (() => { const s2 = S.newState(64); s2.blobs = st.blobs; return t.call(null, { op: 'img', id: 9, sha: S.sha256(blob) }) === 'throw' ? 'throw' : 'no throw'; })()].join(), '==', 'throw,throw,no throw'); }
  const { chromium } = require('playwright-core'), srv = http.createServer((q, r) => { const f = path.join(ROOT, decodeURIComponent(q.url.split('?')[0])); if (!f.startsWith(ROOT) || !fs.existsSync(f) || fs.statSync(f).isDirectory()) { r.writeHead(404); return r.end(); }
    r.writeHead(200, { 'content-type': f.endsWith('.js') ? 'text/javascript' : f.endsWith('.html') ? 'text/html' : 'application/octet-stream' }); fs.createReadStream(f).pipe(r); }).listen(0, '127.0.0.1');
  await new Promise((r) => srv.on('listening', r)); const base = 'http://127.0.0.1:' + srv.address().port, br = await chromium.launch({ executablePath: process.env.CHROMIUM || '/opt/pw-browsers/chromium', args: ['--no-sandbox'] });
  const open = async (ctx, o) => { const c = ctx || await br.newContext(o || { viewport: { width: 1400, height: 900 } }), pg = await c.newPage(); pg.errs = []; pg.on('pageerror', (e) => pg.errs.push(e.message)); await pg.goto(base + '/editor/index.html'); await pg.waitForFunction(() => window.__ed); pg.ctx = c; return pg; };
  const pg = await open(); const ev = (f, a) => pg.evaluate(f, a), cur = () => ev(() => window.__ed.hashes()), ref = () => ev(() => { const e = window.__ed; return Editor.refold(JSON.parse(JSON.stringify(e.ops)), 1024, e.blobs); });
  // a noise photo (worst case for size) as raw pixels, imported through the editor API
  const noise = (w) => ev((seed) => { const W = 1024, u = new Uint8Array(W * W * 4); let s = seed >>> 0; for (let i = 0; i < u.length; i++) { s = (Math.imul(s, 1664525) + 1013904223) >>> 0; u[i] = i % 4 === 3 ? 255 : s >>> 24; } return Array.from(u.subarray(0, 0)).length || (window.__noise = u, true); }, w);
  await noise(7);
  // ---- I2 / I3
  await ev(() => { const e = window.__ed; e.reset(); e.params.tool = 'hard'; e.params.layer = 1; e.params.size = 30; e.begin(100, 100); e.move(400, 300); e.end(); e.importPixels(window.__noise); e.importPixels(window.__noise); });
  const sv = JSON.parse(await ev(() => window.__ed.save())); chk('I2', 'same photo imported twice: save file has 1 blob and 2 img ops', Object.keys(sv.blobs).length === 1 && sv.ops.filter((o) => o.op === 'img').length === 2, '==', true); num.I4size = JSON.stringify(sv).length;
  { const key = Object.keys(sv.blobs)[0], t1 = JSON.parse(JSON.stringify(sv)); const b = Buffer.from(t1.blobs[key], 'base64'); b[1000] ^= 1; t1.blobs[key] = b.toString('base64'); const t2 = JSON.parse(JSON.stringify(sv)); delete t2.blobs[key];
    const tryLoad = (j) => ev((s) => { try { window.__ed.load(s); return 'loaded'; } catch (e) { return e.message; } }, J(j)); const m1 = await tryLoad(t1), m2 = await tryLoad(t2); chk('I2', `tampered blob rejected (${m1.slice(0, 40)})`, /sha/.test(m1), '==', true); chk('I2', `missing blob rejected (${m2.slice(0, 40)})`, /missing blob/.test(m2), '==', true); }
  await ev((s) => window.__ed.load(s), J(sv)); const h = await cur(); chk('I3', 'loaded log with 2 photo layers: hashes == refold(ops, blobs)', J(h) === J(await ref()), '==', true);
  await ev(() => { const e = window.__ed; e.params.tool = 'hard'; e.params.color = [1, 0, 0]; e.params.size = 40; e.begin(300, 300); e.move(700, 500); e.end(); e.hideLayer(3, true); e.moveLayer(2, 1); }); const h2 = await cur(); chk('I3', 'photo layer painted on + hidden + moved: live == refold', J(h2) === J(await ref()), '==', true);
  await ev(() => { for (let i = 0; i < 3; i++) window.__ed.undo(); }); const hu = await cur(); await ev(() => { for (let i = 0; i < 3; i++) window.__ed.redo(); }); chk('I3', 'undo x3 / redo x3 (stroke on photo, hide, move): bit-exact', J(await cur()) === J(h2) && J(hu) !== J(h2), '==', true);
  await ev(() => { const e = window.__ed; e.reset(); e.params.layer = 1; e.importPixels(window.__noise); }); const hi = await cur(); await ev(() => window.__ed.undo()); const nl = await ev(() => window.__ed.layers().length); await ev(() => window.__ed.redo()); chk('I3', 'undo of the import removes the layer (layers: ' + nl + '), redo restores bit-exact', nl === 2 && J(await cur()) === J(hi), '==', true);
  // ---- I7 PSD
  { const png = Buffer.from(await ev(async () => Array.from(await window.__ed.exportPSD()))), nodeEx = await exportLog(await ev(() => window.__ed.save())); chk('I7', `page PSD bytes (${png.length}) == Node exporter bytes for a log with a photo layer (blobs decoded from the save file)`, Buffer.compare(png, Buffer.from(nodeEx.bytes)) === 0, '==', true);
    fs.writeFileSync(path.join(OUT, 'photo.psd'), png); fs.writeFileSync(path.join(OUT, 'photo_display.raw'), Buffer.from(nodeEx.display)); fs.writeFileSync(path.join(OUT, 'photo_meta.json'), J({ W: 1024, display: path.join(OUT, 'photo_display.raw') }));
    const py = spawnSync(process.env.PYTHON || 'python3', ['-I', path.join(__dirname, 'check_layers_psd.py'), path.join(OUT, 'photo.psd'), path.join(OUT, 'photo_meta.json')], { encoding: 'utf8' }); if (py.status !== 0) { console.error(py.stderr); process.exit(2); } const R = JSON.parse(py.stdout.trim().split('\n').pop()); num.I7 = R;
    chk('I7', 'psd-tools: 3 layers (Background, Layer 1, photo) and merged image within 1 level', R.names.length === 3 && R.merged_max_diff <= 1, '==', true); }
  // ---- I4 reload
  { await ev(() => { window.__saved = 0; const e = window.__ed; e.reset(); e.params.layer = 1; e.params.tool = 'hard'; e.begin(100, 100); e.move(500, 300); e.end(); e.importPixels(window.__noise); }); const hb = await cur(), nb = await ev(() => window.__ed.ops.length);
    await pg.waitForFunction((n) => window.__saved === n, nb, { timeout: 15000 }).catch(() => {}); const saved = await ev(() => window.__saved); const lsThrows = await ev(() => { try { localStorage.setItem('probe', 'x'.repeat(6 * 1024 * 1024)); localStorage.removeItem('probe'); return false; } catch (e) { return true; } });
    num.I4 = { saveJsonChars: num.I4size, localStorage6MBThrows: lsThrows }; await pg.reload(); await pg.waitForFunction(() => window.__ed); await pg.waitForFunction(() => window.__ed.ops.length > 3, null, { timeout: 15000 }).catch(() => {});
    chk('I4', `autosave reported ${saved} ops; after reload the page has the same ops count and hashes (localStorage 6 MB write throws here: ${lsThrows}; one noise photo = ${(num.I4size / 1e6).toFixed(1)} MB of JSON)`, saved === nb && (await ev(() => window.__ed.ops.length)) === nb && J(await cur()) === J(hb), '==', true); }
  chk('I3', 'no page errors (desktop)', pg.errs.length, '==', 0);
  // ---- I5 12 MP through the file input
  const mkPng = (w, h) => ev(async ([w, h]) => { const c = document.createElement('canvas'); c.width = w; c.height = h; const g = c.getContext('2d'); const gr = g.createLinearGradient(0, 0, w, h); gr.addColorStop(0, '#f00'); gr.addColorStop(1, '#00f'); g.fillStyle = gr; g.fillRect(0, 0, w, h); const b = await new Promise((r) => c.toBlob(r, 'image/png')); return Array.from(new Uint8Array(await b.arrayBuffer())); }, [w, h]);
  for (const [w, h, tag] of [[4000, 3000, 'landscape'], [3000, 4000, 'portrait']]) { await ev(() => { window.__ed.reset(); window.__photoMs = null; }); const buf = Buffer.from(await mkPng(w, h)); const n0 = await ev(() => window.__ed.ops.length);
    await pg.setInputFiles('#photo', { name: tag + '.png', mimeType: 'image/png', buffer: buf }); await pg.waitForFunction(() => window.__photoMs, null, { timeout: 30000 }); const ms = await ev(() => window.__photoMs);
    const g = await ev(() => { const e = window.__ed, l = e.st.L[e.params.layer].pix, a = (x, y) => l[(y * 1024 + x) * 4 + 3]; return { r64: a(512, 64), r127: a(512, 127), r128: a(512, 128), r895: a(512, 895), r896: a(512, 896), c0: a(0, 512), c64: a(64, 512), c127: a(127, 512), c128: a(128, 512), c895: a(895, 512), c896: a(896, 512), r0: a(512, 0), n: e.ops.length }; });
    const ok = tag === 'landscape' ? g.r64 === 0 && g.r127 === 0 && g.r128 === 1 && g.r895 === 1 && g.r896 === 0 && g.c0 === 1 : g.c64 === 0 && g.c127 === 0 && g.c128 === 1 && g.c895 === 1 && g.c896 === 0 && g.r0 === 1;
    chk('I5', `${tag} 12 MP (${w}x${h}) fits by "contain" with transparent bars exactly where the geometry says`, ok && g.n - n0 === 1, '==', true); chk('I5', `${tag} import wall time ${Math.round(ms)} ms`, ms, '<=', 5000); }
  chk('I5', 'no page errors (12 MP)', pg.errs.length, '==', 0); await pg.ctx.close();
  // ---- I6 phone
  { const ph = await open(null, { viewport: { width: 390, height: 844 }, deviceScaleFactor: 3, isMobile: true, hasTouch: true }); const cdp = await ph.ctx.newCDPSession(ph), sleep = (ms) => new Promise((r) => setTimeout(r, ms)); await ph.evaluate(() => { window.__ed.reset(); document.getElementById('side').classList.add('open'); }); await sleep(500);
    const r = await ph.evaluate(() => { const b = document.getElementById('addp').getBoundingClientRect(); return [Math.round(b.width), Math.round(b.height)]; }); chk('I6', `Add photo button ${r.join('x')} >= 44 px both ways`, r[0] >= 44 && r[1] >= 44, '==', true);
    const buf = Buffer.from(await (async () => { const p2 = await br.newPage(); await p2.goto('about:blank'); const a = await p2.evaluate(async () => { const c = document.createElement('canvas'); c.width = 1600; c.height = 900; const g = c.getContext('2d'); g.fillStyle = '#4a8'; g.fillRect(0, 0, 1600, 900); const b = await new Promise((r) => c.toBlob(r, 'image/png')); return Array.from(new Uint8Array(await b.arrayBuffer())); }); await p2.close(); return a; })());
    const n0 = await ph.evaluate(() => window.__ed.ops.length); await ph.setInputFiles('#photo', { name: 'p.png', mimeType: 'image/png', buffer: buf }); await ph.waitForFunction(() => window.__photoMs, null, { timeout: 30000 }); chk('I6', 'choosing a photo on the phone adds +1 log entry and a layer', (await ph.evaluate(() => window.__ed.ops.length)) - n0 === 1, '==', true);
    await ph.evaluate(() => document.getElementById('side').classList.remove('open')); await sleep(500); const v = await ph.evaluate(() => { const r = document.getElementById('view').getBoundingClientRect(); return [r.left + r.width / 2, r.top + r.height / 2]; });
    const T = (t, pts) => cdp.send('Input.dispatchTouchEvent', { type: t, touchPoints: pts.map(([x, y, id]) => ({ x, y, id })) }); await T('touchStart', [[v[0] - 40, v[1], 1]]); await T('touchStart', [[v[0] - 40, v[1], 1], [v[0] + 40, v[1], 2]]); await sleep(60); await T('touchEnd', []); await sleep(200);
    chk('I6', 'two-finger tap undoes the photo (-1 entry)', n0 === (await ph.evaluate(() => window.__ed.ops.length)), '==', true); chk('I6', 'no page errors (phone)', ph.errs.length, '==', 0); await ph.ctx.close(); }
  await br.close(); srv.close();
  const out = { n_checks: rec.length, gate: fails.length ? 'FAIL' : 'PASS', fails, numbers: num, checks: rec, node: process.version }; fs.writeFileSync(path.join(OUT, 'photo.json'), J(out, null, 1)); console.log(J({ ...out, checks: undefined }, null, 1)); process.exit(fails.length ? 1 : 0);
})().catch((e) => { console.error(e); process.exit(2); });
