// Usage: node editor/run_mobile.js   Editor v0.2 mobile pass: M1-M9 (pre-registered in witness_log/HYPOTHESES.md before this file existed). Emulated phone in Chromium (touch via CDP); needs system Chrome (CHROMIUM env).
const fs = require('fs'), path = require('path'), http = require('http'), { execFileSync } = require('child_process'), S = require('../stack.js'), { exportLog } = require('./export_psd.js');
const ROOT = path.join(__dirname, '..'), OUT = path.join(__dirname, 'out'); fs.mkdirSync(OUT, { recursive: true }); const rec = [], fails = [], num = {};
const mark = (m) => console.error('[' + new Date().toISOString().slice(11, 19) + '] ' + m);
const chk = (id, name, value, cmp, limit) => { mark(id + ' ' + String(name).slice(0, 110)); const pass = cmp === '<=' ? value <= limit : cmp === '>=' ? value >= limit : value === limit; rec.push({ id, name, value, cmp, limit, pass }); if (!pass) fails.push({ id, name, value, cmp, limit }); };
const med = (a) => a.slice().sort((x, y) => x - y)[a.length >> 1], pct = (a, p) => a.slice().sort((x, y) => x - y)[Math.min(a.length - 1, Math.floor(a.length * p))], sleep = (ms) => new Promise((r) => setTimeout(r, ms));
(async () => {
  execFileSync(process.execPath, [path.join(__dirname, 'build_dist.js'), path.join(OUT, 'dist')], { stdio: 'pipe' }); execFileSync(process.execPath, [path.join(__dirname, 'build_dist.js'), path.join(OUT, 'single'), '--single'], { stdio: 'pipe' });
  const { chromium } = require('playwright-core'), srv = http.createServer((q, r) => { const f = path.join(ROOT, decodeURIComponent(q.url.split('?')[0])); if (!f.startsWith(ROOT) || !fs.existsSync(f) || fs.statSync(f).isDirectory()) { r.writeHead(404); return r.end(); }
    r.writeHead(200, { 'content-type': f.endsWith('.js') ? 'text/javascript' : f.endsWith('.html') ? 'text/html' : f.endsWith('.webmanifest') ? 'application/manifest+json' : f.endsWith('.png') ? 'image/png' : 'application/octet-stream' }); fs.createReadStream(f).pipe(r); }).listen(0, '127.0.0.1'); await new Promise((r) => srv.on('listening', r));
  const base = 'http://127.0.0.1:' + srv.address().port, br = await chromium.launch({ executablePath: process.env.CHROMIUM || '/opt/pw-browsers/chromium', args: ['--no-sandbox'] });
  const phone = async (vp, url, init, opts = {}) => { const ctx = await br.newContext({ viewport: vp, deviceScaleFactor: 3, isMobile: true, hasTouch: true, ...opts }), pg = await ctx.newPage(), errs = []; pg.on('pageerror', (e) => errs.push(e.message)); pg.on('console', (m) => { if (m.type() === 'error' && !(m.location().url || '').includes('uncached-probe')) errs.push(m.text() + ' @' + (m.location().url || '')); }); pg.setDefaultTimeout(120000); if (init) await pg.addInitScript(init);
    await pg.goto(url); await pg.waitForFunction(() => window.__ed); pg.errs = errs; pg.ctx = ctx; pg.cdp = await ctx.newCDPSession(pg); return pg; };
  const T = (pg, type, pts) => pg.cdp.send('Input.dispatchTouchEvent', { type, touchPoints: pts.map(([x, y, id]) => ({ x, y, id })) });
  const rectOf = (pg, sel) => pg.evaluate((s) => { const r = document.querySelector(s).getBoundingClientRect(); return { x: r.left, y: r.top, w: r.width, h: r.height }; }, sel);
  const settle = (pg) => pg.evaluate(() => new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(() => setTimeout(r, 30)))));
  const ops = (pg) => pg.evaluate(() => window.__ed.ops.length), V = (pg) => pg.evaluate(() => ({ ...window.__V }));
  const oneStroke = async (pg, u0, v0, u1, v1, id = 1) => { const c = await rectOf(pg, '#c'), p = (u, v) => [c.x + u * c.w, c.y + v * c.h]; await T(pg, 'touchStart', [[...p(u0, v0), id]]); for (let i = 1; i <= 10; i++) await T(pg, 'touchMove', [[...p(u0 + (u1 - u0) * i / 10, v0 + (v1 - v0) * i / 10), id]]); await T(pg, 'touchEnd', []); };
  const refoldSame = (pg) => pg.evaluate(() => { const a = window.__ed.hashes(), b = Editor.refold(JSON.parse(JSON.stringify(window.__ed.ops)), window.__ed.W); return a.comp === b.comp && JSON.stringify(a.layers) === JSON.stringify(b.layers); });
  const PH = { width: 390, height: 844 }, SRC = base + '/editor/index.html';

  // ---- M1 / M2 / M3 gestures
  mark('section  M1 / M2 / M3');
  const A = await phone(PH, SRC); await oneStroke(A, 0.2, 0.3, 0.7, 0.35); await oneStroke(A, 0.2, 0.5, 0.7, 0.55); await oneStroke(A, 0.2, 0.7, 0.7, 0.65); const n3 = await ops(A);
  { const c = await rectOf(A, '#view'), cx = c.x + c.w / 2, cy = c.y + c.h / 2, n0 = await ops(A), v0 = await V(A);
    await T(A, 'touchStart', [[cx - 40, cy, 1]]); await T(A, 'touchStart', [[cx - 40, cy, 1], [cx + 40, cy, 2]]); for (let i = 1; i <= 8; i++) await T(A, 'touchMove', [[cx - 40 - i * 5, cy, 1], [cx + 40 + i * 5, cy, 2]]); await settle(A); const v1 = await V(A);   // distance 80 -> 160
    for (let i = 1; i <= 6; i++) await T(A, 'touchMove', [[cx - 80 + i * 8, cy + i * 5, 1], [cx + 80 + i * 8, cy + i * 5, 2]]); await settle(A); const v2 = await V(A); await T(A, 'touchEnd', []);
    const ratio = v1.s / v0.s, panX = v2.x - v1.x, panY = v2.y - v1.y; num.M1 = { ratio, panX, panY, ops: [n0, await ops(A)] };
    chk('M1', `pinch (finger distance x2.0) zoomed the view x${ratio.toFixed(3)} (limit 2.0 +-5%)`, Math.abs(ratio - 2) <= 0.1, '==', true); chk('M1', `two-finger drag of (48, 30) px panned the view by (${panX.toFixed(2)}, ${panY.toFixed(2)}) px (limit 1 px)`, Math.abs(panX - 48) <= 1 && Math.abs(panY - 30) <= 1, '==', true); chk('M1', 'the whole pinch+pan gesture added no log entry', (await ops(A)) === n0, '==', true); }
  { await A.evaluate(() => { document.getElementById('zfit').click(); }); const c = await rectOf(A, '#c'), p = (u, v) => [c.x + u * c.w, c.y + v * c.h], before = await A.evaluate(() => ({ n: window.__ed.ops.length, h: window.__ed.hashes().layers }));
    await T(A, 'touchStart', [[...p(0.3, 0.2), 1]]); for (let i = 1; i <= 6; i++) await T(A, 'touchMove', [[...p(0.3 + i * 0.05, 0.2 + i * 0.02), 1]]); const mid = await A.evaluate(() => window.__ed.busy);
    await T(A, 'touchStart', [[...p(0.6, 0.22), 1], [...p(0.4, 0.8), 2]]); const afterSecond = await A.evaluate(() => ({ busy: window.__ed.busy, n: window.__ed.ops.length, h: window.__ed.hashes().layers }));
    await T(A, 'touchEnd', [[...p(0.4, 0.8), 2]]); await T(A, 'touchMove', [[...p(0.4, 0.82), 2], ]).catch(() => {}); const leftover = await ops(A); await T(A, 'touchEnd', []); await sleep(50);
    chk('M2', `a second finger cancels a live stroke: busy ${mid} -> ${afterSecond.busy}, layer hashes equal the pre-stroke ones, no log entry`, mid === true && afterSecond.busy === false && JSON.stringify(afterSecond.h) === JSON.stringify(before.h) && afterSecond.n === before.n, '==', true);
    chk('M2', 'the finger left over after the gesture draws nothing', leftover === before.n, '==', true); await oneStroke(A, 0.3, 0.4, 0.6, 0.45); chk('M2', 'after all fingers lifted, one finger draws again: exactly 1 stroke logged', (await ops(A)) === before.n + 1, '==', true); }
  { const c = await rectOf(A, '#view'), cx = c.x + c.w / 2, cy = c.y + c.h / 2, N = await ops(A), res = {};
    await T(A, 'touchStart', [[cx - 30, cy, 1]]); await T(A, 'touchStart', [[cx - 30, cy, 1], [cx + 30, cy, 2]]); await sleep(90); await T(A, 'touchEnd', []); await sleep(60); res.undo = await ops(A); res.same1 = await refoldSame(A);
    await T(A, 'touchStart', [[cx - 40, cy, 1]]); await T(A, 'touchStart', [[cx - 40, cy, 1], [cx, cy, 2]]); await T(A, 'touchStart', [[cx - 40, cy, 1], [cx, cy, 2], [cx + 40, cy, 3]]); await sleep(90); await T(A, 'touchEnd', []); await sleep(60); res.redo = await ops(A); res.same2 = await refoldSame(A);
    await T(A, 'touchStart', [[cx - 30, cy, 1]]); await T(A, 'touchStart', [[cx - 30, cy, 1], [cx + 30, cy, 2]]); await sleep(450); await T(A, 'touchEnd', []); await sleep(60); res.slow = await ops(A);
    await T(A, 'touchStart', [[cx - 30, cy, 1]]); await T(A, 'touchStart', [[cx - 30, cy, 1], [cx + 30, cy, 2]]); for (let i = 1; i <= 5; i++) await T(A, 'touchMove', [[cx - 30 + i * 10, cy, 1], [cx + 30 + i * 10, cy, 2]]); await T(A, 'touchEnd', []); await sleep(60); res.moved = await ops(A); num.M3 = { N, ...res };
    chk('M3', `two-finger tap undoes one entry (${N} -> ${res.undo}), hashes equal a refold`, res.undo === N - 1 && res.same1, '==', true); chk('M3', `three-finger tap redoes it (${res.undo} -> ${res.redo}), hashes equal a refold`, res.redo === N && res.same2, '==', true);
    chk('M3', `a slow (450 ms) two-finger touch (${res.slow}) and a two-finger drag (${res.moved}) do NOT undo`, res.slow === N && res.moved === N, '==', true); }
  chk('M1', 'no page errors during the gesture tests', A.errs.length, '==', 0); await A.ctx.close();

  // ---- M4 layout at two phone sizes, M5 swatch/size
  mark('section  M4 layout at');
  for (const [vp, minView] of [[{ width: 390, height: 844 }, 0.5], [{ width: 360, height: 640 }, 0.4]]) { const P = await phone(vp, SRC);
    const m = await P.evaluate(() => { const rect = (s) => { const r = document.querySelector(s).getBoundingClientRect(); return { l: r.left, t: r.top, w: r.width, h: r.height, b: r.bottom }; }, btn = (s) => [...document.querySelectorAll(s)].map((b) => { const r = b.getBoundingClientRect(); return Math.min(r.width, r.height); });
      return { scrollH: Math.max(document.documentElement.scrollHeight, document.body.scrollHeight), innerH: innerHeight, innerW: innerWidth, view: rect('#view'), canvas: rect('#c'), dock: rect('#dock'), tools: btn('#tools button'), sw: btn('#sw button'), top: btn('header .mob, #undo, #redo').filter((v) => v > 0) }; });
    const minBtn = Math.min(...m.tools, ...m.sw, ...m.top); num['M4_' + vp.width] = { ...m, minBtn };
    chk('M4', `${vp.width}x${vp.height}: page height ${m.scrollH} <= screen ${m.innerH}; workspace ${(100 * m.view.h / m.innerH).toFixed(0)}% of height (>= ${minView * 100}%); canvas ${(100 * m.canvas.w / m.innerW).toFixed(0)}% of width (>= 90%)`, m.scrollH <= m.innerH && m.view.h / m.innerH >= minView && m.canvas.w / m.innerW >= 0.9, '==', true);
    chk('M4', `${vp.width}x${vp.height}: smallest tool/swatch/top-bar touch target ${minBtn.toFixed(0)} px (>= 44); dock top at ${(100 * m.dock.t / m.innerH).toFixed(0)}% of the screen height (>= 65%)`, minBtn >= 44 && m.dock.t / m.innerH >= 0.65, '==', true);
    await P.tap('#m-menu'); await sleep(300); const sheet = await P.evaluate(() => { const a = document.getElementById('side').getBoundingClientRect(), e = document.getElementById('m-png').getBoundingClientRect(), l = document.querySelector('#layers .layer').getBoundingClientRect(); return { top: a.top, bottom: a.bottom, innerH: innerHeight, png: e.bottom, layer: l.top }; });
    chk('M4', `${vp.width}x${vp.height}: Menu opens a sheet that ends at the screen bottom (${sheet.bottom.toFixed(0)}/${sheet.innerH}) and shows the layers and export buttons inside the screen`, Math.abs(sheet.bottom - sheet.innerH) <= 2 && sheet.png <= sheet.innerH && sheet.layer >= 0 && sheet.top >= 0, '==', true); await P.tap('#m-close'); await sleep(250);
    if (vp.width === 390) { await P.tap('#sw button:nth-child(3)'); await P.fill('#msize', '30'); await P.dispatchEvent('#msize', 'input'); await oneStroke(P, 0.3, 0.3, 0.7, 0.4); const o = await P.evaluate(() => window.__ed.ops.at(-1)), want = [0xe5, 0x39, 0x35].map((v) => v / 255);
      chk('M5', `tapping the red swatch and setting size 30 in the dock: logged colour ${o.c.map((v) => Math.round(v * 255))} (expected 229,57,53), size ${o.r}`, o.op === 'stroke' && o.c.every((v, i) => Math.abs(v - want[i]) <= 1 / 255 + 1e-4) && o.r === 30, '==', true); }
    chk('M4', `${vp.width}x${vp.height}: no page errors`, P.errs.length, '==', 0); await P.ctx.close(); }

  // ---- M6 share
  mark('section  M6 share');
  { const P = await phone(PH, SRC, () => { Object.defineProperty(navigator, 'canShare', { value: (d) => !!(d && d.files && d.files[0] && d.files[0].type === 'image/png'), configurable: true }); Object.defineProperty(navigator, 'share', { value: async (d) => { window.__sharedFile = d.files[0]; window.__sharedTitle = d.title; }, configurable: true }); });
    await oneStroke(P, 0.2, 0.3, 0.8, 0.5); await P.tap('#m-share'); await sleep(500); const r = await P.evaluate(async () => { const f = window.__sharedFile; if (!f) return null; const bmp = await createImageBitmap(f), oc = document.createElement('canvas'); oc.width = bmp.width; oc.height = bmp.height; const cx = oc.getContext('2d'); cx.drawImage(bmp, 0, 0); const live = document.getElementById('c').getContext('2d'); let s = 99, bad = 0; const rnd = () => (s = (Math.imul(s, 1664525) + 1013904223) >>> 0) / 4294967296; for (let i = 0; i < 200; i++) { const x = (rnd() * 1024) | 0, y = (rnd() * 1024) | 0, a = cx.getImageData(x, y, 1, 1).data, b = live.getImageData(x, y, 1, 1).data; if (a.some((v, k) => v !== b[k])) bad++; } return { type: f.type, size: f.size, name: f.name, bad, mode: window.__shared }; });
    chk('M6', `Share passes one PNG file (${r && r.name}, ${r && r.size} bytes, ${r && r.type}) to navigator.share; it equals the canvas for 200 random pixels`, !!r && r.type === 'image/png' && r.size > 1000 && r.bad === 0 && r.mode === 'share', '==', true); await P.ctx.close(); }
  { const P = await phone(PH, SRC, () => { Object.defineProperty(navigator, 'canShare', { value: undefined, configurable: true }); Object.defineProperty(navigator, 'share', { value: undefined, configurable: true }); });
    await oneStroke(P, 0.2, 0.3, 0.8, 0.5); await P.tap('#m-share'); await sleep(600); const s = await P.evaluate(async () => { const box = document.getElementById('saver'), im = document.getElementById('saveimg'); if (box.hidden) return null; await im.decode(); const oc = document.createElement('canvas'); oc.width = im.naturalWidth; oc.height = im.naturalHeight; const cx = oc.getContext('2d'); cx.drawImage(im, 0, 0); const live = document.getElementById('c').getContext('2d'); let q = 5, bad = 0; const rnd = () => (q = (Math.imul(q, 1664525) + 1013904223) >>> 0) / 4294967296; for (let i = 0; i < 200; i++) { const x = (rnd() * 1024) | 0, y = (rnd() * 1024) | 0, a = cx.getImageData(x, y, 1, 1).data, b = live.getImageData(x, y, 1, 1).data; if (a.some((v, k) => v !== b[k])) bad++; } const r = im.getBoundingClientRect(); return { w: im.naturalWidth, bad, shown: r.width > 100, mode: window.__shared }; });
    chk('M6', `without the Share API a touch device gets a "touch and hold to save" overlay showing the PNG (${s && s.w} px, equals the canvas for 200 random pixels)`, !!s && s.w === 1024 && s.bad === 0 && s.shown && s.mode === 'saver', '==', true); await P.tap('#saveclose'); await sleep(200); chk('M6', 'the overlay closes', await P.evaluate(() => document.getElementById('saver').hidden), '==', true); await P.ctx.close(); }
  { const P = await phone({ width: 1100, height: 800 }, SRC, null, { isMobile: false, hasTouch: false }); const c = await rectOf(P, '#c'); await P.mouse.move(c.x + c.w * 0.2, c.y + c.h * 0.3); await P.mouse.down(); await P.mouse.move(c.x + c.w * 0.6, c.y + c.h * 0.5, { steps: 6 }); await P.mouse.up();
    const dl = P.waitForEvent('download', { timeout: 8000 }).catch(() => null); await P.click('#png'); const d = await dl; chk('M6', `on a desktop (mouse) the Export PNG button downloads a file (${d ? d.suggestedFilename() : 'none'})`, !!d && d.suggestedFilename() === 'painting.png', '==', true); await P.ctx.close(); }

  // ---- M7 PWA installable + offline (built dist over http://127.0.0.1)
  mark('section  M7 PWA insta');
  { const DIST = base + '/editor/out/dist/index.html', P = await phone(PH, DIST); await P.evaluate(() => navigator.serviceWorker.ready.then((r) => !!r.active)); await P.reload(); await P.waitForFunction(() => window.__ed && navigator.serviceWorker.controller);
    const man = await P.evaluate(async () => { const j = await (await fetch('manifest.webmanifest')).json(), icons = []; for (const i of j.icons) { const r = await fetch(i.src), b = await createImageBitmap(await r.blob()); icons.push([i.sizes, r.status, b.width]); } return { j, icons }; });
    const j = man.j; chk('M7', `manifest: name ${j.name}, display ${j.display}, start_url ${j.start_url}, icons ${man.icons.map((i) => i[0] + ':' + i[1]).join(' ')}`, !!j.name && j.display === 'standalone' && !!j.start_url && man.icons.length >= 2 && man.icons.every((i) => i[1] === 200 && `${i[2]}x${i[2]}` === i[0]), '==', true);
    await P.ctx.setOffline(true); await P.reload(); await P.waitForFunction(() => window.__ed); await oneStroke(P, 0.2, 0.3, 0.8, 0.5); const off = await P.evaluate(() => { const ed = window.__ed, psd = ed.exportPSD(); let s = ''; for (let i = 0; i < psd.length; i += 0x8000) s += String.fromCharCode.apply(null, psd.subarray(i, i + 0x8000)); let netBlocked = false; return fetch('uncached-probe-' + Date.now(), { cache: 'no-store' }).then(() => false, () => true).then((blocked) => ({ online: navigator.onLine, netBlocked: blocked, n: ed.ops.length, b64: btoa(s), log: ed.save(), sw: !!navigator.serviceWorker.controller })); });
    const node = await exportLog(off.log); chk('M7', `offline (a network fetch of an uncached URL fails: ${off.netBlocked}; service worker controls the page): reload works, a stroke paints (${off.n} ops), PSD export identical to the Node exporter's`, off.netBlocked && off.sw && off.n >= 4 && Buffer.compare(Buffer.from(off.b64, 'base64'), Buffer.from(node.bytes)) === 0, '==', true);
    chk('M7', 'no page errors on the built page (online and offline)', P.errs.length, '==', 0); await P.ctx.setOffline(false); await P.ctx.close(); }

  // ---- M8 emulated CPU throttling
  mark('section  M8 emulated ');
  { const P = await phone(PH, SRC), res = {}; for (const rate of [1, 4, 6]) { await P.cdp.send('Emulation.setCPUThrottlingRate', { rate }); res[rate] = {};
      for (const [name, tool, size] of [['hard14', 'hard', 14], ['soft60', 'soft', 60], ['smudge30', 'smudge', 30]]) { await P.evaluate(([t, s]) => { const ed = window.__ed; ed.params.tool = t; ed.params.size = s; ed.moveMs.length = 0; }, [tool, size]);
        const c = await rectOf(P, '#c'), p = (u, v) => [c.x + u * c.w, c.y + v * c.h]; await T(P, 'touchStart', [[...p(0.15, 0.5), 1]]); for (let i = 1; i <= 60; i++) await T(P, 'touchMove', [[...p(0.15 + i * 0.012, 0.5 + Math.sin(i / 6) * 0.2), 1]]); await T(P, 'touchEnd', []); const ms = await P.evaluate(() => window.__ed.moveMs.slice()); res[rate][name] = { median: med(ms), p95: pct(ms, 0.95), max: Math.max(...ms), n: ms.length }; } }
    await P.cdp.send('Emulation.setCPUThrottlingRate', { rate: 1 }); num.M8 = res; const worst4 = Math.max(...Object.values(res[4]).map((x) => x.median)), worst4p = Math.max(...Object.values(res[4]).map((x) => x.p95));
    chk('M8', `emulated 4x slower CPU: pointermove handler median <= ${worst4.toFixed(1)} ms, p95 <= ${worst4p.toFixed(1)} ms across hard / soft-60 / smudge-30 (6x: p95 ${Math.max(...Object.values(res[6]).map((x) => x.p95)).toFixed(1)} ms)`, worst4 <= 16 && worst4p <= 33, '==', true); await P.ctx.close(); }

  // ---- M9 single file from file://
  mark('section  M9 single fi');
  { const P = await phone({ width: 1000, height: 800 }, 'file://' + path.join(OUT, 'single', 'oplogpic.html'), null, { isMobile: false, hasTouch: false }); const c = await rectOf(P, '#c'); await P.mouse.move(c.x + c.w * 0.2, c.y + c.h * 0.3); await P.mouse.down(); await P.mouse.move(c.x + c.w * 0.7, c.y + c.h * 0.5, { steps: 10 }); await P.mouse.up();
    const got = await P.evaluate(() => { const ed = window.__ed, psd = ed.exportPSD(); let s = ''; for (let i = 0; i < psd.length; i += 0x8000) s += String.fromCharCode.apply(null, psd.subarray(i, i + 0x8000)); return { b64: btoa(s), log: ed.save(), n: ed.ops.length }; }); const node = await exportLog(got.log);
    chk('M9', `single-file build (${fs.statSync(path.join(OUT, 'single', 'oplogpic.html')).size} bytes) from file://: paints, 0 page errors, PSD identical to the Node exporter's`, P.errs.length === 0 && got.n === 4 && Buffer.compare(Buffer.from(got.b64, 'base64'), Buffer.from(node.bytes)) === 0, '==', true); await P.ctx.close(); }
  await br.close(); srv.close();
  const out = { n_checks: rec.length, gate: fails.length ? 'FAIL' : 'PASS', fails, numbers: num, checks: rec, node: process.version, cpus: require('os').cpus()[0].model };
  fs.writeFileSync(path.join(OUT, 'mobile.json'), JSON.stringify(out, null, 1)); console.log(JSON.stringify({ ...out, checks: undefined }, null, 1)); process.exit(fails.length ? 1 : 0);
})();
