// Usage: node editor/run_history.js   Level 1b history: A1-A3, R1-R2, V1, L1-L2, U (pre-registered in witness_log/HYPOTHESES.md before this file existed). Needs system Chrome (CHROMIUM), Node >= 18.
const fs = require('fs'), path = require('path'), http = require('http');
const S = require('../stack.js'), Br = require('../filters/brush.js'), Bl = require('../filters/blur.js'), LO = require('./layer_ops.js'), SO = require('./select_ops.js'), IO = require('./img_ops.js'), HO = require('./history_ops.js');
const ROOT = path.join(__dirname, '..'), OUT = path.join(__dirname, 'out'), rec = [], fails = [], num = {}; fs.mkdirSync(OUT, { recursive: true });
const chk = (id, name, value, cmp, limit) => { const pass = cmp === '<=' ? value <= limit : cmp === '>=' ? value >= limit : value === limit; rec.push({ id, name, value, cmp, limit, pass }); if (!pass) fails.push({ id, name, value, cmp, limit }); console.error((pass ? 'ok   ' : 'FAIL ') + id + ' ' + name); };
const rng = (seed) => { let s = seed >>> 0; return () => (s = (Math.imul(s, 1664525) + 1013904223) >>> 0) / 4294967296; }, r2 = (x) => Math.round(x * 100) / 100, r4 = (x) => Math.round(x * 1e4) / 1e4, J = JSON.stringify, sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const base = (st, o) => (o.op === 'blur' ? Bl.applyOp(st, o) : Br.applyOp(st, o)), applyOp = (st, o) => (LO.apply(st, o) || IO.apply(st, o) || HO.apply(st, o) || SO.apply(st, o, base) ? undefined : base(st, o));
const fold = (list, W = 256) => { const st = S.newState(W); st.blobs = new Map(); for (const o of HO.expand(list)) applyOp(st, o); return { comp: S.hashF32(S.composite(st)), layers: Object.keys(st.L).map((k) => S.hashF32(st.L[k].pix)) }; };
const L0 = [{ op: 'layer', id: 0, mode: 'normal', opacity: 1, mask: false }, { op: 'fill', layer: 0, c: [1, 1, 1], a: 1 }, { op: 'layer', id: 1, mode: 'normal', opacity: 1, mask: false }];
const pts = (a, b, n = 7) => Array.from({ length: n }, (_, i) => [r2(a[0] + (b[0] - a[0]) * i / (n - 1) + (i % 2) * 6), r2(a[1] + (b[1] - a[1]) * i / (n - 1) - (i % 3) * 4)]);
(async () => {
  // ---- A1 amend == authored that way (engine level)
  { const paint = { op: 'stroke', layer: 1, kind: 'hard', pts: pts([20, 40], [220, 200]), r: 22, c: [0.2, 0.6, 0.3], a: 1 }, dep = [{ op: 'stroke', layer: 1, kind: 'hard', pts: pts([30, 210], [230, 60]), r: 18, c: [0.1, 0.2, 0.9], a: 0.9 }, { op: 'smudge', layer: 1, pts: pts([40, 80], [200, 160]), r: 16, s: 0.6 }];
    const targets = { hard: { op: 'stroke', layer: 1, kind: 'hard', pts: pts([50, 30], [200, 220]), r: 20, c: [0.9, 0.1, 0.1], a: 1 }, soft: { op: 'stroke', layer: 1, kind: 'soft', pts: pts([50, 30], [200, 220]), r: 26, c: [0.9, 0.1, 0.1], a: 0.8 }, erase: { op: 'stroke', layer: 1, kind: 'erase', pts: pts([50, 30], [200, 220]), r: 20, c: [0, 0, 0], a: 0.9 },
      blur: { op: 'stroke', layer: 1, kind: 'blur', pts: pts([50, 30], [200, 220]), r: 20, s: 0.5 }, smudge: { op: 'smudge', layer: 1, pts: pts([50, 30], [200, 220]), r: 20, s: 0.5 } };
    const SETS = { hard: [{ c: [0.1, 0.9, 0.9] }, { r: 40 }, { a: 0.4 }], soft: [{ c: [0.1, 0.9, 0.9], r: 14, a: 1 }], erase: [{ a: 0.3 }, { r: 8 }], blur: [{ s: 1 }, { r: 35 }], smudge: [{ s: 0.95 }, { r: 8 }] };
    let bad = 0, same = 0, n = 0; for (const k of Object.keys(targets)) for (const set of SETS[k]) { n++; const pre = [...L0, paint, targets[k], ...dep], am = fold([...pre, { op: 'amend', i: 4, set }]), ref = fold([...L0, paint, { ...targets[k], ...set }, ...dep]); if (J(am) !== J(ref)) bad++; if (J(fold(pre)) === J(am)) same++; }
    chk('A1', `${n} amends over 5 kinds (colour / size / opacity / strength) with a dependent stroke and a smudge after: hashes == log authored with the new values`, bad, '==', 0); chk('A1', 'negative control: every amend changed the picture', same, '==', 0);
    const pre = [...L0, paint, targets.hard, ...dep]; chk('A1', 'two amends on one target: last wins', J(fold([...pre, { op: 'amend', i: 4, set: { r: 10 } }, { op: 'amend', i: 4, set: { r: 40 } }])) === J(fold([...L0, paint, { ...targets.hard, r: 40 }, ...dep])), '==', true);
    const bads = [{ op: 'amend', i: 1, set: { r: 5 } }, { op: 'amend', i: 9, set: { r: 5 } }, { op: 'amend', i: 4, set: { z: 1 } }, { op: 'amend', i: 4, set: { c: [2, 0, 0] } }, { op: 'amend', i: 4, set: { r: 0 } }, { op: 'amend', i: 4, set: { a: 0 } }, { op: 'amend', i: 4, set: {} }, { op: 'amend', i: 4, set: { s: 0.5 } }];
    const t = bads.map((o) => { try { HO.expand([...pre, o]); return 'no'; } catch (e) { return 'throw'; } }); chk('A1', 'invalid amends (non-stroke target, later index, unknown key, c out of range, r 0, a 0, empty, s on a hard brush) all throw', t.join(), '==', bads.map(() => 'throw').join()); }
  // ---- V1 / L1 engine level
  { const r = rng(2), ops = [...L0]; for (let i = 0; i < 100; i++) { const n = 6 + ((r() * 14) | 0), p = Array.from({ length: n }, () => [r2(r() * 1024), r2(r() * 1024)]); ops.push({ op: 'stroke', layer: 1, kind: i % 3 ? 'hard' : 'soft', pts: p, r: 6 + ((r() * 30) | 0), c: [r4(r()), r4(r()), r4(r())], a: r4(0.4 + r() * 0.6) }); }
    const link = await HO.makeLink(1024, ops), back = await HO.parseLink(link); num.L1 = { urlChars: link.length, ops: ops.length }; chk('L1', 'link round trip: decoded ops deep-equal the log (101+2 entries)', J(back.ops) === J(ops) && back.W === 1024, '==', true); chk('L1', `100-stroke session link is ${link.length} characters (prediction <= 40000)`, link.length, '<=', 40000);
    chk('L1', 'a log with a photo is refused', await HO.makeLink(1024, [...L0, { op: 'img', id: 2, sha: 'ab' }]).then(() => 'made', () => 'refused'), '==', 'refused');
    const mid = link.indexOf('&h=') - 20, flipped = link.slice(0, mid) + (link[mid] === 'A' ? 'B' : 'A') + link.slice(mid + 1); chk('V1', 'a link with one payload character changed is refused', await HO.parseLink(flipped).then(() => 'opened', (e) => 'refused'), '==', 'refused');
    const t2 = JSON.parse(J(ops)); t2[50].pts[3][0] += 0.01; chk('V1', 'one coordinate changed (+0.01 px) in one stroke: chain head differs', HO.head(t2) !== HO.head(ops), '==', true); chk('V1', 'head is stable across two calls', HO.head(ops) === HO.head(JSON.parse(J(ops))), '==', true);
    const sw = JSON.parse(J(ops)); [sw[10], sw[11]] = [sw[11], sw[10]]; chk('V1', 'swapping two entries changes the head (order is part of the truth)', HO.head(sw) !== HO.head(ops), '==', true); }
  // ---- browser
  const { chromium } = require('playwright-core'), srv = http.createServer((q, r) => { const f = path.join(ROOT, decodeURIComponent(q.url.split('?')[0])); if (!f.startsWith(ROOT) || !fs.existsSync(f) || fs.statSync(f).isDirectory()) { r.writeHead(404); return r.end(); }
    r.writeHead(200, { 'content-type': f.endsWith('.js') ? 'text/javascript' : f.endsWith('.html') ? 'text/html' : 'application/octet-stream' }); fs.createReadStream(f).pipe(r); }).listen(0, '127.0.0.1');
  await new Promise((r) => srv.on('listening', r)); const url = 'http://127.0.0.1:' + srv.address().port + '/editor/index.html', br = await chromium.launch({ executablePath: process.env.CHROMIUM || '/opt/pw-browsers/chromium', args: ['--no-sandbox'] });
  const open = async (ctx, hash = '') => { const pg = await ctx.newPage(); pg.errs = []; pg.on('pageerror', (e) => pg.errs.push(e.message)); await pg.goto(url + hash); await pg.waitForFunction(() => window.__ed); return pg; };
  const ctxA = await br.newContext({ viewport: { width: 1400, height: 900 } }), pg = await open(ctxA); const ev = (f, a) => pg.evaluate(f, a), cur = () => ev(() => window.__ed.hashes()), ref = (n) => ev((n) => { const e = window.__ed; return Editor.refold(JSON.parse(JSON.stringify(n === undefined ? e.ops : e.ops.slice(0, n))), 1024, e.blobs); }, n);
  const strokes = (k, seed = 1) => ev(([k, seed]) => { const e = window.__ed; let s = seed >>> 0; const rd = () => (s = (Math.imul(s, 1664525) + 1013904223) >>> 0) / 4294967296; for (let i = 0; i < k; i++) { e.params.tool = ['hard', 'soft', 'smudge', 'blur'][i % 4]; e.params.layer = 1; e.params.size = 12 + ((rd() * 30) | 0); e.params.color = [rd(), rd(), rd()]; const x = 100 + rd() * 700, y = 100 + rd() * 700; e.begin(x, y); for (let j = 1; j < 7; j++) e.move(x + j * 25 + rd() * 20, y + (j % 2) * 60 + rd() * 20); e.end(); } }, [k, seed]);
  // ---- A2 / A3
  await ev(() => { window.__ed.reset(); }); await strokes(5, 4); await ev(() => window.__ed.amend(4, { c: [0.05, 0.9, 0.2], r: 33 })); chk('A3', 'live amend: hashes == refold of the log', J(await cur()) === J(await ref()), '==', true); await strokes(2, 9);
  { const n = await ev(() => window.__ed.ops.length); let okU = true, steps = 0; while (await ev(() => window.__ed.canUndo())) { await ev(() => window.__ed.undo()); steps++; if (J(await cur()) !== J(await ref())) okU = false; } const nEnd = await ev(() => window.__ed.ops.length);
    let okR = true, stepsR = 0; while (await ev(() => window.__ed.canRedo())) { await ev(() => window.__ed.redo()); stepsR++; if (J(await cur()) !== J(await ref())) okR = false; }
    chk('A2', `undo all the way (${steps} steps, log ${n} -> ${nEnd}) around an amend: hashes == refold of the prefix at every step`, okU && steps >= 7, '==', true); chk('A2', `redo all the way (${stepsR} steps): same, and back to ${n} entries`, okR && (await ev(() => window.__ed.ops.length)) === n, '==', true); }
  { const sv = await ev(() => window.__ed.save()), h = await cur(); await ev(() => window.__ed.reset()); await ev((s) => window.__ed.load(s), sv); chk('A3', 'save -> load of a log with an amend: hashes equal', J(await cur()) === J(h), '==', true);
    const ex = await ev(() => { const e = window.__ed; return { amends: e.ops.filter((o) => o.op === 'amend').length }; }); chk('A3', 'the amend is one log entry, the target entry is unchanged in the log', ex.amends === 1 && (await ev(() => window.__ed.ops[4].r !== 33)), '==', true); }
  // ---- R2 preview
  { const n = await ev(() => window.__ed.ops.length); let bad = 0; for (const k of [3, 4, 5, Math.floor(n / 2), n - 1, n]) { const p = await ev((k) => window.__ed.preview(k), k), r = await ref(k); if (p.comp !== r.comp || J(p.layers) !== J(r.layers)) bad++; await ev(() => window.__ed.endPreview()); }
    chk('R2', 'preview(k) for k in {3, 4, 5, mid, n-1, n}: state hashes == refold of the first k entries', bad, '==', 0);
    await ev(() => window.__ed.preview(5)); const n0 = await ev(() => window.__ed.ops.length); await ev(() => { const e = window.__ed; e.params.tool = 'hard'; e.begin(100, 100); e.move(300, 300); e.end(); e.undo(); e.addLayer(); e.hideLayer(1, true); }); chk('R2', 'painting / undo / layer ops while previewing log nothing', (await ev(() => window.__ed.ops.length)) === n0, '==', true);
    await ev(() => window.__ed.endPreview()); chk('R2', 'after endPreview the dirty compositor equals the full composite and the canvas shows it', await ev(() => { const e = window.__ed, a = e.D.back, b = Stack.composite(e.st); for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false; const g = document.getElementById('c').getContext('2d'); for (let t = 0; t < 200; t++) { const x = (t * 97) % 1024, y = (t * 211) % 1024, px = g.getImageData(x, y, 1, 1).data, d = e.displayRGBA8(x, y); for (let c = 0; c < 4; c++) if (Math.abs(px[c] - d[c]) > 1) return false; } return true; }), '==', true); }
  // ---- R1 replay
  { await ev(() => { window.__ed.reset(); }); await strokes(37, 21); const n = await ev(() => window.__ed.ops.length), h0 = await cur(), ops0 = await ev(() => JSON.stringify(window.__ed.ops));
    const t0 = Date.now(); const full = await ev(async () => { const r = await window.__ed.replay().done; return r; }); const wall = Date.now() - t0;
    chk('R1', `full replay of ${n} entries finished in ${(wall / 1000).toFixed(1)} s (2..8 s +-0.5)`, full.finished && wall >= 1500 && wall <= 8500, '==', true); chk('R1', 'replay end state hashes == live hashes', full.comp === h0.comp && J(full.layers) === J(h0.layers.length ? (await cur()).layers : []), '==', true);
    chk('R1', 'replay left the log and the live state untouched', (await ev(() => JSON.stringify(window.__ed.ops))) === ops0 && J(await cur()) === J(h0), '==', true);
    const half = await ev(async () => { const c = window.__ed.replay({ totalMs: 3000 }); await new Promise((r) => setTimeout(r, 1300)); c.stop(); return await c.done; }); chk('R1', `a replay stopped after 1.3 s ended unfinished at ${half.steps} of ${half.n}`, !half.finished && half.steps > 3 && half.steps < half.n, '==', true);
    chk('R1', 'after the stopped replay the canvas shows the live picture (200 sampled pixels) and the log is untouched', await ev(() => { const e = window.__ed, g = document.getElementById('c').getContext('2d'); for (let t = 0; t < 200; t++) { const x = (t * 97) % 1024, y = (t * 211) % 1024, px = g.getImageData(x, y, 1, 1).data, d = e.displayRGBA8(x, y); for (let c = 0; c < 4; c++) if (Math.abs(px[c] - d[c]) > 1) return false; } return true; }) && (await ev(() => JSON.stringify(window.__ed.ops))) === ops0, '==', true); }
  // ---- V1 live verify
  { const v1 = await ev(() => window.__ed.verify()), v2 = await ev(() => window.__ed.verify()); num.verify = v1; chk('V1', `verify() on the live editor: ok (${v1.n} entries, ${Math.round(v1.ms)} ms), fingerprint ${v1.fp} stable`, v1.ok && v1.fp === v2.fp && v1.fp.length === 12, '==', true); }
  chk('A2', 'no page errors (desktop)', pg.errs.length, '==', 0);
  // ---- L2 view-only link in a second page of the same browser profile
  { await ev(() => { window.__ed.reset(); }); await strokes(6, 31); await sleep(900); const lsKey = 'psd-oplog-editor-v1', ls = () => ev((k) => localStorage.getItem(k), lsKey), ownBefore = await ls(), hA = await cur();
    await ev(() => document.getElementById('h-share').click()); await pg.waitForFunction(() => window.__lastLink, null, { timeout: 5000 }); const hash = await ev(() => window.__lastLink); const B = await open(ctxA, hash); await B.waitForFunction(() => window.__viewOnly && window.__ed.ops.length > 3, null, { timeout: 8000 });
    chk('L2', 'the opened link shows the same picture as the sender (hashes equal) and the banner', J(await B.evaluate(() => window.__ed.hashes())) === J(hA) && (await B.evaluate(() => !document.getElementById('pvbar').hidden)), '==', true);
    const nB = await B.evaluate(() => { const e = window.__ed; e.params.tool = 'hard'; e.begin(10, 10); e.move(200, 200); e.end(); e.undo(); return e.ops.length; }); const nB0 = await B.evaluate(() => window.__ed.ops.length); await sleep(1000); chk('L2', 'painting in the view-only page is blocked (log length unchanged)', nB === nB0, '==', true);
    chk('L2', "the owner's autosave is untouched after the link was opened and left for 1 s", (await ls()) === ownBefore && (await B.evaluate((k) => localStorage.getItem(k), lsKey)) === ownBefore, '==', true);
    await B.evaluate(() => document.getElementById('pv-copy').click()); await B.evaluate(() => { const e = window.__ed; e.params.tool = 'hard'; e.params.layer = 1; e.begin(10, 10); e.move(200, 200); e.end(); }); await sleep(900);
    chk('L2', '"Edit a copy" allows painting (+1 entry) and then autosaves (storage now differs)', (await B.evaluate(() => window.__ed.ops.length)) === nB0 + 1 && (await ls()) !== ownBefore, '==', true);
    const bad = hash.slice(0, hash.indexOf('&h=') - 5) + 'AAAAA' + hash.slice(hash.indexOf('&h=')); const C = await open(ctxA, bad); await sleep(800); chk('L2', 'an altered link is refused with a message and nothing is loaded', (await C.evaluate(() => document.getElementById('hmsg').textContent)).startsWith('Link not opened') && !(await C.evaluate(() => window.__viewOnly)), '==', true); await B.close(); await C.close(); }
  await ctxA.close();
  // ---- U phone
  { const ctx = await br.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 3, isMobile: true, hasTouch: true }), ph = await open(ctx); await ph.evaluate(() => window.__ed.reset());
    await ph.evaluate(() => { const e = window.__ed; e.params.layer = 1; e.params.tool = 'hard'; for (let i = 0; i < 4; i++) { e.begin(100 + i * 100, 100); e.move(150 + i * 100, 300); e.end(); } document.getElementById('side').classList.add('open'); }); await sleep(600);
    const sizes = await ph.evaluate(() => ['h-play', 'h-ver', 'h-share'].map((id) => { const r = document.getElementById(id).getBoundingClientRect(); return [Math.round(r.width), Math.round(r.height)]; })); chk('U', 'Replay / Verify / Share link buttons >= 44 px both ways', sizes.every(([w, h]) => w >= 44 && h >= 44), '==', true);
    await ph.locator('#hist .hrow .hgo').nth(2).tap(); await sleep(200); const pv = await ph.evaluate(() => window.__ed.previewing); chk('U', 'tapping a history row previews that step (read-only)', pv !== null && pv >= 4, '==', true);
    await ph.evaluate(() => document.getElementById('side').classList.remove('open')); await sleep(500); await ph.locator('#pv-back').tap(); await sleep(200); chk('U', 'Back to now returns to the live picture', (await ph.evaluate(() => window.__ed.previewing)) === null, '==', true);
    await ph.evaluate(() => document.getElementById('side').classList.add('open')); await sleep(500); await ph.locator('#hist .hrow button[title="Re-edit this stroke"]').first().tap(); await sleep(200);
    await ph.evaluate(() => { const r = document.querySelector('#hist .hedit input[type=range]'); r.value = 55; r.dispatchEvent(new Event('input')); }); const n0 = await ph.evaluate(() => window.__ed.ops.length); const ap = ph.locator('#hist .hedit button', { hasText: 'Apply' }); await ap.tap(); await sleep(400);
    chk('U', 'Edit -> size slider -> Apply adds one amend entry', (await ph.evaluate(() => window.__ed.ops.length)) - n0 === 1 && (await ph.evaluate(() => window.__ed.ops.at(-1).op === 'amend' && window.__ed.ops.at(-1).set.r === 55)), '==', true);
    await ph.locator('#h-ver').tap(); await sleep(300); chk('U', 'Verify tap reports a verified log', /^Verified/.test(await ph.evaluate(() => document.getElementById('hmsg').textContent)), '==', true); chk('U', 'no page scroll', await ph.evaluate(() => document.documentElement.scrollHeight <= innerHeight), '==', true); chk('U', 'no page errors (phone)', ph.errs.length, '==', 0); await ctx.close(); }
  await br.close(); srv.close();
  const out = { n_checks: rec.length, gate: fails.length ? 'FAIL' : 'PASS', fails, numbers: num, checks: rec, node: process.version }; fs.writeFileSync(path.join(OUT, 'history.json'), J(out, null, 1)); console.log(J({ ...out, checks: undefined }, null, 1)); process.exit(fails.length ? 1 : 0);
})().catch((e) => { console.error(e); process.exit(2); });
