// ⚠ DO NOT REMOVE — Scope: prove the GENERATED provider of _projectSchedule. When a building
// has NO native IFC tasks table (dropped IFC, e.g. LTU) but TM has run, the support-gate fallback
// schedule lives in kernel_ops (ELEMENT_PLACE, params {phase,storey,_end_ts,...}). The Settings
// 4D-Schedule view must project THAT into the same schedule_instance contract (source:'generated'),
// grouped by storey, Ceiling/TOS collapsed — NOT show an empty "nothing captured" note.
// Run: node tests/test_schedule_generated.js   (exit 0 = pass). Mirrors panels.js _projectGenerated.

const fs = require('fs');
const path = require('path');
const initSqlJs = require('sql.js');

// ── the SAME logic as panels.js _projectGenerated (kernel_ops → contract JSON) ──
function projectGenerated(db) {
  function rows(sql) {
    var r; try { r = db.exec(sql); } catch (e) { return []; }
    if (!r.length) return [];
    var cols = r[0].columns, out = [];
    r[0].values.forEach(function (v) { var o = {}; cols.forEach(function (c, i) { o[c] = v[i]; }); out.push(o); });
    return out;
  }
  function meta(k, d) { var r = rows("SELECT value FROM project_metadata WHERE key='" + k + "'"); return r.length ? r[0].value : d; }
  function collapseLevel(name) { var m = /^(Level\s*\S+?)(?:\s+(?:Ceiling|TOS|Top of Steel))?$/i.exec(name || ''); return m ? m[1] : name; }
  // captured path first (native tasks) — empty here, falls through
  var tasks = rows("SELECT task_id FROM tasks");
  if (tasks.length) return { _wentCaptured: true };

  var ke = rows("SELECT timestamp, parameters FROM kernel_ops WHERE op_type = 'ELEMENT_PLACE' AND undone = 0");
  if (!ke.length) return null;
  function dayMs(ms) { try { return new Date(Number(ms)).toISOString().slice(0, 10); } catch (e) { return ''; } }
  function weeksMs(s, e) { return Math.max(1, Math.round((Number(e) - Number(s)) / (7 * 86400000))); }
  var g = {};
  ke.forEach(function (op) {
    var p; try { p = JSON.parse(op.parameters); } catch (e) { p = {}; }
    var key = collapseLevel(p.storey || p.phase || 'Unspecified');
    var s = Number(op.timestamp), e = Number(p._end_ts != null ? p._end_ts : op.timestamp);
    if (!isFinite(s)) return;
    if (!isFinite(e) || e < s) e = s;
    var b = g[key] || (g[key] = { phase: key, start: s, finish: e, elements: 0, cap: 0 });
    if (s < b.start) b.start = s; if (e > b.finish) b.finish = e; b.elements++;
    if (p._captured) b.cap++;
  });
  var ord = Object.keys(g).map(function (k) { return g[k]; }).sort(function (a, b) { return a.start - b.start; });
  if (!ord.length) return null;
  var gphases = ord.map(function (b, i) {
    var src = b.cap === 0 ? 'generated' : (b.cap === b.elements ? 'captured' : 'mixed');
    return { id: 'p' + i, phase: b.phase, start: dayMs(b.start), weeks: weeksMs(b.start, b.finish), elements: b.elements, source: src };
  });
  var capTot = ord.reduce(function (s, b) { return s + b.cap; }, 0);
  var elTot = ord.reduce(function (s, b) { return s + b.elements; }, 0);
  var projSrc = capTot === 0 ? 'generated' : (capTot === elTot ? 'captured' : 'mixed');
  var out = { Project: { building: meta('building_name', '?'), start: dayMs(ord[0].start), calendar: '', source: projSrc }, Phases: gphases };
  console.log('§SCHEDULE_INSTANCE building=' + out.Project.building + ' provider=' + projSrc + ' phases=' +
    gphases.length + ' captured=' + capTot + ' generated=' + (elTot - capTot) + ' start=' + out.Project.start);
  return out;
}

(async function () {
  var sqljsDir = path.dirname(require.resolve('sql.js'));
  var SQL = await initSqlJs({ locateFile: function (f) { return path.join(sqljsDir, f); } });
  var db = new SQL.Database();
  // LTU-like: NO tasks table; a kernel_ops generated by the support-gate fallback (epoch-ms timestamps)
  db.run("CREATE TABLE project_metadata (key TEXT, value TEXT)");
  db.run("INSERT INTO project_metadata VALUES ('building_name','LTU_AHouse')");
  db.run("CREATE TABLE kernel_ops (id INTEGER PRIMARY KEY, timestamp INTEGER, op_type TEXT, parameters TEXT, input_guids TEXT, output_guid TEXT, undone INTEGER DEFAULT 0)");
  var DAY = 86400000, T0 = Date.parse('2026-06-01T09:00:00Z');
  function place(ms, durDays, storey, captured) {
    var p = { phase: 'Structure', cls: 'IfcWall', name: 'w', storey: storey, resource: null, _end_ts: ms + durDays * DAY };
    if (captured) p._captured = 1;
    db.run("INSERT INTO kernel_ops (timestamp,op_type,parameters,output_guid,undone) VALUES (?,?,?,?,0)",
      [ms, 'ELEMENT_PLACE', JSON.stringify(p), 'g' + Math.round(ms) + storey]);
  }
  // GROUND FLOOR LEVEL: 3 ops over ~2 weeks (earliest)
  place(T0, 5, 'GROUND FLOOR LEVEL'); place(T0 + 2 * DAY, 5, 'GROUND FLOOR LEVEL'); place(T0 + 4 * DAY, 8, 'GROUND FLOOR LEVEL');
  // Level 1 + Level 1 TOS → MUST collapse into one "Level 1" phase
  place(T0 + 14 * DAY, 7, 'Level 1'); place(T0 + 16 * DAY, 7, 'Level 1 TOS'); place(T0 + 18 * DAY, 7, 'Level 1');
  // Aras 01 (non-Level storey, stays as-is), one op captured-overlaid → mixed
  place(T0 + 30 * DAY, 10, 'Aras 01'); place(T0 + 32 * DAY, 10, 'Aras 01', true);
  // an undone op (must be ignored)
  db.run("UPDATE kernel_ops SET undone=1 WHERE id=8 AND 0=1");  // no-op guard; explicit undone row:
  db.run("INSERT INTO kernel_ops (timestamp,op_type,parameters,output_guid,undone) VALUES (?,?,?,?,1)",
    [T0 + 99 * DAY, 'ELEMENT_PLACE', JSON.stringify({ storey: 'GHOST', _end_ts: T0 + 100 * DAY }), 'ghost']);

  var json = projectGenerated(db);
  if (!json || json._wentCaptured) { console.error('FAIL: did not take generated path'); process.exit(1); }

  var fail = 0;
  function ok(c, m) { console.log((c ? 'PASS' : 'FAIL') + ': ' + m); if (!c) fail++; }
  var names = json.Phases.map(function (p) { return p.phase; });
  ok(json.Project.source === 'generated' || json.Project.source === 'mixed', "Project.source is generated/mixed (got " + json.Project.source + ")");
  ok(names.indexOf('GROUND FLOOR LEVEL') === 0, "first phase = earliest storey 'GROUND FLOOR LEVEL' (bottom-up by start)");
  ok(names.indexOf('Level 1') >= 0 && names.indexOf('Level 1 TOS') < 0, "'Level 1 TOS' COLLAPSED into 'Level 1' (no TOS leak)");
  var l1 = json.Phases.find(function (p) { return p.phase === 'Level 1'; });
  ok(l1 && l1.elements === 3, "'Level 1' merged 3 ops (Level 1 + Level 1 TOS) (got " + (l1 && l1.elements) + ")");
  var aras = json.Phases.find(function (p) { return p.phase === 'Aras 01'; });
  ok(aras && aras.source === 'mixed', "'Aras 01' = mixed (1 of 2 captured-overlaid) (got " + (aras && aras.source) + ")");
  ok(!names.some(function (n) { return /GHOST/.test(n); }), "undone op excluded");
  ok(json.Phases.every(function (p) { return ['id', 'phase', 'start', 'weeks', 'elements', 'source'].every(function (k) { return k in p; }); }), "every phase has the contract fields");
  ok(/^2026-06-01/.test(json.Project.start), "Project.start from earliest op epoch (got " + json.Project.start + ")");

  console.log('--- generated instance ---');
  console.log(JSON.stringify(json, null, 1));
  db.close();
  process.exit(fail ? 1 : 0);
})();
