#!/usr/bin/env node
/**
 * W-SDG-JS-PARITY — node witness that the JS on-the-fly SDG derivations (cross_edges.js) reproduce the
 * witnessed Python builders (extractIFCtoDB.derive_datums_and_anchors / derive_spans) EXACTLY, edge-for-edge.
 * User fork 2026-06-26: JS-derive on-the-fly (not the baked tables). NON-INVENT, zero logic drift.
 *
 * ORACLE = the Python functions run at FULL float64 precision over the SAME pristine substrate the modeller
 * renders from (element_transforms center±bbox/2). NOTE: the rel_* tables baked INTO the residents used the
 * SQLite R*Tree, whose coords are 32-bit floats → a handful of datum-cluster boundaries land differently than
 * float64; comparing to those would be apples-to-oranges. So the oracle here is a frozen float64 dump
 * (tests/fixtures/sdg_oracle_float64.json.gz), regenerated by running the SHIPPED Python on a regular (REAL,
 * float64) elements_rtree — see commit body. fills/aggregates are RECOVERED reads, checked vs the live tables.
 */
'use strict';
var path = require('path'), fs = require('fs'), zlib = require('zlib');
var initSqlJs = require('sql.js');
var CE = require(path.join(__dirname, '..', 'viewer', 'cross_edges.js'));

var MOD = path.join(__dirname, '..', 'modeller');
var ORACLE = JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(__dirname, 'fixtures', 'sdg_oracle_float64.json.gz'))));
var RESIDENTS = Object.keys(ORACLE);

function rows(db, sql) { try { var r = db.exec(sql); return r.length ? r[0].values : []; } catch (e) { return []; } }

(async function () {
  var SQL = await initSqlJs();
  var pass = 0, fail = 0;
  function chk(name, cond, extra) { if (cond) { pass++; console.log('  ✅ ' + name + (extra ? '  ' + extra : '')); } else { fail++; console.log('  ❌ ' + name + (extra ? '  ' + extra : '')); } }
  console.log('═══ W-SDG-JS-PARITY — JS derive == Python (float64 oracle), node ═══');

  for (var ri = 0; ri < RESIDENTS.length; ri++) {
    var key = RESIDENTS[ri];
    var p = path.join(MOD, key + '.db');
    if (!fs.existsSync(p)) { console.log('  (skip ' + key + ' — not present)'); continue; }
    console.log('── ' + key + ' ──');
    var O = ORACLE[key];
    var db = new SQL.Database(fs.readFileSync(p));
    var X = CE.deriveAll(db);

    // DATUMS — exact by datum_id → (axis, coord±1e-6, support)
    var oDat = {}; O.datums.forEach(function (d) { oDat[d[0]] = { axis: d[1], coord: d[2], sup: d[3] }; });
    var datBad = 0;
    X.datums.forEach(function (d) { var o = oDat[d.datum_id]; if (!o || o.axis !== d.axis || Math.abs(o.coord - d.coord) > 1e-6 || o.sup !== d.support_count) datBad++; });
    chk(key + ' datums == Python (count + id + axis + coord + support)', X.datums.length === O.datums.length && datBad === 0,
      'js=' + X.datums.length + ' oracle=' + O.datums.length + ' mismatch=' + datBad);

    // ANCHORED — exact EDGE SET (guid|datum_id|axis), offsets to MICRON precision. The only deviations are
    // sub-micron float-accumulation in a few large-cluster datum means (→ ≤1µm offset shift) and the ARBITRARY
    // SIGN of a datum-CENTERED face's offset (±X equally valid at the tie). So: membership exact; |offset|
    // magnitude within 2µm; count of sign-ambiguous ties reported (must be a centered-face tie, |Δ|≈2·|off|).
    var oAnc = {}; O.anchored.forEach(function (a) { oAnc[a[0] + '|' + a[1] + '|' + a[2]] = a[3]; });
    var ancMiss = 0, ancMag = 0, ancSign = 0;
    X.anchored.forEach(function (a) {
      var k = a.element_guid + '|' + a.datum_id + '|' + a.axis;
      if (!(k in oAnc)) { ancMiss++; return; }
      var o = oAnc[k];
      if (Math.abs(o - a.offset_mm) <= 2e-3) return;                         // same value (≤2µm: rounding/accum)
      if (Math.abs(Math.abs(o) - Math.abs(a.offset_mm)) <= 2e-3) { ancSign++; return; }   // datum-centered tie: |off| equal, sign arbitrary
      ancMag++;                                                              // a REAL magnitude drift
    });
    chk(key + ' anchored == Python rel_anchored (set + |offset|≤2µm)',
      X.anchored.length === O.anchored.length && ancMiss === 0 && ancMag === 0,
      'js=' + X.anchored.length + ' oracle=' + O.anchored.length + ' miss=' + ancMiss + ' magΔ=' + ancMag + ' signTies=' + ancSign);

    // SPANS — exact by (guid|axis) → datum ids + span±1e-6
    var oSpan = {}; O.spans.forEach(function (s) { oSpan[s[0] + '|' + s[1]] = { lo: s[2], hi: s[3], s: s[4] }; });
    var spMiss = 0, spId = 0, spLen = 0;
    X.spans.forEach(function (s) { var o = oSpan[s.element_guid + '|' + s.axis]; if (!o) spMiss++; else { if (o.lo !== s.datum_lo_id || o.hi !== s.datum_hi_id) spId++; if (Math.abs(o.s - s.span_m) > 1e-6) spLen++; } });
    chk(key + ' spans == Python rel_spans (count + datum ids + span_m)',
      X.spans.length === O.spans.length && spMiss === 0 && spId === 0 && spLen === 0,
      'js=' + X.spans.length + ' oracle=' + O.spans.length + ' miss=' + spMiss + ' idΔ=' + spId + ' lenΔ=' + spLen);

    // FILLS + AGGREGATES — RECOVERED reads (vs the live recovered tables)
    var bFill = rows(db, "SELECT count(*) FROM rel_fills_host")[0][0];
    var bAgg = rows(db, "SELECT count(*) FROM rel_aggregates")[0][0];
    chk(key + ' fills read == rel_fills_host', X.fills.length === bFill, 'js=' + X.fills.length + ' table=' + bFill);
    chk(key + ' aggregates read == rel_aggregates', X.aggregates.length === bAgg, 'js=' + X.aggregates.length + ' table=' + bAgg);

    // ABUTS — the SHIPPED slice (W-CROSS-EDGES-ABUTS); confirm it still derives + is DETERMINISTIC here.
    var ab2 = CE.deriveAdjacency(db);
    chk(key + ' abuts derives + deterministic (shipped slice)', X.abuts.length > 0 && X.abuts.length === ab2.length, 'edges=' + X.abuts.length);

    db.close();
  }

  console.log('W-SDG-JS-PARITY: ' + pass + ' PASS / ' + fail + ' FAIL');
  process.exit(fail ? 1 : 0);
})();
