#!/usr/bin/env node
// witness_sfr_uniform_not_define.js — W-SFR-UNIFORM
//
// ⚠ DO NOT REMOVE — SCOPE (bim-compiler prompts/PHOTOREAL_STILL_RENDER.md §SFR_UNIFORM_NOT_DEFINE).
// USER, 2026-09-04, after glass panels went missing from a bake that was clean two days earlier:
// "Examine your impact bug and rethink if it is necessary — what does it really do? … Or have a
// proper handling code that nails what u doing and not create the impact." Read the log every run.
//
// THE ISSUE THIS PROVES OR DISPROVES: §SUN_FILL_RATIO expressed "no staged HDRI on matte surfaces"
// by SWAPPING m.envMap. envMap is a shader DEFINE, so every swap sets needsUpdate and recompiles
// that material. Before it there was ONE target and the reassert loop was inert after its first
// pass; after it there are TWO, and A._envMap is regenerated by the 2s-throttled updateSky() — so
// each regen flips every glossy material back and recompiles it, per material, intermittently.
// The policy is unchanged here; the LEVER moves to envMapIntensity, which is a uniform.
//
// Whitebox, no browser, no bake: `_isPhotoGlossyMat` is SLICED OUT of the shipped effects.js by
// brace matching and the shipped assignment block is executed against real THREE-shaped stubs.
'use strict';
const fs = require('fs'), path = require('path'), vm = require('vm');
const { Witness } = require(path.join(__dirname, '..', '..', 'witness_kit', 'contract.js'));
const src = fs.readFileSync(path.join(__dirname, '..', 'effects.js'), 'utf8');

function sliceFn(marker) {
  const i = src.indexOf(marker);
  if (i < 0) return null;
  let d = 0, open = false;
  for (let j = i; j < src.length; j++) {
    if (src[j] === '{') { d++; open = true; }
    else if (src[j] === '}') { d--; if (open && d === 0) return src.slice(i, j + 1); }
  }
  return null;
}
const glossySrc = sliceFn('function _isPhotoGlossyMat(');
// The shipped decisions, read rather than restated.
const mapIsSingleTarget = /\? _roomProbeRT\.texture : A\._envMap;/.test(src);
const usesIntensityLever = /if \(m\.envMapIntensity !== _wantI\) m\.envMapIntensity = _wantI;/.test(src);
const noSavedInAssign = !/_isPhotoGlossyMat\(m\) \? A\._envMap : \(_photoEnvMapSaved \|\| A\._envMap\)/.test(src);
const teardownRestores = /mm\.envMapIntensity = mm\.userData\._sfrBaseEnvI;/.test(src);
const matteI = Number((src.match(/var SFR_MATTE_ENV_I = ([0-9.]+)/) || [])[1]);

function mats() {
  return [
    { name: 'glass-glossy', roughness: 0.05, metalness: 0, envMapIntensity: 1, userData: {} },
    { name: 'metal', roughness: 0.4, metalness: 0.9, envMapIntensity: 1, userData: {} },
    { name: 'concrete-matte', roughness: 0.9, metalness: 0, envMapIntensity: 1, userData: {} },
    { name: 'plaster-matte', roughness: 0.95, metalness: 0, envMapIntensity: 0.8, userData: {} }
  ].map(m => Object.assign(m, { envMap: null, needsUpdate: false, uuid: m.name }));
}

// The two mechanisms, both driven by REGENERATED sky targets (what updateSky does every 2 s).
function run(mode) {
  const sb = {
    Math, console: { log() {} },
    PHOTO_METAL_THRESHOLD: 0.5, PHOTO_GLOSSY_ROUGHNESS_MAX: 0.35
  };
  vm.createContext(sb);
  vm.runInContext(glossySrc, sb);
  const M = mats();
  const SFR = matteI;
  let recompiles = 0;
  let envA = { id: 'sky-0' }, saved = { id: 'pre-staging-sky' };
  for (let tick = 0; tick < 6; tick++) {
    if (tick % 2 === 1) envA = { id: 'sky-' + tick };      // updateSky regen, 2 s throttle
    M.forEach(m => {
      const target = (mode === 'red')
        ? (sb._isPhotoGlossyMat(m) ? envA : (saved || envA))   // PRE-FIX: two targets
        : envA;                                                 // SHIPPED: one target
      if (m.envMap !== target) { m.envMap = target; m.needsUpdate = true; recompiles++; }
      if (mode !== 'red') {
        if (m.userData._sfrBaseEnvI == null) m.userData._sfrBaseEnvI = m.envMapIntensity;
        const want = sb._isPhotoGlossyMat(m) ? m.userData._sfrBaseEnvI : SFR;
        if (m.envMapIntensity !== want) m.envMapIntensity = want;
      }
    });
  }
  const latest = envA.id;
  const restored = M.map(m => ({
    name: m.name, glossy: sb._isPhotoGlossyMat(m), envI: m.envMapIntensity,
    base: m.userData._sfrBaseEnvI, stale: m.envMap.id !== latest ? 1 : 0
  }));
  return { recompiles, mats: restored, staleRefs: restored.reduce((a, b) => a + b.stale, 0) };
}

function population() {
  if (!glossySrc || !Number.isFinite(matteI)) return [];
  const g = run('green'), r = run('red');
  return g.mats.map((m, i) => ({
    material: m.name,
    glossy: m.glossy,
    envIntensity: m.envI,
    baseValue: m.base != null ? m.base : -1,
    baseCaptured: m.base != null,
    staleRefs: g.staleRefs,
    redStaleRefs: r.staleRefs,
    greenRecompiles: g.recompiles,
    redRecompiles: r.recompiles,
    mapIsSingleTarget, usesIntensityLever, noSavedInAssign, teardownRestores
  }));
}
const schema = {
  type: 'object',
  required: ['material', 'glossy', 'envIntensity', 'baseValue', 'baseCaptured', 'staleRefs',
             'redStaleRefs', 'greenRecompiles', 'redRecompiles',
             'mapIsSingleTarget', 'usesIntensityLever', 'noSavedInAssign', 'teardownRestores'],
  properties: {
    material: { type: 'string' }, glossy: { type: 'boolean' }, envIntensity: { type: 'number' },
    baseValue: { type: 'number' }, baseCaptured: { type: 'boolean' },
    staleRefs: { type: 'integer' }, redStaleRefs: { type: 'integer' },
    greenRecompiles: { type: 'integer' }, redRecompiles: { type: 'integer' },
    mapIsSingleTarget: { type: 'boolean' }, usesIntensityLever: { type: 'boolean' },
    noSavedInAssign: { type: 'boolean' }, teardownRestores: { type: 'boolean' }
  }
};

if (!glossySrc || !Number.isFinite(matteI)) {
  console.log('§WITNESS_SFR_UNIFORM_VERDICT INCONCLUSIVE — could not slice _isPhotoGlossyMat or read ' +
    'SFR_MATTE_ENV_I from effects.js; nothing judged');
  process.exit(1);
}

const w = Witness('SFR_UNIFORM_NOT_DEFINE')
  .population(population)
  .schema(schema)
  // G1 — THE DEFECT: no material may end staging holding a texture that is not the CURRENT sky.
  // The pre-fix version pins every matte material to `_photoEnvMapSaved`, a target a later
  // updateSky() regen disposes — a live reference to freed GPU memory, per material.
  .invariant('no-stale-env-reference', rows => rows.every(r => r.staleRefs === 0))
  // G2 — and the stale reference was REAL on the same input, so G1 is not passing vacuously.
  .invariant('stale-ref-was-real', rows => rows.every(r => r.redStaleRefs > 0))
  // G3 — the policy is unchanged: matte gets no staged fill, glossy keeps its own base intensity.
  .invariant('policy-preserved', rows =>
    rows.filter(r => !r.glossy).every(r => r.envIntensity === 0) &&
    rows.filter(r => r.glossy).every(r => r.envIntensity === r.baseValue))
  // G4 — every touched material captured its OWN pre-staging value, so teardown cannot guess.
  .invariant('base-captured-per-material', rows => rows.every(r => r.baseCaptured))
  // G5 — the shipped source really uses the uniform lever, one map target, and restores on teardown.
  .invariant('mechanism-is-the-uniform', rows => rows.every(r =>
    r.mapIsSingleTarget && r.usesIntensityLever && r.noSavedInAssign && r.teardownRestores))
  .redControl(rows => rows.map(r => Object.assign({}, r,
    { staleRefs: r.redStaleRefs, mapIsSingleTarget: false, usesIntensityLever: false })));

const res = w.run();
const rows = population();
rows.forEach(r => console.log('§SFR_UNIFORM_ROW mat=' + r.material + ' glossy=' + r.glossy +
  ' envMapIntensity=' + r.envIntensity + ' baseCaptured=' + r.baseCaptured));
console.log('§SFR_UNIFORM_STALE shipped=' + rows[0].staleRefs + ' materials left on a non-current sky' +
  ' vs pre-fix=' + rows[0].redStaleRefs + ' (updateSky disposes the one they were pinned to)');
console.log('§SFR_UNIFORM_RECOMPILE shipped=' + rows[0].greenRecompiles + ' vs pre-fix=' +
  rows[0].redRecompiles + ' over 3 sky regens — REPORTED, NOT ASSERTED: the swap costs FEWER' +
  ' recompiles, so recompile count is not the defect and this witness does not pretend it is');
console.log('§SFR_UNIFORM_WIRING singleTarget=' + mapIsSingleTarget + ' intensityLever=' + usesIntensityLever +
  ' savedRefGone=' + noSavedInAssign + ' teardownRestores=' + teardownRestores + ' matteI=' + matteI);
const vacuous = rows.length === 0;
console.log('§WITNESS_SFR_UNIFORM_VERDICT ' + (vacuous ? 'VACUOUS — nothing judged'
  : res.fail === 0 ? 'PASS' : 'FAIL') + ' rows=' + rows.length + ' pass=' + res.pass + ' fail=' + res.fail);
process.exit(res.fail === 0 && !vacuous ? 0 : 1);
