-- §S11_META_TRANSFORM_REPAIR (2026-08-17, bim-compiler prompts/4D_GANTT_TM_REFACTOR.md §S11)
-- LTU_AHouse_meta.db was produced with a per-element-corrupted rebase — the same defect class
-- as Terminal_meta.db (§S10), 16x the rows. Against LTU_AHouse_extracted.db + the modal rigid
-- offset (-388.685560, -87.610001, -0.000000), 33528 of 125698 rows deviate >0.05m,
-- and 3105 sit at center_z EXACTLY 0 (0 do in extracted): half the top structural floor
-- (VÅN 4, median z 0.00 here vs 13.73 in truth) lay on the ground plane, with 1,785 IfcMember /
-- 558 IfcColumn / 439 IfcSlab / 49 IfcFooting among them. Geometry itself is identical on both
-- sides (bbox sizes match on all 125698 rows, max diff 0.000; rotations 0 rows differ) — only
-- the centres moved.
--
-- The repaired values come from meta.db's OWN elements_rtree, which was built before the
-- corruption: its box centres agree with extracted+offset on 125698/125698 rows, with
-- element_transforms on far fewer. 33524 rows disagree with their r-tree box by >0.05m
-- (max 291.50m) and are the ones this patch snaps back. Rows already within EPS keep
-- their exact values. Idempotent: after one apply the selection is empty, so a re-apply is a
-- no-op. geo.db needs no patch — its base_geometries vertices are local-centred (measured
-- 400/400), so a repaired transform carries mesh and bbox together.
-- Generated by scripts/gen_ltu_meta_patch.js; verified by scripts/verify_ltu_meta_transform_repair.js.
CREATE TEMP TABLE _s11_fix (guid TEXT PRIMARY KEY, cx REAL, cy REAL, cz REAL);
INSERT INTO _s11_fix SELECT m.guid,
  (r.minX+r.maxX)/2.0, (r.minY+r.maxY)/2.0, (r.minZ+r.maxZ)/2.0
  FROM elements_meta m JOIN elements_rtree r ON r.id = m.id
  JOIN element_transforms t ON t.guid = m.guid
  WHERE abs((r.minX+r.maxX)/2.0 - t.center_x) > 0.05
     OR abs((r.minY+r.maxY)/2.0 - t.center_y) > 0.05
     OR abs((r.minZ+r.maxZ)/2.0 - t.center_z) > 0.05;
UPDATE element_transforms SET
  center_x = (SELECT cx FROM _s11_fix f WHERE f.guid = element_transforms.guid),
  center_y = (SELECT cy FROM _s11_fix f WHERE f.guid = element_transforms.guid),
  center_z = (SELECT cz FROM _s11_fix f WHERE f.guid = element_transforms.guid)
 WHERE guid IN (SELECT guid FROM _s11_fix);
DROP TABLE _s11_fix;
