-- >>> BEGIN §META_TRANSFORM_REPAIR (scripts/gen_meta_transform_patch.js — regenerated block, do not hand-edit)
-- §META_TRANSFORM_REPAIR LTU_AHouse (2026-08-16, bim-compiler prompts/4D_GANTT_TM_REFACTOR.md §S10/§S11/§S12)
-- LTU_AHouse_meta.db — the pair the live viewer loads through streaming.js §DB_SPLIT_DETECT — carries a
-- per-element-corrupted rebase against LTU_AHouse_extracted.db (the extraction truth): 33528 of 125698
-- rows deviate >0.05m from the modal rigid offset (-388.685560, -87.610001, -0.000000), max 291.50m, and 3105 more rows sit at center_z exactly 0 here than in truth.
-- Corrupted centres flip bearing/containment relations, so the live scheduler classifies a
-- different building from the one every fleet probe measures. geo.db needs no patch: its mesh
-- vertices are local-centred, so a repaired transform carries mesh and bbox with it.
-- Repair threshold is HALF ScheduleGate.EPS (0.025m) so nothing is left within half a tolerance
-- of flipping a predicate. Absolute SET values => idempotent. Generated by
-- scripts/gen_meta_transform_patch.js; detected by scripts/audit_split_pairs.js.
-- FORM: r-tree. LTU_AHouse_meta.db's own elements_rtree agrees with extracted+offset on 125698/125698 rows,
-- i.e. it predates the corruption and already holds the correct centres. 40805 rows disagree with
-- their own box by >0.025m and are snapped back — as 4 set-based statements, so the patch stays
-- ~2KB no matter how many rows it repairs (it is re-applied on EVERY load of this DB).
-- The staging table keeps an explicit PRIMARY KEY: without it the correlated lookups degrade to
-- n^2 scans and the patch does not finish (measured).
CREATE TEMP TABLE _fix_meta_transform (guid TEXT PRIMARY KEY, cx REAL, cy REAL, cz REAL);
INSERT INTO _fix_meta_transform SELECT m.guid,
  (r.minX+r.maxX)/2.0, (r.minY+r.maxY)/2.0, (r.minZ+r.maxZ)/2.0
  FROM elements_meta m JOIN elements_rtree r ON r.id = m.id
  JOIN element_transforms t ON t.guid = m.guid
  WHERE abs((r.minX+r.maxX)/2.0 - t.center_x) > 0.025
     OR abs((r.minY+r.maxY)/2.0 - t.center_y) > 0.025
     OR abs((r.minZ+r.maxZ)/2.0 - t.center_z) > 0.025;
UPDATE element_transforms SET
  center_x = (SELECT cx FROM _fix_meta_transform f WHERE f.guid = element_transforms.guid),
  center_y = (SELECT cy FROM _fix_meta_transform f WHERE f.guid = element_transforms.guid),
  center_z = (SELECT cz FROM _fix_meta_transform f WHERE f.guid = element_transforms.guid)
 WHERE guid IN (SELECT guid FROM _fix_meta_transform);
DROP TABLE _fix_meta_transform;
-- <<< END §META_TRANSFORM_REPAIR
