// trl_batch_2026-10-03.js — the 2026-10-03 machine batch for the Viewer's AD_Message dictionary.
// Spec: bim-compiler prompts/S226_localisation.md §R2 SPEC (R2.1 + R2.3). Consumed ONCE by
// trl_migrate_2026-10-03.js, which writes it into viewer/i18n/ad_message_base.csv (NEW rows) and
// viewer/i18n/AD_Message_Trl_<lang>.xml (TRL rows, trl="Y"). After that run the XML is the source and
// this file is its birth record — edit the XML, not this file.
//
// PROVENANCE: every translation below is a MACHINE translation written for this app by Claude (Anthropic)
// on 2026-10-03 — NOT from a published iDempiere language pack (the Viewer's strings do not exist in any
// pack). Labelled `source=machine` in each XML header, as the ERP lane labels its own supplement
// (prompts/ERP_UI_LOCALES.md §L2b). Untranslated = not listed here = stays trl="N" (English, counted).
//
// NEW: value -> { en, type }   — English shown today, byte-identical to the page (S226: English never changes).
// TRL: locale -> { value: text } — new keys AND gap fills for old keys whose .js text was still English.
'use strict';

const NEW = {
  // ── landing index.html ──
  landing_tip_red:        { en: 'Red — you go in (sound on, then we load)' },
  landing_tip_blue:       { en: 'Blue — nothing happens, nothing loads' },
  landing_blue_quote:     { en: '"You take the blue pill — the story ends, you wake up in your bed and believe whatever you want to believe."' },
  landing_back:           { en: '← back' },
  landing_choose_door:    { en: 'choose your door' },
  landing_stats_title:    { en: 'Site traffic stats (GoatCounter)' },
  landing_hub_title:      { en: 'BUILDINGS & IFC' },
  landing_hub_sub:        { en: 'drop your own IFC, or open a ready building — opens in the viewer' },
  landing_launcher_gps:   { en: 'Buildings / IFC' },
  landing_launcher_bonsai:{ en: 'BIM Modeller' },
  landing_launcher_erp:   { en: 'ERP' },
  landing_launcher_doc:   { en: 'User Guide' },
  landing_launcher_watch: { en: 'Watch demo' },
  landing_launcher_clear: { en: 'Clear cache' },
  landing_more:           { en: 'More' },
  landing_mobile_note:    { en: 'BIM authoring (DAGeVu) is a desktop experience — open it on a larger screen.' },
  landing_drop_hint:      { en: '↓ Drop IFC / 3D files here — or tap to browse' },
  landing_drop_sub:       { en: 'multiple discipline files merge into one building' },
  landing_blank_viewer:   { en: 'Blank Viewer' },
  landing_open_own_db:    { en: 'Open your own .db file' },
  landing_loading_manifest:{ en: 'loading building manifest…' },
  landing_city_buildings: { en: 'City buildings' },
  landing_landmark_buildings:{ en: 'Landmark buildings' },
  landing_elements:       { en: 'elements' },
  landing_reload:         { en: 'reload' },
  landing_no_db_for:      { en: 'No DB for {name}', type: 'E' },
  landing_clear_confirm:  { en: 'Reset to the start screen?\n\nClears the in-browser building data:\n  • cached buildings\n  • any IFC scene you dropped in (not saved to a .db file)\nand returns you to the red / blue choice.\n\nKeeps: the installed app + offline data, and any .db you saved yourself.' },
  // ── viewer.html statics ──
  ui_grid_bays:           { en: 'Grid Bays' },
  ui_share:               { en: 'Share' },
  ui_tt_minmax:           { en: 'Min/Max' },
  ui_tt_menu:             { en: 'Menu' },
  ui_tt_prev_phase:       { en: 'Previous phase' },
  ui_tt_next_phase:       { en: 'Next phase' },
  ui_tt_bookmark_add:     { en: 'Bookmark this cut position' },
  ui_tt_bookmark_del:     { en: 'Remove bookmark' },
  ui_update_ready:        { en: 'Update ready — tap to refresh' },
  ui_report_bug:          { en: 'Report Bug' },
  // ── the ⋯ pill (panels.js _actions; key = 'pill_' + id.toLowerCase().replace('-', '_')) ──
  pill_save:              { en: 'Save Building' },
  pill_open:              { en: 'Open Building' },
  pill_find:              { en: 'Find / Navigate' },
  pill_rolefilter:        { en: 'Role View' },
  pill_help:              { en: 'Help' },
  pill_worldhist:         { en: 'World History' },
  pill_dochist:           { en: 'Page History' },
  pill_walk:              { en: 'Walk' },
  pill_whwalk:            { en: 'Pick Walk' },
  pill_share:             { en: 'Share' },
  pill_hbafm:             { en: 'Human-Asset' },
  pill_measure:           { en: 'Measure' },
  pill_clash:             { en: 'Clash Matrix' },
  pill_sanity:            { en: 'Sanity' },
  pill_egress:            { en: 'Egress' },
  pill_xray:              { en: 'X-Ray / Bbox' },
  pill_bbox:              { en: 'Bounding Boxes' },
  pill_tm:                { en: 'Time Machine' },
  pill_sched4d:           { en: '4D Window' },
  pill_sched4d_gen:       { en: '4D Window — tap to generate a programme' },
  pill_section:           { en: 'Section Cut' },
  pill_background:        { en: 'Background' },
  pill_night:             { en: 'Night' },
  pill_palette:           { en: 'Palette' },
  pill_shadow:            { en: 'Shadow + Ground' },
  pill_fly:               { en: 'Fly Tour' },
  pill_dlodnav:           { en: 'Nav LOD (large bldgs)' },
  pill_report:            { en: '4D / 5D' },
  pill_issues:            { en: 'Issues' },
  pill_fullscreen:        { en: 'Fullscreen' },
  pill_precision:         { en: 'Precision (Fine)' },
  pill_cam_reset:         { en: 'Reset Camera' },
  pill_cam_pivot:         { en: 'Auto-Pivot' },
  pill_home:              { en: 'Home' },
  pill_audio:             { en: 'Sound FX' },
  pill_settings:          { en: 'Settings' },
  pill_navigate:          { en: 'Navigate' },
  pill_inspect:           { en: 'Inspect' },
  pill_camview:           { en: 'Camera / View' },
  // ── role presets, settings, ground, night ──
  role_plumber:           { en: 'Plumber' },
  role_electrician:       { en: 'Electrician' },
  role_acmv:              { en: 'ACMV Tech' },
  role_structural:        { en: 'Structural' },
  role_cleaner:           { en: 'Cleaner' },
  ui_rate_pack_5d:        { en: '5D Rate Pack' },
  ui_cache_info:          { en: 'Cache Info' },
  ui_reset_pill_icons:    { en: 'Reset Pill Icons' },
  ui_defaults_restored:   { en: 'Defaults restored' },
  ui_tt_shadow_ground_cycle:{ en: 'Shadow + Ground — cycle Off → Earth → Grass → Paved' },
  ui_ground_none:         { en: 'None' },
  ui_ground_grass:        { en: 'Grass' },
  ui_ground_earth:        { en: 'Earth' },
  ui_ground_paved:        { en: 'Paved' },
  ui_blank_scene_hint:    { en: 'Blank scene — press Ctrl+O (Open Building) to load a .db file' },
  ui_locale_toast_hint:   { en: 'change in ⚙' },
  // ── World History panel (common/whole_history.js — shared with the ERP, which shows the English default) ──
  ui_hist_title:          { en: 'History — across pages' },
  ui_hist_whole:          { en: 'Whole' },
  ui_hist_this_page:      { en: 'This page' },
  ui_close:               { en: 'Close' },
  // ── camera / cinema chips ──
  ui_tt_precision_fine:   { en: 'Fine precision' },
  ui_tt_reset_camera:     { en: 'Reset camera' },
  ui_tt_auto_pivot:       { en: 'Auto-pivot on scene centre' },
  ui_tt_still_refine:     { en: 'Still Refine (Alt+S)' },
  ui_tt_populate:         { en: 'Populate (Alt+P)' },
  ui_tt_maxq:             { en: 'MaxQ Movie (Alt+C — press again to cancel)' },
  // ── panels.js ICONS registry `trl` keys that never had a dictionary row (A.icon: _TRL[trl] || desc) ──
  ui_tt_tm:               { en: 'Time Machine' },
  ui_tt_find:             { en: 'Find' },
  ui_tt_share:            { en: 'Share' },
  ui_tt_help:             { en: 'Help' },
  ui_tt_clash:            { en: 'Clash Matrix' },
  ui_tt_sunglass:         { en: 'Color Studio' },
  ui_tt_night:            { en: 'Night' },
  ui_tt_shadow:           { en: 'Shadow' },
  ui_tt_bg:               { en: 'Background' },
  ui_tt_bbox:             { en: 'Bounding Boxes' },
  ui_tt_cinema:           { en: 'Cinema Orbit' },
  ui_tt_doc:              { en: 'Document' },
  ui_tt_grid:             { en: 'Grid' },
  ui_tt_table:            { en: 'Table' },
  ui_tt_next:             { en: 'Next Phase' },
  ui_tt_save:             { en: 'Save Design' },
  ui_tt_open:             { en: 'Open Design' },
  ui_tt_mep:              { en: 'MEP Routes' },
  ui_tt_ubbl:             { en: 'UBBL Compliance' },
  ui_tt_rosetta:          { en: 'Rosetta Stone' },
  ui_tt_disc:             { en: 'Disciplines' },
  ui_sun:                 { en: 'Sun intensity' },
  ui_exposure:            { en: 'Exposure' },
  ui_ambient:             { en: 'Ambient' },
  ui_hemisphere:          { en: 'Hemisphere' },
  ui_all:                 { en: 'All' },
  ui_off:                 { en: 'Off' },
  ui_night_on:            { en: 'On — {n} fixtures' },
  // ── Find panel ──
  ui_find_tab_find:       { en: 'Find' },
  ui_find_tab_ask:        { en: 'Ask' },
  ui_save_xlsx:           { en: 'Save .xlsx' },
  ui_all_types:           { en: 'All Types' },
  ui_view_back:           { en: 'View back' },
  ui_view_forward:        { en: 'View forward' },
  ui_expand:              { en: 'Expand' },
  ui_voice_unsupported:   { en: 'Voice not supported', type: 'E' },
  // ── main.js status line ──
  ui_loading_find:        { en: 'Loading Find…' },
  ui_find_load_failed:    { en: 'Find failed to load', type: 'E' },
  ui_gpu_compiling:       { en: 'Compiling GPU shaders — please wait...' },
  ui_gpu_compiled:        { en: 'GPU shaders compiled in {ms}ms — rendering' },
  ui_offline_badge:       { en: 'OFFLINE' },
  // ── page titles (brand prefix kept; only the page's own words translate) ──
  title_boq:              { en: 'BIM OOTB — 4D/5D Analytics' },
  title_clash:            { en: 'BIM OOTB — Clash Coordination Report' },
  title_mep:              { en: 'BIM OOTB — MEP Bill of Quantities' },
  // ── boq_charts.html ──
  t_analytics_4d5d:       { en: '4D/5D Analytics' },
  ui_tt_export_5d:        { en: '5D — Cost Excel' },
  ui_tt_export_4d:        { en: '4D — Schedule Excel' },
  ui_tt_mep_boq:          { en: 'MEP Bill of Quantities' },
  ui_tt_copy_link:        { en: 'Copy shareable link' },
  ui_tt_change_locale_cur:{ en: 'Change locale / currency' },
  ui_tt_change_locale:    { en: 'Change locale' },
  ui_loading_ellipsis:    { en: 'Loading...' },
  ui_requesting_viewer:   { en: 'Requesting data from viewer...' },
  ui_waiting_db_cache:    { en: 'Waiting for DB to cache in main scene...' },
  ui_loading_url:         { en: 'Loading {url}...' },
  t_site_resources:       { en: 'Site Resources' },
  t_boq_5d:               { en: '5D — Bill of Quantities' },
  // ── clash_report.html ──
  clash_report_title:     { en: 'Clash Coordination Report' },
  ui_tt_home:             { en: 'Home' },
  ui_report_downloaded:   { en: 'Report Downloaded' },
  ui_report_downloaded_body:{ en: 'HTML file saved. Share via WhatsApp, Email, or any medium.<br>Recipient opens it in any browser — full charts, no setup needed.' },
  ui_ok:                  { en: 'OK' },
  clash_total:            { en: 'Total Clashes' },
  clash_reviewed:         { en: 'Reviewed' },
  clash_resolved:         { en: 'Resolved' },
  clash_accepted:         { en: 'Accepted' },
  clash_tt_total:         { en: 'Total bbox overlaps detected across all discipline pairs' },
  clash_tt_reviewed:      { en: 'Acknowledged clashes under investigation' },
  clash_tt_resolved:      { en: 'Clashes fixed in the model — ready for re-check' },
  clash_tt_accepted:      { en: 'Risk accepted — no design change needed' },
  clash_by_pair:          { en: 'By Discipline Pair' },
  clash_risk_profile:     { en: 'Discipline Risk Profile' },
  clash_by_severity:      { en: 'By Severity' },
  clash_by_status:        { en: 'By Status' },
  clash_top_offenders:    { en: 'Top Offenders — Fix These First' },
  clash_by_class:         { en: 'By Element Class' },
  clash_matrix_summary:   { en: 'Discipline Matrix Summary' },
  clash_source:           { en: 'Source' },
  clash_target:           { en: 'Target' },
  clash_tolerance:        { en: 'Tolerance' },
  clash_clashes:          { en: 'Clashes' },
  clash_clashes_lbl:      { en: 'clashes' }
};

// One file per locale (trl_batch_2026-10-03_<lang>.js exports { <lang>: { value: text } }) so each language is reviewable alone.
const fs = require('fs'), path = require('path');
const TRL = {};
fs.readdirSync(__dirname).filter(f => /^trl_batch_2026-10-03_[a-z]{2}_[A-Z]{2}\.js$/.test(f)).sort().forEach(f => Object.assign(TRL, require(path.join(__dirname, f))));

module.exports = { NEW, TRL };
