-- Duplex_ARC.db rel_fills_host — the authored host<->opening<->filling chain (§PATHB).
-- Self-heal patch. Generated by scripts/gen_rel_fills_host_patch.py (bim-compiler) — regenerate,
-- do not hand-edit. Recovery is extractIFCtoDB.py extract_rel_fills_host(), the ONE implementation.
--
-- Source: Ifc2x3_Duplex_Architecture.ifc   Generated: 2026-07-28
-- Recovered VERBATIM from the source IFC's own IfcRelVoidsElement/IfcRelFillsElement:
--   50 host edges, 38 with a door/window filling, 12 open voids.
-- provenance='ifc:recovered' on every row. Nothing derived, nothing proximity-guessed.
--
-- WHY: sdg_cascade.js stretchRide() is guarded on window.swXEdges.fills (bonsai_gridmove.js:249)
-- which reads this table (cross_edges.js:251). Without it a hosted door/window does NOT ride its
-- wall on a Grid-Stretch — the cascade silently no-ops. docs/ModellerGuide.md documents the ride.
--
-- MEASURED REACH on this exact target: 36/38 fills have BOTH ends present as scene
-- features (a host with no element_instances row never becomes a feature, so that edge is skipped).
--
-- Idempotent: CREATE IF NOT EXISTS + INSERT OR IGNORE on the opening_guid PRIMARY KEY, so the
-- loader re-applying it on every open is a no-op.
CREATE TABLE IF NOT EXISTS rel_fills_host (
    opening_guid TEXT PRIMARY KEY,
    host_guid TEXT,
    filling_guid TEXT,
    host_class TEXT,
    filling_class TEXT,
    provenance TEXT DEFAULT 'ifc:recovered'
);
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('0c3kWfbRLERxKStRVifSpJ','3ThA22djr8AQQ9eQMA5s7I',NULL,'IfcSlab',NULL,'ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('0st2Ty2kP2i9GWVYN22HBn','0wkEuT1wr1kOyafLY4vy_8',NULL,'IfcFurnishingElement',NULL,'ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1JMZUwOon6WAV1rBBORAVn','0wkEuT1wr1kOyafLY4vyu$',NULL,'IfcFurnishingElement',NULL,'ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1_czKmicP9SRkaew1L5q7Z','2OBrcmyk58NupXoVOHUv88',NULL,'IfcFurnishingElement',NULL,'ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1dqkh_grrAr8eEicMrPggp','0wkEuT1wr1kOyafLY4vy4F',NULL,'IfcFurnishingElement',NULL,'ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1ur9wqEhD1fgF0XSBVdztK','0wkEuT1wr1kOyafLY4vy3H',NULL,'IfcFurnishingElement',NULL,'ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvN$je','2O2Fr$t4X7Zf8NOew3FNtn','1s1jVhK8z0pgKYcr9jt781','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvN$lY','2O2Fr$t4X7Zf8NOew3FNr2','1s1jVhK8z0pgKYcr9jt7AB','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNd$j','1aj$VJZFn2TxepZUBcKpvt','1aj$VJZFn2TxepZUBcKp$i','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNdad','1aj$VJZFn2TxepZUBcKpZw','1aj$VJZFn2TxepZUBcKpac','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNmlJ','2O2Fr$t4X7Zf8NOew3FLJd','2OBrcmyk58NupXoVOHUuXp','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNnH$','2O2Fr$t4X7Zf8NOew3FL96','2OBrcmyk58NupXoVOHUvVV','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNnLa','2O2Fr$t4X7Zf8NOew3FLIE','2OBrcmyk58NupXoVOHUvR4','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNnNr','2O2Fr$t4X7Zf8NOew3FL9r','2OBrcmyk58NupXoVOHUvPL','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNo$h','2O2Fr$t4X7Zf8NOew3FL8v','1hOSvn6df7F8_7GcBWlSDm','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNo1Q','2O2Fr$t4X7Zf8NOew3FLQD','1hOSvn6df7F8_7GcBWlSp1','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNo3N','2O2Fr$t4X7Zf8NOew3FLQD','1hOSvn6df7F8_7GcBWlSnC','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNoCx','2O2Fr$t4X7Zf8NOew3FLOH','1hOSvn6df7F8_7GcBWlS_W','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNoJ3','2O2Fr$t4X7Zf8NOew3FLQD','1hOSvn6df7F8_7GcBWlSXO','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNoO$','2O2Fr$t4X7Zf8NOew3FLQD','1hOSvn6df7F8_7GcBWlSga','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNom4','2O2Fr$t4X7Zf8NOew3FLOH','1hOSvn6df7F8_7GcBWlS2V','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNopD','2O2Fr$t4X7Zf8NOew3FLOH','1hOSvn6df7F8_7GcBWlS1M','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNos1','2O2Fr$t4X7Zf8NOew3FLOH','1hOSvn6df7F8_7GcBWlS4Q','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNowu','2O2Fr$t4X7Zf8NOew3FKST','1hOSvn6df7F8_7GcBWlS8Z','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNoxK','2O2Fr$t4X7Zf8NOew3FNau','1hOSvn6df7F8_7GcBWlS9F','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNozF','2O2Fr$t4X7Zf8NOew3FLTF','1hOSvn6df7F8_7GcBWlSFK','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNrY1','2O2Fr$t4X7Zf8NOew3FNqI','1hOSvn6df7F8_7GcBWlRGQ','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNrZJ','2O2Fr$t4X7Zf8NOew3FNhv','1hOSvn6df7F8_7GcBWlRH8','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNrdW','2O2Fr$t4X7Zf8NOew3FNqI','1hOSvn6df7F8_7GcBWlRLx','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNrfE','2O2Fr$t4X7Zf8NOew3FNhv','1hOSvn6df7F8_7GcBWlRRL','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNrrP','2O2Fr$t4X7Zf8NOew3FNtn','1hOSvn6df7F8_7GcBWlR72','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNrv5','2O2Fr$t4X7Zf8NOew3FNr2','1hOSvn6df7F8_7GcBWlRBU','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNw00','2O2Fr$t4X7Zf8NOew3FLR9','1l0GAJtRTFv8$zmKJOH4kJ','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNw49','2O2Fr$t4X7Zf8NOew3FLR9','1l0GAJtRTFv8$zmKJOH4gQ','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNw5g','2O2Fr$t4X7Zf8NOew3FLR9','1l0GAJtRTFv8$zmKJOH4hv','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNwAF','2O2Fr$t4X7Zf8NOew3FLR9','1l0GAJtRTFv8$zmKJOH4aS','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNwDm','2O2Fr$t4X7Zf8NOew3FLPP','1l0GAJtRTFv8$zmKJOH4ZZ','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNwHx','2O2Fr$t4X7Zf8NOew3FLPP','1l0GAJtRTFv8$zmKJOH4$e','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNwMI','2O2Fr$t4X7Zf8NOew3FLPP','1l0GAJtRTFv8$zmKJOH4u1','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNwQb','2O2Fr$t4X7Zf8NOew3FLPP','1l0GAJtRTFv8$zmKJOH4qs','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNwSd','2O2Fr$t4X7Zf8NOew3FLPP','1l0GAJtRTFv8$zmKJOH4oq','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNwTD','2O2Fr$t4X7Zf8NOew3FLR9','1l0GAJtRTFv8$zmKJOH4pU','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNx5J','0jf0rYHfX3RAB3bSIRjmxl','1Eo2$BaHX42AEkDvQQDoy2','IfcRoof','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1xS3BCk291UvhgP2dvNxVS','0jf0rYHfX3RAB3bSIRjmxl','1Eo2$BaHX42AEkDvQQDocD','IfcRoof','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('24EFH82h1DgeJVWlc35MMP','0wkEuT1wr1kOyafLY4vy6l',NULL,'IfcFurnishingElement',NULL,'ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('2YwZmYlr9AiPDZRZmucxc5','0wkEuT1wr1kOyafLY4vy6k',NULL,'IfcFurnishingElement',NULL,'ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('2fQjX2SrTFrxFKC2cOmyZz','0wkEuT1wr1kOyafLY4vy3G',NULL,'IfcFurnishingElement',NULL,'ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3obae0iBn5i9Cv4Ub3eEXf','2OBrcmyk58NupXoVOHUvq$',NULL,'IfcFurnishingElement',NULL,'ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3v9a8BKHj2mvcndWrD6JMo','3ThA22djr8AQQ9eQMA5s7I',NULL,'IfcSlab',NULL,'ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3yrt06HiHCHQOnRKTWhuME','0wkEuT1wr1kOyafLY4vy4m',NULL,'IfcFurnishingElement',NULL,'ifc:recovered');
