-- SampleCastle rel_fills_host — the authored host<->opening<->filling chain (§PATHB).
-- Self-heal patch, §LODHELL-FIX-3 (prompts/RESUME_MODELLER_LOD400_REAL_GEOMETRY.md §LODHELL-FIX).
--
-- WHY: SampleCastle_ARC.db predates extractIFCtoDB.py's extract_rel_fills_host() (:757), so it
-- shipped with no rel_fills_host table at all. That is the ONLY reason sdg_cascade.js
-- stretchRide() silently no-ops on this resident — not a missing relation in the source IFC.
-- Ifc2x3_SampleCastle.ifc carries 79 IfcRelVoidsElement / 74 IfcRelFillsElement; all 79 edges are
-- RECOVERED VERBATIM below (provenance 'ifc:recovered'), nothing derived, nothing proximity-guessed.
--
-- Generated 2026-07-27 from a clean re-extraction of internal/sources/Ifc2x3_SampleCastle.ifc
-- (witness W-LODHELL-CLASSIFY, 5 PASS). Idempotent: CREATE IF NOT EXISTS + INSERT OR IGNORE on the
-- opening_guid PRIMARY KEY, so re-applying on every open is a no-op. Schema matches the compiler's
-- own DDL (extractIFCtoDB.py :198).
--
-- MEASURED LIMIT, read before expecting a visible change: 65 of the 71 hosts are `kozijn` window-
-- frame walls whose body is 100% removed by their own opening (§VOID-CONSUMED) — they are correctly
-- absent from the scene, so fidByGuid[host_guid] is null and stretchRide skips them. Only 9 of the
-- 74 fills have BOTH ends present as scene features today. The table is the substrate; making a
-- void-consumed host participate as a non-rendered logical anchor is a separate design call.
CREATE TABLE IF NOT EXISTS rel_fills_host (
    opening_guid TEXT PRIMARY KEY,
    host_guid TEXT,
    filling_guid TEXT,
    host_class TEXT,
    filling_class TEXT,
    provenance TEXT DEFAULT 'ifc:recovered'
);
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('01l44l2PPl8f9P1d5P9HO9','1xkmYzLHD1VPKdNI8y8Me1','2boqH8yCb7me06TlnJm870','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('02KjFhRcI7CVZwDi31Zx0O','3V$ApEXsL4kuuKln_RMzx7','3RaVPvaOf64eZBU6WKpwMU','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('04QTF4MUScLSzbMHxktTdB','09Jnrvfpz0LhOau2puveUM','3UPz4qnhz6dR_hTWbylJYM','IfcBuildingElementProxy','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('06pCH1SYZ4TC9sXztIUIP6','0IIlOCBsj3HgQHK5iljQCT','1KInL01tD6DQPBVoxre2dQ','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('06zXvol68ifaSN6A2MPov0','1E7L0rbcP3b9T_kO_wpzXM','0MO3NBPw1FofnfwKUa2odt','IfcBuildingElementProxy','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('0Dyqt$xH7lsEsHVNLZyqpz','27SAqTJ4n1cfkb4yN$O3Ny','2$G2$L_ZfD2xyYJh6wxmZd','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('0E6im$l57EqHL09ReZxPHt','1X9_auq7fAKPab7CpdR8v7','3Y6cgtY0rEBQUJPUx_aPRF','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('0GqtzXOkvIqfkJk8AbAagN','2X9Gop0bn3_x38P_1PGdAJ','2qY72vI$D0SenCZx1z6HDK','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('0IEPamUddvmzAprJOQn4F0','06vshORsrEVvjbvNCwwl$2','1dnueTAkL0h8RlVLQtwd3w','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('0SlGRK9ZOVUK9BtaMmgD2V','07o2mHpkH4_PxUBc290w3Z','2RXwC8nPLBKOSiamyBX0qt','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('0UMmGnV463MLm2FMLl$rLX','32cOaJbaP9VOemKr9dYXtJ','1FtRH1k0bE4fyu_U9mJBmf','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('0_CqIoZjW2apc6nSTYv2Dx','0LxscyRCL35PTDOLAAjfSI','1zWpVk7Az3eeFDJEw36Ky9','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('0bF$T5u17dBe6R6oW2DaAi','0uG931DjD31hhRwgBkGmit','3vBRjYZSX1a8J6d0CTn4Yh','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('0fsr4AdIiOgBwzfZa28r_o','0VctgvK$r7cwrBnu9fG$cA','38X2u$b_51PQbXrbF3UXq0','IfcBuildingElementProxy','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('0jApD$0AtFJCJgOxoJd_ou','1hsZ5cIZbElRpA938d3ffl','0EWFPIrsv7_9lhqHOpPwsU','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('0mwYDZf_8Aq2dXR0_oDKUO','0bPEvM_fn8SPrU2SioL4bx','3qYGwE1BDBbP2FWtfJUDNa','IfcBuildingElementProxy','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('0u433U_mtqmy447tYAv_dE','2jJ$Htazn4wuzmZrbCCkR9',NULL,'IfcCovering',NULL,'ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('0yeHirqI6mcF2qTQZ26WcN','2jJ$Htazn4wuzmZrbCCkR9',NULL,'IfcCovering',NULL,'ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('0zkPGJjLkL9gWCbwVvNqqA','3fvHYcQET4afRMl3etTK4F','26iMI7lnj4Rukyjg89OAF3','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('10_3QclYzmHVaIndGIkCXa','3u3z2zFojEchllTko9vkJ5','2EqkVNVRnBUvQjRlN4tm$r','IfcBuildingElementProxy','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('13Vvkc_yyjKxPao2AYC3C4','1WCZr3c7r05hqSejiWoWO4','1k3S_FTjr5YgVNsOxgXfqg','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1ClSPLKbrtgzKnGghFJfRG','0$YDCcbYPB0wRxDYucu1$k','0FcHfq3eXDUvB1x$PxjHW5','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1E_dUDvmJWCU7qbEHGNUFL','2SOFxehfn3JPJ42eH$gc$u','1jm08JDI1AxPr7MMlr69d8','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1Gu952rAxgbDp5TElOy2HF','0yZXVK6wf1RuZHbCnDbIWu','266hPy3$L5vfMXcAOOFF6p','IfcBuildingElementProxy','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1Gxll6B1U7YgSc0Q2yq5zA','1HTzx6dK99rxYirl5arG$b','27bh8yZhL8hPRD0H6aMxEY','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1HMu6$4nLPMJmbympAKWlh','1j6lJOCJrBfhwVjXcDrBMU','012S6Z0qLCRuoYXSZ2tygw','IfcBuildingElementProxy','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1LBU1tL8d9DEA9BhZ9gsuc','2iybqz3VH31hQztnwzJ_m7','0eASoFkCvD_OTC_ct3cBps','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1OVySEmHFHdipc8tHw$JoP','0Nj60ieO55uBt_I0iEvvde','1ktZHnXqP81AONft3VUKlo','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1TbD1hYlkRvhSw29VgOblT','1ZbRQwjUz9DQ98KhTax8G9','0xrZguOJ55xx5lucOklTa9','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1TuvwTbwpgOgwOQKGHCz13','0uG931DjD31hhRwgBkGmit','3kTNDXm3L6jgBFZ2taLcKJ','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1Waj0870YwDfcS4RQijrMr','1qSuEDSd1E8ftzFK1HXdBc','13lQ7MfpP9YQNh0Z31qoMP','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1WyXfW4Hqoowfe6PwyMRfW','0uG931DjD31hhRwgBkGmit','0xmEoRha9E$xhaP7dhI3oe','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1mgaTBo5Ej3i1I52D7Kd99','3C2fvEKUr00BlwuG1or05l',NULL,'IfcSlab',NULL,'ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1og9YKWY_EFKLC9YltQRUm','36fadt$IzDJQp5auYj8rIY','2aVhmg2N92hhv4rjQpPXmo','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1pxF$WIrY17zECdxnWQm2P','2qmQa8nAP39u6po5334l9v','0Nx0E1OHf1DuxTjjuUm2Ac','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1qrRkv3zXyuAMHWKz0fGJj','3XhijCDWT4ERsmhSDcEHtI','1dvN3gzSD4L9Bv2$zoJRLk','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1sNgiC090UdtFQO5npPFM2','0zCNq_mof6gPonl4mLYuLv','1WI7CxHKj8vQB6ZX1aG6wQ','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1sQQnxp4yO4HQpeAeQHvRT','1J9G$AMj5D8ePpFewsM_ee','2mNENoxwD4MQMQY_gKi$v7','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1slHY8IMUglWsYTrH3MaIp','01hUAhn2r989LDYSpRx4VK','2KQzcnl4P108p1xYLp2BcG','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1tknVQg$jcQGLlmYxhrZlq','2r4e5jHWfDKhLK$Is1u15D','3G$_TtmoH0i97AYiv2eBBu','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1tsM6iVjMm95VTODAaeqlL','0SzdhD7kXE$9LKStg07UwP','2KiBBLKs133RJOEnn$kg25','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1yiR6eAmST0jHLMQDwQyya','1qHBiNfAHCHhBLrRv9Uyf5','3upcShrCbFfh0jm4mYUUdu','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('1zo9HLxE57v4DmFM1Z7srY','0uG931DjD31hhRwgBkGmit','30Awpp2EX78eiSUY7FvQt3','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('2$I6iiQ9n8n4TOgqMzA0SJ','0ZN2GJozT4VxCVh_WHtQyq','3lVtU7tjD3YOCLUfqajZ2A','IfcBuildingElementProxy','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('264dm_Wg0ghNBAsQyrjaUO','0uG931DjD31hhRwgBkGmit','3ZKKU$3lPCq8PEyTGjaGdU','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('2FXfLj7BbJzgyZ2gjiLgfP','13hN5zL1L2fftXqB_Ac_WZ','2hVrKM8Vv2Xxs7m9ITda8L','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('2GK2888FNUDebw1bXUxS3V','0GioG4iQzA1OyX4F47kc4a','1DmcUaFzzFFhg92TJQnxyJ','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('2H8TFkE8qW1axTjo9SRRzr','3CRwhrtRn1UvX9iQV_OTuz','2GoKiXXxrC7g4IPoyQPZ2t','IfcBuildingElementProxy','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('2Kc0O_KBDC0CH2mBZ6ePqI','3JaHyppKTBGBnjCpoJt74v','3WXd7RsH9CT9CRRwuhBxrU','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('2YTu3steXE$WMJAsJFbg27','356ZU40Tn3tvjGsP5aWnKD','03lGFt1VjBDe6syvgmNFAy','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('2ZPLYMlv$R69hry2mM7R2B','1J9G$AMj5D8ePpFewsM_ee','2wNrfbWo5F3AXCQjcATu9n','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('2_5jthHi8DiV82sEu6QUir','1a3Bw$Plv1NBGNlNfFUZO_','0yGGfH85nFPvINarcAfBNX','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('2jT_OTjZM5odqgM7jd8Qq2','0P9P2MTnDFWgpzAECWRMfc','0pZslPSAb8jBEsesxVZzu0','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('2k0WVKunoAv_AIv2NCiO8z','03x61TFn1FxQHXFUNuParm','3vqhA9V$zD8Ri_tijsQ9Uy','IfcBuildingElementProxy','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('2k7SwcvISjmPRfe9AnwmeV','23NrJ1a$r1DOY9eePDI0DJ','2$5nWI0fL8zwtrwndfa9MN','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('2l7rgQIFSfxzKkno1Hi5D1','1i4_mvNgv86Pj97Vy1f2eY','2ri5H4RCf2ZuCMpo1Ccl52','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('2qR9Q2qf_i3yhWEtsdkt4l','3TK6FSuO9AVg4wHo$O3IN3','140c7DVn1Fdgh5_iO2DSKg','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('2sE8Ha8jZAEIetaRIzSZEf','3xum028un7c91eysAw7ToR','3topRXa9T1svryvk0HDA1V','IfcBuildingElementProxy','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('2xicW6eU04O2vo5611eb6m','2_xwfAnHjEGheqbGUc$BD5','2Qc0XfkND1d86$Q97dSDkt','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('2yG6PjMsJCSw$wWoUwaY4R','3kQNZLqVfDcRRvBkM1IMS9',NULL,'IfcSlab',NULL,'ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('37zRds4ANdcvJxswLMHEbg','0vTAFL4d1DwxQSNiJxvejT','2YXmX7u6r4yOOh$kIa$Gd6','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3Don1s7QEHh1a2pb7mpkxv','3lUaefqT14jRJXPO$2osRB','178Zovd$P9MeTHI2jV$s2n','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3FJMSSB3ATVembQhvKe9QY','2jJ$Htazn4wuzmZrbCCkR9',NULL,'IfcCovering',NULL,'ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3GP9QYrbayq33qri5qyt2$','0I$ApwjMb2WhHUnG9PohvA','3LppQIb2j30xblkm5GtTTV','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3Ip6HsMyI1NcWFsDorI_mc','0FdLbmS_r6Ch8VPitxry03','0HKXdsxQDBXehvvnIH9Bj2','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3Loz87W2QU8ZXxJvmvicsl','2Hagr_o5nCPha8GzqG_2Pz','2tncJiXU52xOIwnI4dHkq$','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3M0D3egUMBYtAWLjf7ifyp','1tkaVzyOLEHRrk3ZXytZyO','0rEPlH2fP8YQ_q3GiazsFo','IfcBuildingElementProxy','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3OdfN$Ive1S0F$$8adHAnR','1ZbRQwjUz9DQ98KhTax8G9','3nUiG96vjAwPUR6jFmv$ZI','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3P4AXXdMqDfySyU5JAVKQq','1oHEx35PDDzQFKEx3RZUI5','2xD3QGjx90oAGyybkEra8b','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3QHlZ2Unwl2_E63a5CXgc4','0d193_IC94VBo0OC8YxmOX','39e5HG9Mz5bhpeErZLhRP4','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3V60v400XEBSLdGt9x8vAo','1A9aTEU4z9SwaqEUwI8Lx4','2vImyoNwX9iBXoTp4G3gAg','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3WMY5krdz54lIOHbK6cg3o','0A$dxBFCfD698O7H1hW$fd','2DaLEnOpD71xPKiE7SoDTP','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3aaZ34vTqUdH_lsBbTmw$t','1AtB01imf94g7vyKEx$EUO','0rOlpuy6fEpfuuqvscj$PW','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3ccxvIHVc_Chr3XroWbB9b','32BRu80e95IgL7sHEAaW4K','26_$0XSjr4qx6Hsbp36s4D','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3ib8v8dl32P5kzhn6tXbk3','148inggZz0fAp_L7YGDBl6','0WtDl5Fx1CGO$F0RJCi8b$','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3qtaRtgoOJ4eB7z7birJTK','1V2qCAZ9rAp8VsEGyWln2v','1vWdN2kyHCyOFb8jrE1QwS','IfcBuildingElementProxy','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3tMTKSP5YJ505cjzpGpCoP','09R3x3btbEC9NWKCsQ9Ndr','1ZFLyNI$fDRgE2KgYahsry','IfcBuildingElementProxy','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3wQwZtXMIt8MY6jmRmfYts','2T7$dTI398mR34m8VeIw4m','1PAxaJRu13gfudq_tpVBm7','IfcWallStandardCase','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3zAMENWkMpWjVZBUxGGlNb','3bi7XzqxrAgvdZxFnRwTdg','1xjGgwmzP23uthLfXurB67','IfcWallStandardCase','IfcDoor','ifc:recovered');

-- SampleCastle_ARC.db patch — generated by scripts/gen_void_anchor_patch.py (bim-compiler).

-- ── §ANCHOR — void-consumed hosts persisted as non-rendered logical anchors ──
-- RESUME_MODELLER_LOD400_REAL_GEOMETRY.md §START HERE OPEN 1 — USER-APPROVED 2026-07-30,
-- binding condition: anchors are UNMISTAKABLE (is_anchor=1 + transform_source='void_anchor')
-- and EXCLUDED from every count, pick, and audit. NO element_instances rows are added —
-- an anchor has no geometry hash, nothing to render (§GEOM-HARDFAIL untouched).
-- Source: fresh extraction SC_anchor_new.db   Generated: 2026-07-30
-- 65 anchors; target already had 65/65 meta rows (the meta-only population) and 0/65 transform rows.
-- Frame guard: per-axis mean Δ = (0.0072,-0.0104,-0.0232) m (systematic, ≤ 0.05 m), worst per-element scatter 2.596 m over 3225 shared guids.
-- element_transforms values: center+rotation from shape.transformation.matrix;
-- bbox_x/y/z = pre-boolean Body ITEM LOCAL extent (NOT world AABB) — 'void_anchor' marks
-- the convention. Idempotent inserts; ALTERs run on RAW shipped bytes only (see generator).
ALTER TABLE elements_meta ADD COLUMN is_anchor INTEGER DEFAULT 0;
ALTER TABLE element_transforms ADD COLUMN transform_source TEXT;
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('0$YDCcbYPB0wRxDYucu1$k','IfcWallStandardCase','kozijn','01 eerste verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('0$YDCcbYPB0wRxDYucu1$k',5.1770000000000005,8.8599999999,3.7800000000000002,0.0,0.0,-1.5707963267948966,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('01hUAhn2r989LDYSpRx4VK','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('01hUAhn2r989LDYSpRx4VK',3.83699994411,4.73299993738,-0.026000000000000002,0.0,0.0,1.570796389174475,1.034,0.114,2.596,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('03x61TFn1FxQHXFUNuParm','IfcBuildingElementProxy','kozijn','03 derde verdieping','ARC','01 Hout - hardhout',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('03x61TFn1FxQHXFUNuParm',9.96695510086,11.779,8.968,0.0,0.0,3.141592653589793,1.016,0.114,2.64,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('06vshORsrEVvjbvNCwwl$2','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('06vshORsrEVvjbvNCwwl$2',3.1400000811099997,12.7269999777,-0.026000000000000002,0.0,0.0,0.0,1.21,0.114,2.656,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('07o2mHpkH4_PxUBc290w3Z','IfcWallStandardCase','kozijn','01 eerste verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('07o2mHpkH4_PxUBc290w3Z',5.1770000000000005,2.85,3.7800000000000002,0.0,0.0,-1.5707963267948966,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('09Jnrvfpz0LhOau2puveUM','IfcBuildingElementProxy','kozijn','02 tweede verdieping','ARC','01 Hout - hardhout',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('09Jnrvfpz0LhOau2puveUM',12.1299996815,15.269,5.968,0.0,0.0,-1.5707963267948966,1.016,0.114,2.64,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('09R3x3btbEC9NWKCsQ9Ndr','IfcBuildingElementProxy','kozijn','01 eerste verdieping','ARC','01 Hout - hardhout',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('09R3x3btbEC9NWKCsQ9Ndr',9.30999983013,15.529,2.983,0.0,0.0,0.0,1.016,0.114,2.625,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('0A$dxBFCfD698O7H1hW$fd','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('0A$dxBFCfD698O7H1hW$fd',10.2149999845,0.227,-0.026000000000000002,0.0,0.0,3.141592653589793,1.715,0.114,2.46599998916,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('0FdLbmS_r6Ch8VPitxry03','IfcWallStandardCase','kozijn','02 tweede verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('0FdLbmS_r6Ch8VPitxry03',21.422999892700002,6.5200000000000005,5.974,0.0,0.0,-1.5707963267948966,2.5399999921300003,0.114,2.176,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('0GioG4iQzA1OyX4F47kc4a','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('0GioG4iQzA1OyX4F47kc4a',20.659999892700004,0.877,0.78,0.0,0.0,3.141592653589793,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('0I$ApwjMb2WhHUnG9PohvA','IfcWallStandardCase','kozijn','01 eerste verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('0I$ApwjMb2WhHUnG9PohvA',21.422999892700002,8.8599999999,3.7800000000000002,0.0,0.0,-1.5707963267948966,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('0IIlOCBsj3HgQHK5iljQCT','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('0IIlOCBsj3HgQHK5iljQCT',15.923,20.3150000004,0.78,0.0,0.0,-1.5707963267948966,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('0LxscyRCL35PTDOLAAjfSI','IfcWallStandardCase','kozijn','01 eerste verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('0LxscyRCL35PTDOLAAjfSI',5.1770000000000005,6.485000003930001,2.974,0.0,0.0,-1.5707963267948966,2.47,0.114,2.656,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('0Nj60ieO55uBt_I0iEvvde','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('0Nj60ieO55uBt_I0iEvvde',10.5349999845,0.227,-0.026000000000000002,0.0,0.0,0.0,1.715,0.114,2.46599998916,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('0P9P2MTnDFWgpzAECWRMfc','IfcWallStandardCase','kozijn','01 eerste verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('0P9P2MTnDFWgpzAECWRMfc',21.422999892700002,2.85,3.7800000000000002,0.0,0.0,-1.5707963267948966,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('0SzdhD7kXE$9LKStg07UwP','IfcWallStandardCase','kozijn','03 derde verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('0SzdhD7kXE$9LKStg07UwP',5.6125,10.8070000004,9.685519826277,0.0,0.0,1.5707963267948966,0.916,0.114,1.76,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('0VctgvK$r7cwrBnu9fG$cA','IfcBuildingElementProxy','kozijn','00 begane grond','ARC','01 Hout - hardhout',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('0VctgvK$r7cwrBnu9fG$cA',7.744009458870001,11.193,0.0,0.0,0.0,0.0,1.47,0.114,2.608,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('0ZN2GJozT4VxCVh_WHtQyq','IfcBuildingElementProxy','kozijn','03 derde verdieping','ARC','01 Hout - hardhout','1.000,1.000,1.000,1.000','Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('0ZN2GJozT4VxCVh_WHtQyq',11.5924996602,15.1317461493,8.968,0.0,0.0,-1.5707963267948966,1.016,0.114,2.45,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('0bPEvM_fn8SPrU2SioL4bx','IfcBuildingElementProxy','kozijn','01 eerste verdieping','ARC','01 Hout - hardhout',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('0bPEvM_fn8SPrU2SioL4bx',11.6500000626,15.269,2.968,0.0,0.0,-1.5707963267948966,1.016,0.114,2.64,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('0d193_IC94VBo0OC8YxmOX','IfcWallStandardCase','kozijn','01 eerste verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('0d193_IC94VBo0OC8YxmOX',18.0899996736,15.6230003943,3.7800000000000002,0.0,0.0,0.0,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('0vTAFL4d1DwxQSNiJxvejT','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('0vTAFL4d1DwxQSNiJxvejT',1.5800000811100001,12.726999936,0.78,0.0,0.0,0.0,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('0yZXVK6wf1RuZHbCnDbIWu','IfcBuildingElementProxy','kozijn','03 derde verdieping','ARC','01 Hout - hardhout',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('0yZXVK6wf1RuZHbCnDbIWu',16.3839999904,0.226999940649,8.968,0.0,0.0,0.0,0.30031777906999996,0.114,2.637,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('0zCNq_mof6gPonl4mLYuLv','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('0zCNq_mof6gPonl4mLYuLv',10.330000097800001,21.3830000004,0.78,0.0,0.0,0.0,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('13hN5zL1L2fftXqB_Ac_WZ','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('13hN5zL1L2fftXqB_Ac_WZ',16.3849999845,0.227,-0.026000000000000002,0.0,0.0,0.0,1.715,0.114,2.46599998916,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('148inggZz0fAp_L7YGDBl6','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('148inggZz0fAp_L7YGDBl6',5.1770000000000005,2.85,0.78,0.0,0.0,-1.5707963267948966,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('1A9aTEU4z9SwaqEUwI8Lx4','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('1A9aTEU4z9SwaqEUwI8Lx4',5.1770000000000005,8.8599999999,0.78,0.0,0.0,-1.5707963267948966,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('1AtB01imf94g7vyKEx$EUO','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('1AtB01imf94g7vyKEx$EUO',-0.12300004173300001,18.8600000004,0.78,0.0,0.0,-1.5707963267948966,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('1E7L0rbcP3b9T_kO_wpzXM','IfcBuildingElementProxy','kozijn','00 begane grond','ARC','01 Hout - hardhout',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('1E7L0rbcP3b9T_kO_wpzXM',10.623000000000001,15.273,0.0,0.0,0.0,-1.5707963267948966,1.034,0.114,2.608,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('1HTzx6dK99rxYirl5arG$b','IfcWallStandardCase','kozijn','02 tweede verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('1HTzx6dK99rxYirl5arG$b',16.3849999845,0.227,5.945,0.0,0.0,0.0,1.715,0.114,2.688,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('1V2qCAZ9rAp8VsEGyWln2v','IfcBuildingElementProxy','kozijn','03 derde verdieping','ARC','01 Hout - hardhout',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('1V2qCAZ9rAp8VsEGyWln2v',10.5339999904,0.226999940649,8.968,0.0,0.0,0.0,0.30031777906999996,0.114,2.637,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('1WCZr3c7r05hqSejiWoWO4','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('1WCZr3c7r05hqSejiWoWO4',14.3499999845,0.227,-0.026000000000000002,0.0,0.0,0.0,1.715,0.114,2.46599998916,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('1X9_auq7fAKPab7CpdR8v7','IfcWallStandardCase','kozijn','01 eerste verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('1X9_auq7fAKPab7CpdR8v7',4.35000008111,12.7269999777,3.7800000000000002,0.0,0.0,3.141592653589793,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('1a3Bw$Plv1NBGNlNfFUZO_','IfcWallStandardCase','kozijn','01 eerste verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('1a3Bw$Plv1NBGNlNfFUZO_',21.422999892700002,6.485000003930001,2.974,0.0,0.0,-1.5707963267948966,2.47,0.114,2.656,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('1hsZ5cIZbElRpA938d3ffl','IfcWallStandardCase','kozijn','03 derde verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('1hsZ5cIZbElRpA938d3ffl',6.817,6.51999999213,9.074,0.0,0.0,-1.5707963267948966,2.5399999921300003,0.114,2.282,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('1i4_mvNgv86Pj97Vy1f2eY','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('1i4_mvNgv86Pj97Vy1f2eY',15.923,17.9150000004,0.78,0.0,0.0,-1.5707963267948966,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('1j6lJOCJrBfhwVjXcDrBMU','IfcBuildingElementProxy','kozijn','00 begane grond','ARC','01 Hout - hardhout',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('1j6lJOCJrBfhwVjXcDrBMU',9.536,11.193,-0.017,0.0,0.0,0.0,1.016,0.114,2.6270000000000002,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('1oHEx35PDDzQFKEx3RZUI5','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('1oHEx35PDDzQFKEx3RZUI5',21.202999892700003,13.3599997461,0.78,0.0,0.0,-1.5707963267948966,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('1qHBiNfAHCHhBLrRv9Uyf5','IfcWallStandardCase','kozijn','01 eerste verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('1qHBiNfAHCHhBLrRv9Uyf5',5.396999892709999,11.869999746100001,3.7800000000000002,0.0,0.0,-1.5707963267948966,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('1qSuEDSd1E8ftzFK1HXdBc','IfcWallStandardCase','kozijn','02 tweede verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('1qSuEDSd1E8ftzFK1HXdBc',5.1770000000000005,6.5200000000000005,5.974,0.0,0.0,-1.5707963267948966,2.5399999921300003,0.114,2.176,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('1tkaVzyOLEHRrk3ZXytZyO','IfcBuildingElementProxy','kozijn','02 tweede verdieping','ARC','01 Hout - hardhout',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('1tkaVzyOLEHRrk3ZXytZyO',9.96695510086,11.779,5.968,0.0,0.0,3.141592653589793,1.016,0.114,2.64,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('1xkmYzLHD1VPKdNI8y8Me1','IfcWallStandardCase','kozijn','03 derde verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('1xkmYzLHD1VPKdNI8y8Me1',20.9874998065,12.4480000004,9.685519826277,0.0,0.0,1.5707963267948966,0.916,0.114,1.727,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('23NrJ1a$r1DOY9eePDI0DJ','IfcWallStandardCase','kozijn','01 eerste verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('23NrJ1a$r1DOY9eePDI0DJ',12.3700000978,21.3830000004,3.8,0.0,0.0,0.0,1.21,0.114,1.79,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('27SAqTJ4n1cfkb4yN$O3Ny','IfcWallStandardCase','kozijn','01 eerste verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('27SAqTJ4n1cfkb4yN$O3Ny',10.330000097800001,21.3830000004,3.8,0.0,0.0,0.0,1.21,0.114,1.79,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('2Hagr_o5nCPha8GzqG_2Pz','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('2Hagr_o5nCPha8GzqG_2Pz',-0.12300004173300001,16.4600000004,0.78,0.0,0.0,-1.5707963267948966,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('2SOFxehfn3JPJ42eH$gc$u','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('2SOFxehfn3JPJ42eH$gc$u',1.17998980281,21.397000000000002,-0.026000000000000002,0.0,0.0,0.0,2.85999999213,0.114,2.64,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('2T7$dTI398mR34m8VeIw4m','IfcWallStandardCase','kozijn','01 eerste verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('2T7$dTI398mR34m8VeIw4m',1.5800000811100001,12.7269999777,3.7800000000000002,0.0,0.0,0.0,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('2X9Gop0bn3_x38P_1PGdAJ','IfcWallStandardCase','kozijn','01 eerste verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('2X9Gop0bn3_x38P_1PGdAJ',4.03998980281,21.383,2.974,0.0,0.0,3.141592653589793,2.85999999213,0.114,2.616,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('2_xwfAnHjEGheqbGUc$BD5','IfcWallStandardCase','kozijn','01 eerste verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('2_xwfAnHjEGheqbGUc$BD5',6.37000009779,21.3830000004,3.8,0.0,0.0,0.0,1.21,0.114,1.79,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('2iybqz3VH31hQztnwzJ_m7','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('2iybqz3VH31hQztnwzJ_m7',21.422999892700002,2.85,0.78,0.0,0.0,-1.5707963267948966,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('2qmQa8nAP39u6po5334l9v','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('2qmQa8nAP39u6po5334l9v',5.94,0.877,0.78,0.0,0.0,0.0,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('2r4e5jHWfDKhLK$Is1u15D','IfcWallStandardCase','kozijn','02 tweede verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('2r4e5jHWfDKhLK$Is1u15D',10.5349999845,0.227,5.945,0.0,0.0,0.0,1.715,0.114,2.688,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('32BRu80e95IgL7sHEAaW4K','IfcWallStandardCase','separatiewand','01 eerste verdieping','ARC','IFC_separatiewand_gasbeton_70mm',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('32BRu80e95IgL7sHEAaW4K',9.20000006259,16.940999951000002,2.91,0.0,0.0,1.5707963267948966,0.775,0.07,2.71,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('32cOaJbaP9VOemKr9dYXtJ','IfcWallStandardCase','kozijn','02 tweede verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('32cOaJbaP9VOemKr9dYXtJ',14.349999875400002,0.227,5.945,0.0,0.0,0.0,1.715,0.114,2.688,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('356ZU40Tn3tvjGsP5aWnKD','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('356ZU40Tn3tvjGsP5aWnKD',18.0899996736,15.623000287000002,0.78,0.0,0.0,0.0,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('36fadt$IzDJQp5auYj8rIY','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('36fadt$IzDJQp5auYj8rIY',12.3700000978,21.3830000004,0.78,0.0,0.0,0.0,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('3CRwhrtRn1UvX9iQV_OTuz','IfcBuildingElementProxy','kozijn','03 derde verdieping','ARC','01 Hout - hardhout',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('3CRwhrtRn1UvX9iQV_OTuz',10.2149998754,0.226999940649,8.968,0.0,0.0,3.141592653589793,0.30031777906999996,0.114,2.637,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('3JaHyppKTBGBnjCpoJt74v','IfcWallStandardCase','kozijn','02 tweede verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('3JaHyppKTBGBnjCpoJt74v',8.49999987537,0.227,5.945,0.0,0.0,0.0,1.715,0.114,2.688,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('3TK6FSuO9AVg4wHo$O3IN3','IfcWallStandardCase','kozijn','03 derde verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('3TK6FSuO9AVg4wHo$O3IN3',19.783,6.51999999213,9.074,0.0,0.0,-1.5707963267948966,2.5399999921300003,0.114,2.282,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('3V$ApEXsL4kuuKln_RMzx7','IfcWallStandardCase','kozijn','01 eerste verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('3V$ApEXsL4kuuKln_RMzx7',21.203,13.3599997461,3.7800000000000002,0.0,0.0,-1.5707963267948966,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('3XhijCDWT4ERsmhSDcEHtI','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('3XhijCDWT4ERsmhSDcEHtI',21.422999892700002,8.8599999999,0.78,0.0,0.0,-1.5707963267948966,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('3bi7XzqxrAgvdZxFnRwTdg','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('3bi7XzqxrAgvdZxFnRwTdg',5.396999892709999,11.869999746100001,-0.026000000000000002,0.0,0.0,-1.5707963267948966,1.21,0.114,2.656,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('3fvHYcQET4afRMl3etTK4F','IfcWallStandardCase','kozijn','00 begane grond','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('3fvHYcQET4afRMl3etTK4F',6.37000009779,21.3830000004,0.78,0.0,0.0,0.0,1.21,0.114,1.85,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('3lUaefqT14jRJXPO$2osRB','IfcWallStandardCase','kozijn','03 derde verdieping','ARC','IFC_kozijn_90x114',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('3lUaefqT14jRJXPO$2osRB',18.2369999556,15.407499851299999,9.685519826277,0.0,0.0,0.0,0.916,0.114,1.76,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('3u3z2zFojEchllTko9vkJ5','IfcBuildingElementProxy','kozijn','03 derde verdieping','ARC','01 Hout - hardhout',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('3u3z2zFojEchllTko9vkJ5',16.0649998754,0.226999940649,8.968,0.0,0.0,3.141592653589793,0.30031777906999996,0.114,2.637,'void_anchor');
INSERT OR IGNORE INTO elements_meta (guid,ifc_class,element_name,storey,discipline,material_name,material_rgba,building) VALUES ('3xum028un7c91eysAw7ToR','IfcBuildingElementProxy','kozijn','01 eerste verdieping','ARC','01 Hout - hardhout',NULL,'Ifc2x3_SampleCastle');
INSERT OR IGNORE INTO element_transforms (guid,center_x,center_y,center_z,rotation_x,rotation_y,rotation_z,bbox_x,bbox_y,bbox_z,transform_source) VALUES ('3xum028un7c91eysAw7ToR',9.96695510086,11.779,2.968,0.0,0.0,3.141592653589793,1.016,0.114,2.64,'void_anchor');
UPDATE elements_meta SET is_anchor=1 WHERE guid IN ('0$YDCcbYPB0wRxDYucu1$k','01hUAhn2r989LDYSpRx4VK','03x61TFn1FxQHXFUNuParm','06vshORsrEVvjbvNCwwl$2','07o2mHpkH4_PxUBc290w3Z','09Jnrvfpz0LhOau2puveUM','09R3x3btbEC9NWKCsQ9Ndr','0A$dxBFCfD698O7H1hW$fd','0FdLbmS_r6Ch8VPitxry03','0GioG4iQzA1OyX4F47kc4a','0I$ApwjMb2WhHUnG9PohvA','0IIlOCBsj3HgQHK5iljQCT','0LxscyRCL35PTDOLAAjfSI','0Nj60ieO55uBt_I0iEvvde','0P9P2MTnDFWgpzAECWRMfc','0SzdhD7kXE$9LKStg07UwP','0VctgvK$r7cwrBnu9fG$cA','0ZN2GJozT4VxCVh_WHtQyq','0bPEvM_fn8SPrU2SioL4bx','0d193_IC94VBo0OC8YxmOX','0vTAFL4d1DwxQSNiJxvejT','0yZXVK6wf1RuZHbCnDbIWu','0zCNq_mof6gPonl4mLYuLv','13hN5zL1L2fftXqB_Ac_WZ','148inggZz0fAp_L7YGDBl6','1A9aTEU4z9SwaqEUwI8Lx4','1AtB01imf94g7vyKEx$EUO','1E7L0rbcP3b9T_kO_wpzXM','1HTzx6dK99rxYirl5arG$b','1V2qCAZ9rAp8VsEGyWln2v','1WCZr3c7r05hqSejiWoWO4','1X9_auq7fAKPab7CpdR8v7','1a3Bw$Plv1NBGNlNfFUZO_','1hsZ5cIZbElRpA938d3ffl','1i4_mvNgv86Pj97Vy1f2eY','1j6lJOCJrBfhwVjXcDrBMU','1oHEx35PDDzQFKEx3RZUI5','1qHBiNfAHCHhBLrRv9Uyf5','1qSuEDSd1E8ftzFK1HXdBc','1tkaVzyOLEHRrk3ZXytZyO','1xkmYzLHD1VPKdNI8y8Me1','23NrJ1a$r1DOY9eePDI0DJ','27SAqTJ4n1cfkb4yN$O3Ny','2Hagr_o5nCPha8GzqG_2Pz','2SOFxehfn3JPJ42eH$gc$u','2T7$dTI398mR34m8VeIw4m','2X9Gop0bn3_x38P_1PGdAJ','2_xwfAnHjEGheqbGUc$BD5','2iybqz3VH31hQztnwzJ_m7','2qmQa8nAP39u6po5334l9v','2r4e5jHWfDKhLK$Is1u15D','32BRu80e95IgL7sHEAaW4K','32cOaJbaP9VOemKr9dYXtJ','356ZU40Tn3tvjGsP5aWnKD','36fadt$IzDJQp5auYj8rIY','3CRwhrtRn1UvX9iQV_OTuz','3JaHyppKTBGBnjCpoJt74v','3TK6FSuO9AVg4wHo$O3IN3','3V$ApEXsL4kuuKln_RMzx7','3XhijCDWT4ERsmhSDcEHtI','3bi7XzqxrAgvdZxFnRwTdg','3fvHYcQET4afRMl3etTK4F','3lUaefqT14jRJXPO$2osRB','3u3z2zFojEchllTko9vkJ5','3xum028un7c91eysAw7ToR');
UPDATE element_transforms SET transform_source='void_anchor' WHERE guid IN ('0$YDCcbYPB0wRxDYucu1$k','01hUAhn2r989LDYSpRx4VK','03x61TFn1FxQHXFUNuParm','06vshORsrEVvjbvNCwwl$2','07o2mHpkH4_PxUBc290w3Z','09Jnrvfpz0LhOau2puveUM','09R3x3btbEC9NWKCsQ9Ndr','0A$dxBFCfD698O7H1hW$fd','0FdLbmS_r6Ch8VPitxry03','0GioG4iQzA1OyX4F47kc4a','0I$ApwjMb2WhHUnG9PohvA','0IIlOCBsj3HgQHK5iljQCT','0LxscyRCL35PTDOLAAjfSI','0Nj60ieO55uBt_I0iEvvde','0P9P2MTnDFWgpzAECWRMfc','0SzdhD7kXE$9LKStg07UwP','0VctgvK$r7cwrBnu9fG$cA','0ZN2GJozT4VxCVh_WHtQyq','0bPEvM_fn8SPrU2SioL4bx','0d193_IC94VBo0OC8YxmOX','0vTAFL4d1DwxQSNiJxvejT','0yZXVK6wf1RuZHbCnDbIWu','0zCNq_mof6gPonl4mLYuLv','13hN5zL1L2fftXqB_Ac_WZ','148inggZz0fAp_L7YGDBl6','1A9aTEU4z9SwaqEUwI8Lx4','1AtB01imf94g7vyKEx$EUO','1E7L0rbcP3b9T_kO_wpzXM','1HTzx6dK99rxYirl5arG$b','1V2qCAZ9rAp8VsEGyWln2v','1WCZr3c7r05hqSejiWoWO4','1X9_auq7fAKPab7CpdR8v7','1a3Bw$Plv1NBGNlNfFUZO_','1hsZ5cIZbElRpA938d3ffl','1i4_mvNgv86Pj97Vy1f2eY','1j6lJOCJrBfhwVjXcDrBMU','1oHEx35PDDzQFKEx3RZUI5','1qHBiNfAHCHhBLrRv9Uyf5','1qSuEDSd1E8ftzFK1HXdBc','1tkaVzyOLEHRrk3ZXytZyO','1xkmYzLHD1VPKdNI8y8Me1','23NrJ1a$r1DOY9eePDI0DJ','27SAqTJ4n1cfkb4yN$O3Ny','2Hagr_o5nCPha8GzqG_2Pz','2SOFxehfn3JPJ42eH$gc$u','2T7$dTI398mR34m8VeIw4m','2X9Gop0bn3_x38P_1PGdAJ','2_xwfAnHjEGheqbGUc$BD5','2iybqz3VH31hQztnwzJ_m7','2qmQa8nAP39u6po5334l9v','2r4e5jHWfDKhLK$Is1u15D','32BRu80e95IgL7sHEAaW4K','32cOaJbaP9VOemKr9dYXtJ','356ZU40Tn3tvjGsP5aWnKD','36fadt$IzDJQp5auYj8rIY','3CRwhrtRn1UvX9iQV_OTuz','3JaHyppKTBGBnjCpoJt74v','3TK6FSuO9AVg4wHo$O3IN3','3V$ApEXsL4kuuKln_RMzx7','3XhijCDWT4ERsmhSDcEHtI','3bi7XzqxrAgvdZxFnRwTdg','3fvHYcQET4afRMl3etTK4F','3lUaefqT14jRJXPO$2osRB','3u3z2zFojEchllTko9vkJ5','3xum028un7c91eysAw7ToR') AND transform_source IS NULL;

-- SampleCastle_ARC.db rel_aggregates — real IfcRelAggregates parent->child GUID pairs (§NOGEO_COMPOSE,
-- prompts/4D_SCHEDULE_PERFECTION.md Part B — Modeller port). Relationship-only, NO computed values:
-- composeGhostsFromAggregates() does the union-bbox math live from element_transforms at open.
-- Recovered VERBATIM from the source IFC's own IfcRelAggregates (same read as
-- extractIFCtoDB.py extract, the ONE implementation), filtered to this DB's 52 ghost
-- aggregate-parents (elements_meta rows with no element_transforms row).
-- Source: Ifc2x3_SampleCastle.ifc (277)   Generated: 2026-08-10 (ifcopenshell 0.8.4.post1)
-- Idempotent: CREATE IF NOT EXISTS + INSERT OR IGNORE on the (parent_guid,child_guid) PRIMARY KEY.

CREATE TABLE IF NOT EXISTS rel_aggregates (parent_guid TEXT NOT NULL, child_guid TEXT NOT NULL, PRIMARY KEY (parent_guid, child_guid));
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1LODwiyWT2UwMzhuYIlYa2','34RnzQjo78q9a_nkPqmuFs');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1LODwiyWT2UwMzhuYIlYa2','23uCBkBX1OgotbHJjad5qB');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0Kvw2yChTBXuQ4cILhgS7P','1Y6HZlUA6K9eS1kBX9vsSC');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0Kvw2yChTBXuQ4cILhgS7P','1PuyKaDmVgHWp4NO1th780');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('07cuRabSn7ofP$cYt02X4i','07BhnDAlpluxhFLT3HVXJx');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('07cuRabSn7ofP$cYt02X4i','3PhiSOz3BRjsd4Mz3W2eLt');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1QAOzVcfjCIgepdR9u6YaR','2mrhxpI1dR0dhKf5xPBRmq');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1QAOzVcfjCIgepdR9u6YaR','1F8JPBU_xywOMXcbfvpU8I');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0qpBWaAanEoR5V$fq4r3RS','1DKa1r7TJyn_faqOfhgMfE');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0qpBWaAanEoR5V$fq4r3RS','3GnRUT9Hd2823326CS$6Wl');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2ojoT3QkX9_xyO2CmkhazA','0ZPw7Vnf0xeyWjR7mM8GXh');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2ojoT3QkX9_xyO2CmkhazA','3bj3iol8WXZ_E$IfDiq2iw');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0kBoEfgQzCZwcAITqZnDkN','30ZfjXcBxYvLviWVoPKaTZ');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0kBoEfgQzCZwcAITqZnDkN','2cIAKBTC$saVOscKGMtzvK');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1AGXqM6FXE$PKWFpHb0tD1','14XKbgi6lo4sBH4l$_m3dX');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1AGXqM6FXE$PKWFpHb0tD1','0Uaigz52wuv1wvVn01sVyZ');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1q7DPgykr9lATuR9kfU1JJ','1T0WdnpDorHB3Wb7k0laKx');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1q7DPgykr9lATuR9kfU1JJ','029nZn9pWbYm6K36N_k9uN');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3a6hoiwS5ALQTYbFhAtpMx','1NsZOuLHAirGHtEWbykqn_');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3a6hoiwS5ALQTYbFhAtpMx','0B0V49K_gbJPJhaFO2XQxP');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0Aoj1Fkgn3UATZpBNlMNaf','3pZopONwSLwhwwW7xfHCNn');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0Aoj1Fkgn3UATZpBNlMNaf','24wY8D$KWFZM$r9u0uNr5u');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0NegscEpLBHfCO0cOvWvWD','2x1LdgE3PZ8IwG$DJaKll6');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0NegscEpLBHfCO0cOvWvWD','1pjT2JRDozz1g7jvGWSdvM');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('23IDpa5hfBCAToeuOPibhu','1EZlbLnOt0ALoBOSZlFIkC');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('23IDpa5hfBCAToeuOPibhu','3T0Ac4tYcnkccnetq5vnIU');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('11SSFTmvfAsh7uffkbAkHw','1L4tIi2aPIYh74ZuxZjE3J');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('11SSFTmvfAsh7uffkbAkHw','2Y2FlRwin7bA7a8S2nExbq');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3k4Z3diXzAWAnqMaC4UbXG','2zkVvjLvp0l9zdYu6k1u6j');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3k4Z3diXzAWAnqMaC4UbXG','1Z_aNVZuoYklbxNGrQBKbU');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3k4Z3diXzAWAnqMaC4UbXG','1gGXDdZklWOpI0pSWQBA70');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3k4Z3diXzAWAnqMaC4UbXG','1OmyC6JqQ55MwBYSwI8fiv');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3k4Z3diXzAWAnqMaC4UbXG','1aJ0yx11fT0n0fMX4BFFi_');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3k4Z3diXzAWAnqMaC4UbXG','2j1bbTYKr7be5pGvlQrwGU');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3k4Z3diXzAWAnqMaC4UbXG','09sskEgKOUAjtwNv$SJOOM');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('10T_URhX986PdE3NdBihco','3GAx8b1medHp4rF4VUj1Ii');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('10T_URhX986PdE3NdBihco','3UdpG9zqKGH6T23Q7Tvuzi');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('10T_URhX986PdE3NdBihco','1RDuS5TSLRls1jhj0K09_W');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('10T_URhX986PdE3NdBihco','05yIp9Q0yASdKakpVqU9Vn');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('10T_URhX986PdE3NdBihco','2zUSP6LPGYK_cd1XpdOraG');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('10T_URhX986PdE3NdBihco','32OwYg$u91bvqPhRFa4xgW');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('10T_URhX986PdE3NdBihco','1oIBe7Q_4wbL1EMHpytulg');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0bh_izAIvCGR4N2dD46iKk','3j45ziZgFw_jLZCfiTufdg');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0bh_izAIvCGR4N2dD46iKk','07ciTp5g35un1OzTCfCkmn');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1EAotCuNzD2w4dz5DcwpX_','0O8bNxMIe3zo48cKKUtyZU');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1EAotCuNzD2w4dz5DcwpX_','2GG0Ga6sYNZgp60c_8blPw');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3T7qMysCj85xrHCzTZnlNj','0ecfGuAg7aD4opEGdV5L8T');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3T7qMysCj85xrHCzTZnlNj','1f$QSG2Z9l_yxHSb$9a89g');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('060KlqT792Gu$HoedzYDFv','3_YDY$erOjuXrB2uKXsw7o');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('060KlqT792Gu$HoedzYDFv','0pp$t3OWF63e2PBlmohnmy');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('20qaS1_VH8IOJrYDQQgAEV','2STdQDomybBipWob336Xxj');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('20qaS1_VH8IOJrYDQQgAEV','1jVJMQwAfI$LNNE6vfGZw1');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('20qaS1_VH8IOJrYDQQgAEV','2ttUUrHl6T9aTOHzeOyjsO');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('20qaS1_VH8IOJrYDQQgAEV','0twGO1$Rg590turzq0mpOk');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('20qaS1_VH8IOJrYDQQgAEV','3LR5hU_kzENzec73b9olgz');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('20qaS1_VH8IOJrYDQQgAEV','19sxP40MORD5MBXT7oKH$F');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('20qaS1_VH8IOJrYDQQgAEV','1pinm96QV2Jc$L8t18GZNW');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('20qaS1_VH8IOJrYDQQgAEV','05J7cjSl2xvEyd4USt_xFk');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('20qaS1_VH8IOJrYDQQgAEV','2Q_3iLYecvHrgmPf2ZICrI');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('20qaS1_VH8IOJrYDQQgAEV','3OYNmF9G_aJel$hAklB140');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('20qaS1_VH8IOJrYDQQgAEV','0qBMh4oLdAh0xxpyKuSZJN');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0x2Ptqk7D5yQfXDXwRCLJk','0rKbt5sk8u$6Q4VUyZ3kvE');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0x2Ptqk7D5yQfXDXwRCLJk','0zAEmrIdxPrXoKR0qMTBRd');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0x2Ptqk7D5yQfXDXwRCLJk','2eLe4$5OiF18twvZhRsDi$');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0x2Ptqk7D5yQfXDXwRCLJk','11_ICKA2$hzUjUfthgrNLO');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0x2Ptqk7D5yQfXDXwRCLJk','1mk5gVwtHj2xjA4CuOMoRh');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0x2Ptqk7D5yQfXDXwRCLJk','3pVhgf26VqGJvaMt5LEJIk');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0x2Ptqk7D5yQfXDXwRCLJk','1hQLMJ9c3$9F5AIomsD3B6');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0x2Ptqk7D5yQfXDXwRCLJk','1c1F_eT8z7azhkU5N1U$u5');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0x2Ptqk7D5yQfXDXwRCLJk','3xHpBNnBdP1j0zwjjYYWyq');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0x2Ptqk7D5yQfXDXwRCLJk','3MkPbMTNkMW2LwUxAhwVyK');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0x2Ptqk7D5yQfXDXwRCLJk','1rDos4xTyos4Hc2n8fqooQ');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0NYuZC_Zn0zxU$8bSIn_dg','2phMQo3fr0RkqczaMY3E7l');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0NYuZC_Zn0zxU$8bSIn_dg','25qkYE2O_Rovyo97dDWd8E');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0NYuZC_Zn0zxU$8bSIn_dg','20QmCtk8QqY6Xmbcx4t3Jp');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0NYuZC_Zn0zxU$8bSIn_dg','1NKHO9AJfqODk$wbyvmkR1');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0NYuZC_Zn0zxU$8bSIn_dg','0oJGxVH49XTArgpbf6F3tn');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0NYuZC_Zn0zxU$8bSIn_dg','33RGzILwnhTVt_EhcVthpe');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0NYuZC_Zn0zxU$8bSIn_dg','3qe3foe4oA9MN6j6p_cnWB');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0NYuZC_Zn0zxU$8bSIn_dg','1Ws_sHRa98wpC7MnTKGtx7');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0NYuZC_Zn0zxU$8bSIn_dg','2alk$os2Qey$erWLCPMxKL');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0NYuZC_Zn0zxU$8bSIn_dg','2CITgOJYYFLVryyRV8Appa');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0NYuZC_Zn0zxU$8bSIn_dg','2sbJtwuzRI4zFAKhsgU7Yk');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1MobKlpi5FmRBwmIGJvVe7','2NwEYGlcoQLCPHiWYIs0xx');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1MobKlpi5FmRBwmIGJvVe7','2CDZUpdG_P_rjoBHyYb1G8');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1MobKlpi5FmRBwmIGJvVe7','16CdJeN$0C7uOS7CMfSU1L');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1MobKlpi5FmRBwmIGJvVe7','0B5cXkxxikDfoXXq1yZAKM');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1MobKlpi5FmRBwmIGJvVe7','02y74GahWjk37OrPzNqoz0');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1MobKlpi5FmRBwmIGJvVe7','3T7J24ssxjQwoCPg9FnnR4');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1MobKlpi5FmRBwmIGJvVe7','2izfyAsXF2cbWbWmuD92lq');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1MobKlpi5FmRBwmIGJvVe7','1iAocGjyJIz6gelkZPsz6g');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1MobKlpi5FmRBwmIGJvVe7','3$aN4MibAC_8Sd7su4u3NI');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1MobKlpi5FmRBwmIGJvVe7','2yIi7oLLw5JUxLULjFTdH_');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1MobKlpi5FmRBwmIGJvVe7','1tNmIpY8h5p3wFAYZUNoU4');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('18Dp7n99rCLBnu8_b3RxrR','3d$HOCkAI92hUpKLm1YS$9');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('18Dp7n99rCLBnu8_b3RxrR','2j4C2gfoH48Lou3nYyI1IX');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('18Dp7n99rCLBnu8_b3RxrR','1QG$NZI_pRC9hnBjgMiuCI');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('18Dp7n99rCLBnu8_b3RxrR','3xk0I6ff9k5XDIKUCmFVBq');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('18Dp7n99rCLBnu8_b3RxrR','1ANHP6RLa$6TWM6lGEZxor');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('18Dp7n99rCLBnu8_b3RxrR','0fd21RNJVb0r5LyQAPzxK6');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('18Dp7n99rCLBnu8_b3RxrR','04AK4lxqKdoEF6pYkUWdq7');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('18Dp7n99rCLBnu8_b3RxrR','16wFKmII3FYvA9Ii8CFRbZ');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('18Dp7n99rCLBnu8_b3RxrR','2ehVH$ybIPz3sGk_E6vMp8');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('18Dp7n99rCLBnu8_b3RxrR','16MKQNhrFR_3aQa9cWDO6M');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('18Dp7n99rCLBnu8_b3RxrR','0uzvBUWE7ztTfNfpc0FRtI');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3vD0BTagr0uhk85$J$0SBn','0k9Q8fxLJ8lYQVmCf_4ott');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3vD0BTagr0uhk85$J$0SBn','1uWiE0A125yBD4bcwGGZLq');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3OZhFtFq98_OiNVPZhex1v','1SrdEbgkBT4cvB_Y$8fKx7');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3OZhFtFq98_OiNVPZhex1v','2dmbkqbVGtdxVSE4R86yxh');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3OZhFtFq98_OiNVPZhex1v','2fQpid431umFyBWWRKv4z1');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3OZhFtFq98_OiNVPZhex1v','1X9sHhMerugCzWWuxSUdLf');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3OZhFtFq98_OiNVPZhex1v','3PQb4NZ3RM8C7jEOvUSFzn');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3OZhFtFq98_OiNVPZhex1v','2n4BGS2QrdG4V9LUZ$J6$A');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3OZhFtFq98_OiNVPZhex1v','1hPd$LyQLap8hsUz1bD6At');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3OZhFtFq98_OiNVPZhex1v','2I5lLMycJJpx1gQFOpazGW');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3OZhFtFq98_OiNVPZhex1v','3iZAQzYTcB2jl_SOxdH9uN');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3OZhFtFq98_OiNVPZhex1v','1pYYQsxBuTA$unMxg3hbRp');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3OZhFtFq98_OiNVPZhex1v','3W3XMybgk56LqlJxeyLy2K');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('03smbr_9zFUvoPc7iSmcEW','0krrSL5sE0QMpG0pB0FlU9');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('03smbr_9zFUvoPc7iSmcEW','3S966vAVkktCd6ePv5nLIh');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('03smbr_9zFUvoPc7iSmcEW','2jS$PS1YId9BWrC$etkQI7');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('03smbr_9zFUvoPc7iSmcEW','1esPqM6wE6oIAoIIjPO0zh');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('03smbr_9zFUvoPc7iSmcEW','2e4qnow0uKEgJ3TEVp4syl');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('03smbr_9zFUvoPc7iSmcEW','1$opBhHNmuUuU5xzwOwJTn');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('03smbr_9zFUvoPc7iSmcEW','0BmpNmwukKJPd8jhXFlbF7');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('03smbr_9zFUvoPc7iSmcEW','121F3_NrjoQ6dPmfHyyp_I');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('03smbr_9zFUvoPc7iSmcEW','0Har63Eq8agR6xryIQkTwX');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('03smbr_9zFUvoPc7iSmcEW','2XEN$w$EDuGb1TPBZ8M0fM');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('03smbr_9zFUvoPc7iSmcEW','3fNHHxiZLVFzcYMhER$217');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2UvMAz_eX4de4Cch8tic9z','2wDZ$fWVOfmq4NIm_hmrXP');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2UvMAz_eX4de4Cch8tic9z','0a_7UNQR$vb5zYkUyt$6fB');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2UvMAz_eX4de4Cch8tic9z','0DmgQGVEXejKPofddr334h');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2UvMAz_eX4de4Cch8tic9z','2PFSoDuaSWNUrIDIDQZcVq');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2UvMAz_eX4de4Cch8tic9z','2VB_odRDpVf7Cj40ydy2b_');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2UvMAz_eX4de4Cch8tic9z','31LcEJODsZGW4PS2ECY7H3');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2UvMAz_eX4de4Cch8tic9z','3YXHEH8xpKhozaX4ZJsCk7');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2UvMAz_eX4de4Cch8tic9z','32UthF7rKWMBcBiE9mbYRy');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2UvMAz_eX4de4Cch8tic9z','32qJPWsn0FJZ$5cmeSH8ui');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2UvMAz_eX4de4Cch8tic9z','0yKYMfD5cevhsdmvUQpAyL');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2UvMAz_eX4de4Cch8tic9z','2GAgWJi$iKJ13ASDck7Xpw');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2HxXb1h3n16BOCoDJT05OM','1KzHGpkxGGN7aIyB3yQAlS');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2HxXb1h3n16BOCoDJT05OM','2R6aacDqxAY4qBzYTx1Ztp');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2HxXb1h3n16BOCoDJT05OM','1YAN0i3f3ElcHZNjJtSO_a');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2HxXb1h3n16BOCoDJT05OM','1s5AgAVUEve6nXK5I7YnAK');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2HxXb1h3n16BOCoDJT05OM','3rzStU6x4NqMPhqJG8i4JY');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2HxXb1h3n16BOCoDJT05OM','0M5smZ7ne4sA_Fj7JhVFP7');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2HxXb1h3n16BOCoDJT05OM','117W45p4g_rmdt16SvIlE6');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2HxXb1h3n16BOCoDJT05OM','0iKX7wrTELHBnET8da7YKF');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2HxXb1h3n16BOCoDJT05OM','3LXRZ3PDZ9$k41Tz2teWXf');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2HxXb1h3n16BOCoDJT05OM','27HI$FeJFJ_G1aNZKQqnLZ');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2HxXb1h3n16BOCoDJT05OM','3eYYBSP3JccT9HZVg9q2e$');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2jqRiK6lr5dgbYAtO7O9PM','0PykvjAF2nnRAlL8DX7hio');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2jqRiK6lr5dgbYAtO7O9PM','1Yl2nwuTyNmfCR5YYrABZ$');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2jqRiK6lr5dgbYAtO7O9PM','3$DVYFiE_2DGd6swaKtHHh');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2jqRiK6lr5dgbYAtO7O9PM','1kAgfoaS3IrPCb6kK09dGe');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2jqRiK6lr5dgbYAtO7O9PM','1rvzb9w048VWKs$fazh$jH');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2jqRiK6lr5dgbYAtO7O9PM','3K7Vajr85AISJA9A9mNvuA');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2jqRiK6lr5dgbYAtO7O9PM','0367gNZN8J6XGpko84gXRH');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2jqRiK6lr5dgbYAtO7O9PM','0ZQs3nc_LFVKKeF7e2QHn3');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2jqRiK6lr5dgbYAtO7O9PM','3bmyajEOHPOwnaL9sydha$');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2jqRiK6lr5dgbYAtO7O9PM','17O25ORY6_PHNbY4o8cipa');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2jqRiK6lr5dgbYAtO7O9PM','1tdA_EPTEwcluJVSGkyUPl');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0lF5MOhTPBxPrLOQzM_gU0','31rKdxEidDN0edWHvtZFL1');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0lF5MOhTPBxPrLOQzM_gU0','1mWq1ZwuC0Qm36y5jJfn4s');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2LWjDdCajEqx6y3aO2HdiR','3YHv2gkSiv$7TyJDsP7Nqg');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2LWjDdCajEqx6y3aO2HdiR','2HjONyGuONr_xpOP7OVxW9');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3KwtARMrX7SOZcscyIrGyC','1dTbj3mRekp3FJ09QAq2dF');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3KwtARMrX7SOZcscyIrGyC','3QJwa8mODZ0miqwtcV5_OR');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('03pWrikv57TvJ6ZuhGktHh','3dDJsJFO_OZbZEVuFDHe5Y');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('03pWrikv57TvJ6ZuhGktHh','00NDnS7S4XpPOkRoWOC1Fw');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2luRa0gbH7jxkpjjSUl3pE','3a1XjPa1TF3vu_tHyeSYZv');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2luRa0gbH7jxkpjjSUl3pE','3ItkcLc5kuOvUQ5pIcg6gS');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1L540sTSbBmBcA50ERiYup','0WeZ97whRZvTOL46e0eF$E');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1L540sTSbBmBcA50ERiYup','3$VTIuFYs2tsQr$pBxygqL');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0_FtwVBcH6BQrvFHbzx1Dk','0hJUZyS9wKjo_5z8snKlOP');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0_FtwVBcH6BQrvFHbzx1Dk','3UpWH9vT4pKbE$Q1p$K2qi');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0c9IdEzTz61uKg3zrEBJVm','18mOF3LGLSonZywkOjXdIc');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0c9IdEzTz61uKg3zrEBJVm','2rXlXcHhAzBlqGl0NV7Q3F');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0c9IdEzTz61uKg3zrEBJVm','2Fs0q0YBUSeyg13AOWYkaE');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0c9IdEzTz61uKg3zrEBJVm','2ofjikBVKVKJC2xePQqaNR');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0c9IdEzTz61uKg3zrEBJVm','2IXekg6nqfinwGMnVEb47i');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0c9IdEzTz61uKg3zrEBJVm','2iogjXEUnYH2A8rt0evQ18');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0c9IdEzTz61uKg3zrEBJVm','0YOZZ4F5Yx5u$Brw1Kh53a');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0c9IdEzTz61uKg3zrEBJVm','2Mh9HbwrcVACK8sCqNp3wB');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1CPapQAlf4YQ_ggfHZhkiy','28sG7FAd3NEMBAs6CBbZl7');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1CPapQAlf4YQ_ggfHZhkiy','2lh7hYzxWgqznLFZfEP4Gn');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1CPapQAlf4YQ_ggfHZhkiy','1u5LcZAk5_IoT8AQc6jbri');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1CPapQAlf4YQ_ggfHZhkiy','07OdeefT1FDAtUXwyB3i3t');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1CPapQAlf4YQ_ggfHZhkiy','0ag9ckb5kGQyUyBo7_pa46');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1CPapQAlf4YQ_ggfHZhkiy','1f3LE27ZEG1QWNN6yq7oEe');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1CPapQAlf4YQ_ggfHZhkiy','0LKrcTbwwSnZlXoCMt_i4v');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1CPapQAlf4YQ_ggfHZhkiy','2otbi1sE71MnsLAoBkuDrh');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0vzoXh8HfE39$x$uEJYJop','1cYxlZ_cLXUaohauK8PY7l');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0vzoXh8HfE39$x$uEJYJop','1y137bqHDER8Yw8UwltVnx');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0vzoXh8HfE39$x$uEJYJop','20OfIMEfyxhknDcV7YT6iK');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0vzoXh8HfE39$x$uEJYJop','0gJmLMrXz8vTQUQkJAgFI9');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0vzoXh8HfE39$x$uEJYJop','2OZKKdreemYHMrAjDqluWU');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0vzoXh8HfE39$x$uEJYJop','0tpyXs70f6Hm21wv41FQwQ');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0vzoXh8HfE39$x$uEJYJop','0O2iZKf5CunUxTfRmadCaX');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0vzoXh8HfE39$x$uEJYJop','1PYsGh7IFKtNQ7csl0m$m8');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3nJZgUzE597eilBObAKJsS','3J5FWU4elHDErEK4BNqCIn');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3nJZgUzE597eilBObAKJsS','2SHvc$8U8cJSnQUCSt4zOj');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3nJZgUzE597eilBObAKJsS','3cMQfcVmbMHmmIGzFW6KXs');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3nJZgUzE597eilBObAKJsS','2$WAnIUvSuYSABwr$wMilZ');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3nJZgUzE597eilBObAKJsS','0piDoyjeO5MD6UbLVtaoqj');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3nJZgUzE597eilBObAKJsS','0JA5tiqDaMMHJGz7gsAQsI');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3nJZgUzE597eilBObAKJsS','3$fUwXkP73TyInjVZk78D4');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3nJZgUzE597eilBObAKJsS','2WBMs31k6sK1DmFcFDJOTE');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2GynMxLJb7Ve_WEsuAUB$o','1ER3lsoq12ZNahd9n5$CrF');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2GynMxLJb7Ve_WEsuAUB$o','3g4neeJkSLeq1OeVmLT4ma');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2GynMxLJb7Ve_WEsuAUB$o','0mCklXgNQgXxyBlAPHx_oN');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2GynMxLJb7Ve_WEsuAUB$o','2q5VX7kPjqCI_S8vB2W7Lw');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2GynMxLJb7Ve_WEsuAUB$o','2sqs_PC_DUNkfahjKhNrVn');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2GynMxLJb7Ve_WEsuAUB$o','2bVS2a5OHqwzTNVPZO_XjO');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2GynMxLJb7Ve_WEsuAUB$o','2GhzLKsnBfWRoIazi9QV9K');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2GynMxLJb7Ve_WEsuAUB$o','0AQYVeJRmaEEN6HaaMIwgQ');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3Y0AN$7uH9RhdeNNvTVRg$','1l_iz__psaWP0eu89aSMAb');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3Y0AN$7uH9RhdeNNvTVRg$','1SNxIz7qHVNriBXkl1vnvJ');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3Y0AN$7uH9RhdeNNvTVRg$','0WwGozUzyX1WMgI$ZqJqWI');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3Y0AN$7uH9RhdeNNvTVRg$','0et2DhFnlWYCUJMeeYG9eB');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3Y0AN$7uH9RhdeNNvTVRg$','2hIeC$OBG$x6M0wcBA2fSL');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3Y0AN$7uH9RhdeNNvTVRg$','1MXEmih1HiYxLInmQ$Brqw');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3Y0AN$7uH9RhdeNNvTVRg$','0pOLFg$sxlV8R02BgnpQOp');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3Y0AN$7uH9RhdeNNvTVRg$','0_lUiRLEfX5rPQpQF2juDU');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('043PX6AOf83xoc4Zbos9VV','3tGEskOtXQZ7VRzJuH0rru');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('043PX6AOf83xoc4Zbos9VV','2WdrTQAqFnbxwYMyHKx9Uo');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('043PX6AOf83xoc4Zbos9VV','3PlpcHG8InoInlCYdNiNLp');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('043PX6AOf83xoc4Zbos9VV','0Z3iroS1TPhMjYZYL0grSb');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('043PX6AOf83xoc4Zbos9VV','0G1xDd6ah5loD9GYkzLa9p');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('043PX6AOf83xoc4Zbos9VV','2l8iCW95Y9XcTOL6JaxWf9');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('043PX6AOf83xoc4Zbos9VV','16wrRvcRZvXFZ8sqA22g$d');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('043PX6AOf83xoc4Zbos9VV','0wmJeGlhlhrV4NRs1eYpAP');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3hhiC8yEn2tx0W6$uE_WXb','02htwID3$qG5GnU4vUssTS');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3hhiC8yEn2tx0W6$uE_WXb','2X49HOwvz8I7nPj12uu6Z7');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3hhiC8yEn2tx0W6$uE_WXb','2LNpbHDlhtSyLe4eu6Ejix');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3hhiC8yEn2tx0W6$uE_WXb','1BRLFVhH$xZpZLgctzxArl');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('3hhiC8yEn2tx0W6$uE_WXb','3uGiNLp8SptPZN5SlbJ2yy');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2vp_usBx12Y9PoQVOVdAFF','2nogX_lG7Dc4IFSUSW32EO');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2vp_usBx12Y9PoQVOVdAFF','3UVOpzaJqHLY8F8cJ7UQmO');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2vp_usBx12Y9PoQVOVdAFF','1HLwjOEY62yqE3n2S0LNfP');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2vp_usBx12Y9PoQVOVdAFF','2$Q1Yc_pnWB_ta97sCo5k_');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2vp_usBx12Y9PoQVOVdAFF','03AaV8WilE56W1UUxh178E');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2mZ5fvqSj1euAdxjC9HqAB','3FzaF6KwvZP4Qh2p8mNpAt');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2mZ5fvqSj1euAdxjC9HqAB','1V0$CnAl$cNdjOxAvcEKXY');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2mZ5fvqSj1euAdxjC9HqAB','1CAOP0SwJEIY3Fvbj7TsKV');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2mZ5fvqSj1euAdxjC9HqAB','25eO2P2MHvEk$4o$gN3g0Z');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2mZ5fvqSj1euAdxjC9HqAB','1HSv11bmtt33hB6fh5Cmdm');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2mZ5fvqSj1euAdxjC9HqAB','3oQLzuKPOWeeBI0ZtY4dKb');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2mZ5fvqSj1euAdxjC9HqAB','3YYC7KhbRMWqV7tV$wJ9D_');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2mZ5fvqSj1euAdxjC9HqAB','1H7OKx8FJ3mrqL2jAFxXCi');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0ObAt5weD2MxClwOERiQnw','1WXSa$kzB5whNvSZdceHqb');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0ObAt5weD2MxClwOERiQnw','2EaL2fu69uFL2V4emrYEZl');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0ObAt5weD2MxClwOERiQnw','3qC5XxtUwn4b0yQh_s8DD7');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0ObAt5weD2MxClwOERiQnw','0nNS2Z1$Qpb1CgpIA5akc$');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0ObAt5weD2MxClwOERiQnw','0MKMg6PeC4vrBpYriQUkvu');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0ObAt5weD2MxClwOERiQnw','2ZzOsFdTouX1hlqaiXDshG');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0ObAt5weD2MxClwOERiQnw','1CkeQx$QxjepOTt$DYK7Yd');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0ObAt5weD2MxClwOERiQnw','0vBfDjxo_YnC0buTWZDnmh');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0ObAt5weD2MxClwOERiQnw','063iSjgHW4qGcye4jHVic0');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0ObAt5weD2MxClwOERiQnw','3GitlOVky8HpLsCgNPDqjw');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0ObAt5weD2MxClwOERiQnw','06lPIuxu504UUSPYpzF22G');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0ObAt5weD2MxClwOERiQnw','2x9nT54ROTbWN83etFe8h5');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2Oyl7MsmPBX8QuVAq0wJYB','3pPw$Ov7Nj_yizdko4OJeC');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2Oyl7MsmPBX8QuVAq0wJYB','0yIuibAacv$mKmwg_Opb5q');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2Oyl7MsmPBX8QuVAq0wJYB','2wpWNyYJCzQYHuiez7jPMy');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2Oyl7MsmPBX8QuVAq0wJYB','0XxAX454i8rl8olZKyftFg');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('2Oyl7MsmPBX8QuVAq0wJYB','05WxPljinrRPusR$K5IzJQ');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0Zx4cqrajBR8O5_p97fE50','13vrbEFLPZhvkVt8ICakBz');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0Zx4cqrajBR8O5_p97fE50','3w_4Nr3qZzmOMpdUU6L883');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0Zx4cqrajBR8O5_p97fE50','39QCUfvE2lRxFvdhJZ_21I');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0Zx4cqrajBR8O5_p97fE50','1AYGVmRisrlSWYzis10EIo');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('0Zx4cqrajBR8O5_p97fE50','12oGX$FFPmcDIJNCurND0g');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1k4Rf11O17$OYfDaxGxz3e','0AcBr5seiftVMT528mMvOS');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1k4Rf11O17$OYfDaxGxz3e','0wF7OJTFuyvR15syOeIbP$');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1k4Rf11O17$OYfDaxGxz3e','3VUYP1sjpXnoI4akvffbMR');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1k4Rf11O17$OYfDaxGxz3e','27nlhYDWXUPqULKwIMe6fj');
INSERT OR IGNORE INTO rel_aggregates (parent_guid,child_guid) VALUES ('1k4Rf11O17$OYfDaxGxz3e','1z6qVYSgqwnLAoDR_QS$VU');
