-- SampleHouse_ARC.db rel_fills_host — the authored host<->opening<->filling chain (§PATHB).
-- Self-heal patch. Generated by scripts/gen_rel_fills_host_patch.py (bim-compiler) — regenerate,
-- do not hand-edit. Recovery is extractIFCtoDB.py extract_rel_fills_host(), the ONE implementation.
--
-- Source: Ifc4_SampleHouse.ifc   Generated: 2026-07-28
-- Recovered VERBATIM from the source IFC's own IfcRelVoidsElement/IfcRelFillsElement:
--   7 host edges, 7 with a door/window filling, 0 open voids.
-- provenance='ifc:recovered' on every row. Nothing derived, nothing proximity-guessed.
--
-- WHY: sdg_cascade.js stretchRide() is guarded on window.swXEdges.fills (bonsai_gridmove.js:249)
-- which reads this table (cross_edges.js:251). Without it a hosted door/window does NOT ride its
-- wall on a Grid-Stretch — the cascade silently no-ops. docs/ModellerGuide.md documents the ride.
--
-- MEASURED REACH on this exact target: 7/7 fills have BOTH ends present as scene
-- features (a host with no element_instances row never becomes a feature, so that edge is skipped).
--
-- Idempotent: CREATE IF NOT EXISTS + INSERT OR IGNORE on the opening_guid PRIMARY KEY, so the
-- loader re-applying it on every open is a no-op.
CREATE TABLE IF NOT EXISTS rel_fills_host (
    opening_guid TEXT PRIMARY KEY,
    host_guid TEXT,
    filling_guid TEXT,
    host_class TEXT,
    filling_class TEXT,
    provenance TEXT DEFAULT 'ifc:recovered'
);
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3cUkl32yn9qRSPvAVVyWYp','3cUkl32yn9qRSPvBJVyWy4','3cUkl32yn9qRSPvBJVyWYp','IfcWall','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3cUkl32yn9qRSPvAVVyWaG','3cUkl32yn9qRSPvBJVyWXt','3cUkl32yn9qRSPvBJVyWaG','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3cUkl32yn9qRSPvAVVyWax','3cUkl32yn9qRSPvBJVyWXt','3cUkl32yn9qRSPvBJVyWax','IfcWallStandardCase','IfcDoor','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3cUkl32yn9qRSPvAVVyWcE','3cUkl32yn9qRSPvBJVyWw5','3cUkl32yn9qRSPvBJVyWcE','IfcWall','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3cUkl32yn9qRSPvAVVyWdx','3cUkl32yn9qRSPvBJVyWw5','3cUkl32yn9qRSPvBJVyWdx','IfcWall','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3cUkl32yn9qRSPvAVVyWe9','3cUkl32yn9qRSPvBJVyWw5','3cUkl32yn9qRSPvBJVyWe9','IfcWall','IfcWindow','ifc:recovered');
INSERT OR IGNORE INTO rel_fills_host (opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ('3cUkl32yn9qRSPvAVVyZTO','3cUkl32yn9qRSPvBJVyWy4','3cUkl32yn9qRSPvBJVyZTO','IfcWall','IfcWindow','ifc:recovered');
