/**
 * BIM OOTB — RouteWalker JS (ported from RouteWalker.java)
 * Copyright (c) 2025-2026 Redhuan D. Oon <red1org@gmail.com>
 * SPDX-License-Identifier: MIT
 *
 * Port of DAGCompiler/src/main/java/com/bim/compiler/mep/RouteWalker.java
 * Reads MEP recipes from mep_rw.db (sidecar, cached via IndexedDB).
 * Writes RW2D-prefixed elements into the building's extracted DB.
 *
 * Data chain:
 *   mep_rw.db: ad_space_type → ad_space_type_mep_bom → ad_placement_offset → _shim_attributes
 *   mep_rw.db: ad_mep_pattern (CW/SP topology) + ad_mep_anchor (known buildings)
 *   building DB: elements_meta + element_transforms (read ARC envelope, write MEP)
 *
 * Session isolation: this file is NEW. Does not edit any existing file.
 * GUID prefix: RW2D- (never collides with IFC-extracted or Java RW- elements)
 */

// ─── Constants ───────────────────────────────────────────────
var RW_PREFIX = 'RW2D-';
var MEP_RW_DB_URL = 'mep_rw.db?v=2';  // relative to viewer, or full OCI URL (?v busts the IDB cache when the db data changes — v2 adds building_room)
var RW_PIPE_NOMINAL_MM = 50;
var RW_PIPE_CROSS = RW_PIPE_NOMINAL_MM * 1.5;  // bbox cross-section
var RW_MAX_PAIR_DIST = 50.0;  // metres — skip pairs > 50m apart
var RW_ARC_CLASH_TOL = -0.01; // metres — pipes may touch walls but not penetrate
var RW_WALL_SNAP_MAX = 1.5;   // metres — a wall-host fixture snaps onto a real wall within this; else keeps nominal

// ─── MEP product → IFC class mapping ────────────────────────
var RW_IFC_MAP = {
  TOILET:         { cls: 'IfcFlowTerminal',    disc: 'PLB', rgba: '0,119,190,255' },
  SINK:           { cls: 'IfcFlowTerminal',    disc: 'PLB', rgba: '0,119,190,255' },
  FLOOR_TRAP:     { cls: 'IfcFlowTerminal',    disc: 'PLB', rgba: '0,119,190,255' },
  WASHING_MACHINE_TAP: { cls: 'IfcFlowTerminal', disc: 'PLB', rgba: '0,119,190,255' },
  OUTLET:         { cls: 'IfcOutlet',          disc: 'ELEC', rgba: '255,200,0,255' },
  OUTLET_GFCI:    { cls: 'IfcOutlet',          disc: 'ELEC', rgba: '255,200,0,255' },
  LIGHT:          { cls: 'IfcLightFixture',    disc: 'ELEC', rgba: '255,220,100,255' },
  SWITCH:         { cls: 'IfcSwitchingDevice', disc: 'ELEC', rgba: '255,200,0,255' },
  EXHAUST_FAN:    { cls: 'IfcFan',             disc: 'ACMV', rgba: '100,200,255,255' },
  SPRINKLER:      { cls: 'IfcFlowTerminal',    disc: 'FP',   rgba: '255,80,80,255' },
  AIRCON_POINT:   { cls: 'IfcUnitaryEquipment',disc: 'ACMV', rgba: '100,200,255,255' },
  DATA_POINT:     { cls: 'IfcCommunicationsAppliance', disc: 'ELEC', rgba: '180,180,255,255' },
  CEILING_FAN:    { cls: 'IfcFan',             disc: 'ACMV', rgba: '120,210,255,255' },
  SUPPLY_DIFFUSER:{ cls: 'IfcAirTerminal',     disc: 'ACMV', rgba: '150,220,255,255' },
  EMERGENCY_LIGHT:{ cls: 'IfcLightFixture',    disc: 'ELEC', rgba: '120,255,120,255' },
  OUTLET_20A:     { cls: 'IfcOutlet',          disc: 'ELEC', rgba: '255,200,0,255' },
  WASHING_TAP:    { cls: 'IfcFlowTerminal',    disc: 'PLB',  rgba: '0,119,190,255' },
  FRIDGE:         { cls: 'IfcElectricAppliance',disc: 'ELEC', rgba: '200,200,200,255' },
  // Pipe segments generated by walker
  PIPE_CW:        { cls: 'IfcPipeSegment',     disc: 'PLB', rgba: '0,119,190,255' },
  PIPE_SP:        { cls: 'IfcPipeSegment',     disc: 'PLB', rgba: '139,90,43,255' },
  // Defaults
  _DEFAULT:       { cls: 'IfcBuildingElementProxy', disc: 'MEP', rgba: '180,180,180,255' }
};

// ─── Module state ────────────────────────────────────────────
var _rwDb = null;      // sql.js instance for mep_rw.db
var _rwReady = false;
var _rwGuidCounter = 0;

// ═══════════════════════════════════════════════════════════════
// PUBLIC API
// ═══════════════════════════════════════════════════════════════

/**
 * Initialise RouteWalker: fetch mep_rw.db, open as sql.js instance.
 * Call once at page load. Caches in IndexedDB (same pattern as building DB).
 * @param {object} SQL - initSqlJs result (sql.js factory)
 * @param {string} [baseUrl] - base URL for mep_rw.db (default: relative)
 * @returns {Promise<boolean>} true if ready
 */
async function rwInit(SQL, baseUrl) {
  if (_rwReady) return true;
  var url = (baseUrl || '') + MEP_RW_DB_URL;
  try {
    var buf = await _rwFetchCached(url);
    _rwDb = new SQL.Database(new Uint8Array(buf));
    _rwReady = true;
    var counts = _rwDb.exec(
      "SELECT (SELECT COUNT(*) FROM ad_space_type_mep_bom) as bom, " +
      "(SELECT COUNT(*) FROM ad_mep_pattern) as pat, " +
      "(SELECT COUNT(*) FROM ad_mep_anchor) as anc, " +
      "(SELECT COUNT(*) FROM ad_placement_offset) as off, " +
      "(SELECT COUNT(*) FROM _shim_attributes) as shim, " +
      "(SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='arc_envelope') as has_arc"
    );
    var r = counts[0].values[0];
    console.log('§RW_INIT mep_rw.db loaded bom=' + r[0] + ' patterns=' + r[1] +
                ' anchors=' + r[2] + ' offsets=' + r[3] + ' shims=' + r[4] + ' arc_env=' + r[5]);
    return true;
  } catch (e) {
    console.warn('§RW_INIT_FAIL ' + e.message);
    return false;
  }
}

/**
 * Run RouteWalker on a building DB.
 * Path A: building has anchors in mep_rw.db → use Java-style pattern walk
 * Path B: building has no anchors → generate from room BOM recipes + placement offsets
 *
 * @param {object} buildingDb - sql.js Database instance (building's extracted DB)
 * @param {string} buildingName - building name (matches source_building in anchors)
 * @param {object} [opts] - { rooms: [{id,type,storey,bbox}], forceRegen: false }
 * @returns {object} { fixtures, pipes, clashSkipped, total }
 */
function rwWalk(buildingDb, buildingName, opts) {
  if (!_rwReady) { console.warn('§RW_WALK_FAIL not initialised'); return null; }
  opts = opts || {};
  _rwGuidCounter = 0;

  // Resolve actual building name from DB (may differ from ERP anchor key)
  var dbBldName = buildingName;
  try {
    var bldRow = buildingDb.exec("SELECT DISTINCT building FROM elements_meta LIMIT 1");
    if (bldRow.length && bldRow[0].values.length) dbBldName = bldRow[0].values[0][0];
  } catch (e) { /* use passed name */ }

  // Clean previous RW2D- elements (idempotent re-run)
  try {
    buildingDb.run("DELETE FROM elements_meta WHERE guid LIKE 'RW2D-%'");
    buildingDb.run("DELETE FROM element_transforms WHERE guid LIKE 'RW2D-%'");
  } catch (e) { /* tables may not exist yet */ }

  // Load ARC envelope from building DB for clash checking
  var arcEnvelope = _rwLoadArcEnvelope(buildingDb);

  // Check if this building has pre-mined anchors (try exact name, then fuzzy)
  var anchorKey = _rwFindAnchorKey(buildingName, dbBldName);
  var hasAnchors = anchorKey !== null;

  var result = { fixtures: 0, pipes: 0, clashSkipped: 0, total: 0, fixturesRefused: 0 };

  if (hasAnchors && !opts.forceRegen) {
    // Path A: pattern walk using pre-mined anchors (Java port)
    console.log('§RW_PATH_A building=' + buildingName + ' anchorKey=' + anchorKey);
    var patResult = _rwPatternWalk(buildingDb, anchorKey, arcEnvelope);
    result.pipes = patResult.cwLines + patResult.spLines;
    result.clashSkipped = patResult.clashSkipped;
  }

  // Path B: room-based BOM placement (always runs — adds fixtures)
  // Uses dbBldName for DB queries (the actual building column value)
  var rooms = opts.rooms || _rwDetectRooms(buildingDb, dbBldName);
  if (rooms.length > 0) {
    console.log('§RW_PATH_B building=' + dbBldName + ' rooms=' + rooms.length);
    var bomResult = _rwPlaceFromBOM(buildingDb, dbBldName, rooms, arcEnvelope);
    result.fixtures += bomResult.placed;
    result.fixturesRefused += (bomResult.refused || 0);

    // If no pre-mined anchors, also generate pipe runs from placed fixtures
    if (!hasAnchors || opts.forceRegen) {
      var pipeResult = _rwConnectFixtures(buildingDb, dbBldName, arcEnvelope);
      result.pipes += pipeResult.pipes;
      result.clashSkipped += pipeResult.clashSkipped;
    }
  }

  result.total = result.fixtures + result.pipes;
  console.log('§RW_WALK building=' + buildingName + ' fixtures=' + result.fixtures +
              ' fixturesRefused=' + result.fixturesRefused +
              ' pipes=' + result.pipes + ' clashSkipped=' + result.clashSkipped +
              ' total=' + result.total);
  return result;
}


/**
 * Find anchor key in mep_rw.db for this building.
 * Tries exact match, then fuzzy (DB name contains anchor key or vice versa).
 * e.g. DB has 'Ifc2x3_Duplex_Architecture', anchors keyed as 'Duplex' → match.
 */
function _rwFindAnchorKey(buildingName, dbBldName) {
  // Get all source_building values from anchors
  var rows = _rwDb.exec("SELECT DISTINCT source_building FROM ad_mep_anchor");
  if (!rows.length) return null;
  var keys = rows[0].values.map(function(v) { return v[0]; });

  // Exact match
  if (keys.indexOf(buildingName) >= 0) return buildingName;
  if (keys.indexOf(dbBldName) >= 0) return dbBldName;

  // Fuzzy: anchor key is substring of DB name or vice versa
  var candidates = [buildingName, dbBldName];
  for (var c = 0; c < candidates.length; c++) {
    var name = candidates[c].toUpperCase();
    for (var i = 0; i < keys.length; i++) {
      var key = keys[i].toUpperCase();
      if (name.indexOf(key) >= 0 || key.indexOf(name) >= 0) {
        console.log('§RW_ANCHOR_MATCH fuzzy "' + candidates[c] + '" → "' + keys[i] + '"');
        return keys[i];
      }
    }
  }
  return null;
}

// ═══════════════════════════════════════════════════════════════
// EMIT SEAM: route SEGMENTS (endpoint polylines) for the op-log modeller
// ═══════════════════════════════════════════════════════════════
//
// The modeller is op-log-native (no building DB). Instead of inserting RW2D- rows
// it emits one signed GEOM_SWEEP per pipe run. GEOM_SWEEP needs an explicit polyline
// path (from→to), which the proven _rwApplyPattern collapses into midpoint+bbox.
// rwRouteSegments mirrors the SAME proven pairing (pattern topology + nearest-neighbour
// + clash gate) but RETURNS the endpoint pairs instead of writing — the bridge between
// the routed MEP and GEOM_SWEEP. The insert path above is left untouched (revert-safe).
//
// Each segment: { disc:'CW'|'SP', storey, axis, from:[x,y,z], to:[x,y,z], len }
// Caller maps each to a GEOM_SWEEP op (2-point path, pipe profile RW_PIPE_NOMINAL_MM).
function rwRouteSegments(buildingDb, buildingName, opts) {
  if (!_rwReady) { console.warn('§RW_SEG_FAIL not initialised'); return []; }
  opts = opts || {};
  // Op-log modeller has NO building DB — pass buildingDb=null + opts.arcEnvelope (or none).
  var dbBldName = buildingName;
  if (buildingDb) {
    try {
      var bldRow = buildingDb.exec("SELECT DISTINCT building FROM elements_meta LIMIT 1");
      if (bldRow.length && bldRow[0].values.length) dbBldName = bldRow[0].values[0][0];
    } catch (e) { /* use passed name */ }
  }

  var anchorKey = _rwFindAnchorKey(buildingName, dbBldName);
  if (anchorKey === null) { console.log('§RW_SEG no anchors for ' + buildingName); return []; }
  // Load ARC envelope: explicit > from building DB > from mep_rw.db arc_envelope table (modeller path)
  var arcEnvelope = (opts.arcEnvelope !== undefined)
    ? opts.arcEnvelope
    : (buildingDb ? _rwLoadArcEnvelope(buildingDb) : _rwLoadArcEnvelopeFromDb(anchorKey));

  var segments = [];
  ['CW', 'SP'].forEach(function (disc) {
    var steps = _rwLoadPatternSteps(disc, anchorKey);
    if (!steps.length) return;
    _rwPairSegments(disc, steps, _rwLoadAnchors(anchorKey), arcEnvelope, segments);
  });

  console.log('§RW_SEG building=' + buildingName + ' segments=' + segments.length +
    ' CW=' + segments.filter(function (s) { return s.disc === 'CW'; }).length +
    ' SP=' + segments.filter(function (s) { return s.disc === 'SP'; }).length);
  return segments;
}

// Map route segments → modeller GEOM_SWEEP commit payloads (the op-log emit).
// Each payload: { op_type:'GEOM_SWEEP', parameters:{ profile:{w,h}, path:[from,to] }, _rw:{disc,storey} }.
// opts: { translate:[tx,ty,tz] (drop transform applied to both endpoints, default 0),
//         profileM (pipe cross-section in metres, default RW_PIPE_NOMINAL_MM/1000),
//         limit (cap the number of ops emitted — occt pipe is costly; default all) }.
// Pure: no DB, no commit — caller feeds each payload to window.Bonsai.oplog.commit().
function rwSweepOps(segments, opts) {
  opts = opts || {};
  var t = opts.translate || [0, 0, 0];
  var pw = (opts.profileM != null) ? opts.profileM : (RW_PIPE_NOMINAL_MM / 1000);
  var segs = (opts.limit != null && opts.limit < segments.length) ? segments.slice(0, opts.limit) : segments;
  return segs.map(function (s) {
    return {
      op_type: 'GEOM_SWEEP',
      parameters: {
        profile: { w: pw, h: pw },
        path: [
          [s.from[0] + t[0], s.from[1] + t[1], s.from[2] + t[2]],
          [s.to[0] + t[0], s.to[1] + t[1], s.to[2] + t[2]]
        ]
      },
      _rw: { disc: s.disc, storey: s.storey, axis: s.axis }
    };
  });
}

// Align anchor-space route segments to a WORLD-placed building (the auto-emit-on-drop transform).
// The dropped building's STRUCTURAL leaves are in modeller world space; its MEP anchors are in extraction
// space. Both are the SAME building at 1:1 metres, so map the anchor bbox-min → the placed-leaf bbox-min,
// + an optional yaw about +Z (the drop rotation). Returns segments with world-space from/to.
//   placedBBox: { min:[x,y,z], max:[x,y,z] } world bbox of the just-placed structural leaves.
//   opts: { rotDeg } (the drop rotation; 0 = the common case).
function rwAlignSegments(segments, placedBBox, opts) {
  if (!segments.length) return [];
  opts = opts || {};
  var rad = (opts.rotDeg || 0) * Math.PI / 180, cs = Math.cos(rad), sn = Math.sin(rad);
  var amin = [Infinity, Infinity, Infinity];
  segments.forEach(function (s) {
    [s.from, s.to].forEach(function (p) { for (var i = 0; i < 3; i++) if (p[i] < amin[i]) amin[i] = p[i]; });
  });
  var wmin = placedBBox.min;
  function map(p) {
    var lx = p[0] - amin[0], ly = p[1] - amin[1], lz = p[2] - amin[2];
    return [wmin[0] + (cs * lx - sn * ly), wmin[1] + (sn * lx + cs * ly), wmin[2] + lz];
  }
  return segments.map(function (s) {
    return { disc: s.disc, storey: s.storey, axis: s.axis, from: map(s.from), to: map(s.to), len: s.len };
  });
}

// Centroid of all segment endpoints — the natural drop-transform pivot
// (negate to centre a routed building at the modeller origin / drop point).
function rwSegmentCentroid(segments) {
  if (!segments.length) return [0, 0, 0];
  var sx = 0, sy = 0, sz = 0, n = 0;
  segments.forEach(function (s) {
    sx += s.from[0] + s.to[0]; sy += s.from[1] + s.to[1]; sz += s.from[2] + s.to[2]; n += 2;
  });
  return [sx / n, sy / n, sz / n];
}

// ═══════════════════════════════════════════════════════════════
// EMIT SEAM: place FIXTURES per room (lights / fans / sprinklers / outlets) for the op-log modeller
// ═══════════════════════════════════════════════════════════════
//
// The structural-only buildings (SH/DX) carry NO MEP leaves (correct by design, §6.2). Per-room MEP is
// GENERATED by the COVERING verb from the real recipe: ad_space_type_mep_bom (what MEP per room type) +
// ad_placement_offset (where in the room). The ROOMS come from the per-building BOM's role-typed room sets
// (e.g. SH FLOOR children: LIVING / DINING / MASTER / BATHROOM) — real type + position, NOT invented.
// rwPlaceFixtures is PURE (no DB writes): it returns fixture placements the modeller commits as signed ops.

// Catalog room ROLE → ad_space_type_mep_bom space_type_id (the role IS the type; only MASTER needs a rename).
var RW_ROLE_TO_SPACE = {
  MASTER: 'MASTER_BEDROOM', MASTER_BEDROOM: 'MASTER_BEDROOM', BED: 'BEDROOM', BEDROOM: 'BEDROOM',
  LIVING: 'LIVING', DINING: 'DINING', KITCHEN: 'KITCHEN', WET_KITCHEN: 'WET_KITCHEN',
  BATHROOM: 'BATHROOM', TOILET: 'BATHROOM', TOILET_BLOCK: 'BATHROOM',
  STUDY: 'STUDY_NOOK', STUDY_NOOK: 'STUDY_NOOK', OFFICE: 'OFFICE', CORRIDOR: 'CORRIDOR',
  STAIR: 'STAIR', GARAGE: 'GARAGE', UTILITY: 'UTILITY', STORAGE: 'STORAGE'
};
function _rwRoleToSpace(role) {
  if (!role) return 'GENERIC';
  var u = String(role).toUpperCase();
  return RW_ROLE_TO_SPACE[u] || u;   // identity for already-canonical types; GENERIC handled by caller fallback
}

/**
 * Place MEP fixtures per room from the real recipe — PURE (returns placements, no DB write).
 * @param {Array} rooms  [{ type|role, cx,cy,cz, bx,by,bz, storey, name }] in the SAME frame the caller wants out.
 * @param {object} [opts] reserved.
 * @returns {Array} [{ product, ifcClass, disc, rgba, x, y, z, room, hostSurface, placementRule }]
 *   disc ∈ {ELEC, ACMV, FP, PLB} — every fixture traces to ad_space_type_mep_bom + ad_placement_offset.
 */
function rwPlaceFixtures(rooms, opts) {
  if (!_rwReady) { console.warn('§RW_FIX_FAIL not initialised'); return []; }
  opts = opts || {};
  if (!rooms || !rooms.length) return [];

  // Load placement offsets once (keyed by rule name)
  var offsets = {};
  var offRows = _rwDb.exec("SELECT * FROM ad_placement_offset");
  if (offRows.length) {
    var cols = offRows[0].columns;
    offRows[0].values.forEach(function (v) { var o = {}; cols.forEach(function (c, i) { o[c] = v[i]; }); offsets[v[0]] = o; });
  }

  // WALL-MOUNT FIDELITY: a WALL-host fixture (switch/outlet/wall-aircon) nominally lands at the room SET's aabb
  // EDGE — the furniture-extent, not a real wall. Snap it onto the nearest REAL wall solid (the building's
  // arc_envelope thin-and-tall boxes, same source the clash gate uses) so switches/outlets actually mount on a
  // wall surface. Honest fallback: where SH's PARTIAL wall model has no wall within RW_WALL_SNAP_MAX, the fixture
  // keeps its nominal edge position (never teleported across the building). opts.wallBoxes injects them directly
  // (witness); else they self-load from opts.buildingName.
  var wallBoxes = opts.wallBoxes ||
    (opts.buildingName ? _rwLoadArcEnvelopeFromDb(opts.buildingName).filter(function (a) { return Math.min(a.w, a.d) < 0.5 && a.h > 1.5; }) : []);

  var out = [], snappedN = 0;
  rooms.forEach(function (room) {
    var spaceType = _rwRoleToSpace(room.type || room.role);
    var bomRows = _rwDb.exec(
      "SELECT mep_product_id, qty_normal, placement_rule, host_surface, anchor_end " +
      "FROM ad_space_type_mep_bom WHERE space_type_id = '" + spaceType.replace(/'/g, "''") + "' AND qty_normal > 0"
    );
    // GENERIC fallback if the room type has no recipe (so every room gets at least a light + switch)
    if (!bomRows.length || !bomRows[0].values.length) {
      bomRows = _rwDb.exec("SELECT mep_product_id, qty_normal, placement_rule, host_surface, anchor_end " +
        "FROM ad_space_type_mep_bom WHERE space_type_id = 'GENERIC' AND qty_normal > 0");
      if (!bomRows.length) return;
    }
    bomRows[0].values.forEach(function (v) {
      var product = v[0], qty = v[1] || 1, rule = v[2] || 'AUTO', host = v[3] || 'WALL';
      var offset = offsets[rule] || offsets['AUTO'];
      if (!offset) return;
      var info = RW_IFC_MAP[product] || RW_IFC_MAP._DEFAULT;
      for (var q = 0; q < qty; q++) {
        var pos = _rwComputePosition(room, offset, host, q, qty);
        var wsnap = false;
        if (host === 'WALL' && wallBoxes.length) {
          var sn = _rwSnapToWall(pos.x, pos.y, pos.z, wallBoxes, RW_WALL_SNAP_MAX);
          if (sn.snapped) { pos.x = sn.x; pos.y = sn.y; wsnap = true; snappedN++; }
        }
        out.push({
          product: product, ifcClass: info.cls, disc: info.disc, rgba: info.rgba,
          x: pos.x, y: pos.y, z: pos.z, room: (room.name || spaceType), hostSurface: host, placementRule: rule,
          wallSnapped: wsnap
        });
      }
    });
  });

  var byDisc = {};
  out.forEach(function (f) { byDisc[f.disc] = (byDisc[f.disc] || 0) + 1; });
  console.log('§RW_FIX rooms=' + rooms.length + ' fixtures=' + out.length + ' wallSnapped=' + snappedN +
    ' disc=' + Object.keys(byDisc).map(function (k) { return k + ':' + byDisc[k]; }).join(' '));
  return out;
}

// Snap a wall-host fixture onto the nearest REAL wall solid (arc_envelope thin-and-tall box). Walls are thin in
// ONE horizontal axis; mount the fixture on the box face nearest the point (the room-facing side) + a small
// offset, clamped to the wall's span. Only snaps if a wall is within maxDist (else honest fallback to nominal).
function _rwSnapToWall(x, y, z, wallBoxes, maxDist) {
  var best = null, bestD = Infinity;
  for (var i = 0; i < wallBoxes.length; i++) {
    var a = wallBoxes[i];
    if (z < a.cz - a.h / 2 - 0.10 || z > a.cz + a.h / 2 + 0.10) continue;   // fixture height must fall within the wall
    var dx = Math.max(Math.abs(x - a.cx) - a.w / 2, 0);
    var dy = Math.max(Math.abs(y - a.cy) - a.d / 2, 0);
    var d = Math.sqrt(dx * dx + dy * dy);
    if (d < bestD) { bestD = d; best = a; }
  }
  if (!best || bestD > (maxDist || 1.5)) return { x: x, y: y, z: z, snapped: false };
  var nx = x, ny = y;
  if (best.w <= best.d) {                                                    // thin in X → wall runs along Y
    nx = best.cx + (x >= best.cx ? 1 : -1) * (best.w / 2 + 0.02);
    ny = Math.max(best.cy - best.d / 2, Math.min(best.cy + best.d / 2, y));
  } else {                                                                   // thin in Y → wall runs along X
    ny = best.cy + (y >= best.cy ? 1 : -1) * (best.d / 2 + 0.02);
    nx = Math.max(best.cx - best.w / 2, Math.min(best.cx + best.w / 2, x));
  }
  return { x: nx, y: ny, z: z, snapped: true, dist: bestD };
}

// Mirror of _rwApplyPattern's pairing, but collects endpoint pairs into `out`.
function _rwPairSegments(discipline, steps, allAnchors, arcEnvelope, out) {
  var byStorey = {};
  allAnchors.forEach(function (a) {
    var s = a.storey || 'Unknown';
    if (!byStorey[s]) byStorey[s] = [];
    byStorey[s].push(a);
  });

  Object.keys(byStorey).forEach(function (storey) {
    var storeyAnchors = byStorey[storey];
    var usedIds = {};
    steps.forEach(function (step) {
      var fromCandidates = [], toCandidates = [];
      storeyAnchors.forEach(function (a) {
        var nt = _rwToNodeType(a.anchorType, discipline);
        if (nt === step.fromNodeType) fromCandidates.push(a);
        if (nt === step.toNodeType && !usedIds[a.anchorId]) toCandidates.push(a);
      });
      if (!fromCandidates.length || !toCandidates.length) return;

      fromCandidates.forEach(function (from) {
        var nearest = null, minDist = Infinity;
        toCandidates.forEach(function (to) {
          if (usedIds[to.anchorId]) return;
          var dx = to.x - from.x, dy = to.y - from.y;
          var dist = Math.sqrt(dx * dx + dy * dy);
          if (dist < minDist) { minDist = dist; nearest = to; }
        });
        if (!nearest) return;
        if (minDist === 0 || minDist > RW_MAX_PAIR_DIST) return;

        var dx = nearest.x - from.x, dy = nearest.y - from.y, dz = nearest.z - from.z;
        if (step.offsetRule === 'GRADIENT' && step.gradient > 0) {
          dz = step.gradient * Math.sqrt(dx * dx + dy * dy);
        }
        var len = Math.sqrt(dx * dx + dy * dy + dz * dz);
        var midX = (from.x + nearest.x) / 2, midY = (from.y + nearest.y) / 2, midZ = (from.z + nearest.z) / 2;
        if (_rwClashesWithArc(midX, midY, midZ, RW_PIPE_CROSS / 1000, RW_PIPE_CROSS / 1000, len, arcEnvelope)) {
          return; // clash — skip, same gate as the insert path
        }
        out.push({
          disc: discipline, storey: storey, axis: step.directionAxis,
          from: [from.x, from.y, from.z], to: [nearest.x, nearest.y, from.z + dz],
          len: len
        });
        usedIds[nearest.anchorId] = true;
      });
    });
  });
}

// ═══════════════════════════════════════════════════════════════
// PATH A: Pattern walk (Java RouteWalker port)
// ═══════════════════════════════════════════════════════════════

function _rwPatternWalk(buildingDb, buildingName, arcEnvelope) {
  var cwSteps = _rwLoadPatternSteps('CW', buildingName);
  var spSteps = _rwLoadPatternSteps('SP', buildingName);
  var allAnchors = _rwLoadAnchors(buildingName);

  if (!allAnchors.length) {
    console.warn('§RW_WARN no anchors for ' + buildingName);
    return { cwLines: 0, spLines: 0, clashSkipped: 0 };
  }

  var cwResult = cwSteps.length ? _rwApplyPattern(buildingDb, 'CW', cwSteps, allAnchors, arcEnvelope, buildingName) : { emitted: 0, clashSkipped: 0 };
  var spResult = spSteps.length ? _rwApplyPattern(buildingDb, 'SP', spSteps, allAnchors, arcEnvelope, buildingName) : { emitted: 0, clashSkipped: 0 };

  console.log('§RW_PATTERN ' + buildingName + ': CW=' + cwResult.emitted +
              ' SP=' + spResult.emitted + ' clashSkipped=' + (cwResult.clashSkipped + spResult.clashSkipped));
  return {
    cwLines: cwResult.emitted,
    spLines: spResult.emitted,
    clashSkipped: cwResult.clashSkipped + spResult.clashSkipped
  };
}

// A1. Load pattern steps from mep_rw.db
function _rwLoadPatternSteps(discipline, buildingType) {
  var rows = _rwDb.exec(
    "SELECT pattern_id, discipline, building_type, sequence, from_node_type, to_node_type, " +
    "direction_axis, piece_type, offset_rule, COALESCE(gradient, 0) " +
    "FROM ad_mep_pattern WHERE discipline = '" + discipline + "' " +
    "ORDER BY CASE WHEN building_type = '" + buildingType.replace(/'/g, "''") + "' THEN 0 ELSE 1 END, sequence"
  );
  if (!rows.length || !rows[0].values.length) return [];
  var selectedId = rows[0].values[0][0];
  var steps = [];
  for (var i = 0; i < rows[0].values.length; i++) {
    var v = rows[0].values[i];
    if (v[0] !== selectedId) break; // only first (best) pattern
    steps.push({
      patternId: v[0], discipline: v[1], buildingType: v[2], sequence: v[3],
      fromNodeType: v[4], toNodeType: v[5], directionAxis: v[6],
      pieceType: v[7], offsetRule: v[8], gradient: v[9]
    });
  }
  if (steps.length) console.log('§RW_PATTERN_LOADED ' + discipline + ' pattern=' + selectedId + ' steps=' + steps.length);
  return steps;
}

// A2. Load anchors from mep_rw.db
function _rwLoadAnchors(buildingName) {
  var rows = _rwDb.exec(
    "SELECT anchor_id, anchor_type, x_m, y_m, z_m, storey " +
    "FROM ad_mep_anchor WHERE source_building = '" + buildingName.replace(/'/g, "''") + "'"
  );
  if (!rows.length) return [];
  return rows[0].values.map(function(v) {
    return { anchorId: v[0], anchorType: v[1], x: v[2], y: v[3], z: v[4], storey: v[5] || 'Unknown' };
  });
}

// Node type mapping (same logic as Java)
function _rwToNodeType(anchorType, discipline) {
  if (anchorType === 'METER') return discipline === 'SP' ? 'STACK' : 'METER';
  if (anchorType === 'FIXTURE') return 'FIXTURE';
  if (anchorType === 'VALVE') return 'VALVE';
  return 'JUNCTION';
}

// A3. Apply pattern — pair anchors, check clash, emit pipe segments
function _rwApplyPattern(buildingDb, discipline, steps, allAnchors, arcEnvelope, buildingName) {
  // Group anchors by storey
  var byStorey = {};
  allAnchors.forEach(function(a) {
    var s = a.storey || 'Unknown';
    if (!byStorey[s]) byStorey[s] = [];
    byStorey[s].push(a);
  });

  var emitted = 0, clashSkipped = 0;

  Object.keys(byStorey).forEach(function(storey) {
    var storeyAnchors = byStorey[storey];
    var usedIds = {};

    steps.forEach(function(step) {
      var fromCandidates = [], toCandidates = [];
      storeyAnchors.forEach(function(a) {
        var nt = _rwToNodeType(a.anchorType, discipline);
        if (nt === step.fromNodeType) fromCandidates.push(a);
        if (nt === step.toNodeType && !usedIds[a.anchorId]) toCandidates.push(a);
      });

      if (!fromCandidates.length || !toCandidates.length) return;

      fromCandidates.forEach(function(from) {
        // Find nearest unmatched to-anchor
        var nearest = null, minDist = Infinity;
        toCandidates.forEach(function(to) {
          if (usedIds[to.anchorId]) return;
          var dx = to.x - from.x, dy = to.y - from.y;
          var dist = Math.sqrt(dx * dx + dy * dy);
          if (dist < minDist) { minDist = dist; nearest = to; }
        });
        if (!nearest) return;

        // Sanity guard: skip distance=0 or >50m
        if (minDist === 0 || minDist > RW_MAX_PAIR_DIST) return;

        var dx = nearest.x - from.x;
        var dy = nearest.y - from.y;
        var dz = nearest.z - from.z;

        // Gradient steps: enforce slope
        if (step.offsetRule === 'GRADIENT' && step.gradient > 0) {
          var horiz = Math.sqrt(dx * dx + dy * dy);
          dz = step.gradient * horiz;
        }

        var pipeLen = Math.sqrt(dx * dx + dy * dy + dz * dz);
        var midX = (from.x + nearest.x) / 2;
        var midY = (from.y + nearest.y) / 2;
        var midZ = (from.z + nearest.z) / 2;

        // ARC envelope clash check
        if (_rwClashesWithArc(midX, midY, midZ, RW_PIPE_CROSS / 1000, RW_PIPE_CROSS / 1000, pipeLen, arcEnvelope)) {
          clashSkipped++;
          return;
        }

        // Emit pipe segment
        var info = discipline === 'CW' ? RW_IFC_MAP.PIPE_CW : RW_IFC_MAP.PIPE_SP;
        var guid = _rwGuid(discipline + '_PIPE');
        _rwInsertElement(buildingDb, guid, info.cls,
          discipline + ' Pipe ' + step.directionAxis + ' ' + storey,
          buildingName, storey, info.disc, info.rgba,
          midX, midY, midZ,
          Math.abs(dx) || RW_PIPE_CROSS / 1000,
          Math.abs(dy) || RW_PIPE_CROSS / 1000,
          Math.abs(dz) || RW_PIPE_CROSS / 1000
        );
        emitted++;
        usedIds[nearest.anchorId] = true;
      });
    });
  });

  return { emitted: emitted, clashSkipped: clashSkipped };
}

// A4a. ARC envelope loader from mep_rw.db (for the op-log modeller — no building DB)
// Returns boxes in extraction-space metres, same coordinate frame as ad_mep_anchor.
function _rwLoadArcEnvelopeFromDb(buildingName) {
  if (!_rwDb) return [];
  try {
    var rows = _rwDb.exec(
      "SELECT cx, cy, cz, w, d, h FROM arc_envelope WHERE source_building = '" +
      buildingName.replace(/'/g, "''") + "'"
    );
    if (!rows.length || !rows[0].values.length) return [];
    var boxes = rows[0].values.map(function(v) {
      return { cx: v[0], cy: v[1], cz: v[2], w: v[3], d: v[4], h: v[5] };
    });
    console.log('§RW_ARC_FROM_DB building=' + buildingName + ' boxes=' + boxes.length);
    return boxes;
  } catch (e) {
    console.warn('§RW_ARC_FROM_DB_FAIL ' + e.message);
    return [];
  }
}

/**
 * Building origin in extraction space (from mep_rw.db building_origin table).
 * This is the structural AABB min (allMinXYZ used by StructuralBomBuilder) — the
 * reference point that maps extraction-space positions to BOM-relative positions.
 * Use with: worldPos = placedBBoxMin + (extractionPos - buildingOrigin)
 * @param {string} buildingName — matches source_building in mep_rw.db
 * @returns {{ x, y, z }} or null if not found
 */
function rwBuildingOrigin(buildingName) {
  if (!_rwReady || !_rwDb) return null;
  try {
    var rows = _rwDb.exec(
      "SELECT min_x, min_y, min_z FROM building_origin WHERE source_building = '" +
      buildingName.replace(/'/g, "''") + "'"
    );
    if (!rows.length || !rows[0].values.length) return null;
    var v = rows[0].values[0];
    return { x: v[0], y: v[1], z: v[2] };
  } catch (e) {
    return null;
  }
}

/**
 * Load a building's REAL rooms from mep_rw.db (building_room), baked from its OWN extracted BOM by
 * scripts/build_mep_room_envelopes.js. The op-log modeller has no building DB and the catalog's FLOOR rooms
 * are a SYNTHESISED row — so the faithful room source is this sidecar, the same way the clash gate reads
 * arc_envelope. Rooms come back in EXTRACTION-WORLD metres (cx,cy,cz + extents), ready for rwPlaceFixtures;
 * the caller then applies the SAME rigid transform the routed pipes use: world = bmin + (pos − buildingOrigin).
 * @param {string} buildingName — matches source_building in mep_rw.db
 * @returns {Array} [{ type, name, storey, cx, cy, cz, bx, by, bz }] (empty if the building has no baked rooms)
 */
function rwLoadRooms(buildingName) {
  if (!_rwReady || !_rwDb) { console.warn('§RW_ROOMS_FAIL not initialised'); return []; }
  var out = [];
  try {
    var rows = _rwDb.exec(
      "SELECT role, cx, cy, cz, bx, by_, bz FROM building_room WHERE source_building = '" +
      buildingName.replace(/'/g, "''") + "'"
    );
    if (rows.length) {
      rows[0].values.forEach(function (v) {
        out.push({ type: v[0], name: v[0], storey: 'Ground Floor',
          cx: v[1], cy: v[2], cz: v[3], bx: v[4], by: v[5], bz: v[6] });
      });
    }
  } catch (e) { /* table absent — no baked rooms for this building */ }
  console.log('§RW_ROOMS building=' + buildingName + ' rooms=' + out.length);
  return out;
}

// A4. ARC envelope loader (from building DB)
function _rwLoadArcEnvelope(buildingDb) {
  var boxes = [];
  try {
    var rows = buildingDb.exec(
      "SELECT t.center_x, t.center_y, t.center_z, t.bbox_x, t.bbox_y, t.bbox_z " +
      "FROM elements_meta m JOIN element_transforms t ON m.guid = t.guid " +
      "WHERE m.discipline = 'ARC' AND m.ifc_class IN ('IfcWall','IfcWallStandardCase','IfcSlab','IfcRoof','IfcCovering')"
    );
    if (rows.length) {
      rows[0].values.forEach(function(v) {
        if (v[3] > 0 && v[4] > 0 && v[5] > 0) {
          boxes.push({ cx: v[0], cy: v[1], cz: v[2], w: v[3], d: v[4], h: v[5] });
        }
      });
    }
  } catch (e) { /* no ARC elements — no clash check */ }
  console.log('§RW_ARC_ENVELOPE boxes=' + boxes.length);
  return boxes;
}

// AABB overlap check (same as Java)
function _rwAabbOverlap(c1, s1, c2, s2, tol) {
  return Math.abs(c1 - c2) < (s1 / 2 + s2 / 2 + tol);
}

// Optional `tol` overrides RW_ARC_CLASH_TOL. Positive tol = a REQUIRED standoff (the candidate must stay
// `tol` metres CLEAR of the box); the default -0.01 lets a pipe touch a wall but not penetrate. The
// discipline-aware caller (_rwStructTol) passes the cited clearance for the relevant service.
function _rwClashesWithArc(px, py, pz, pw, pd, ph, arcs, tol) {
  if (tol === undefined) tol = RW_ARC_CLASH_TOL;
  for (var i = 0; i < arcs.length; i++) {
    var a = arcs[i];
    if (_rwAabbOverlap(px, pw, a.cx, a.w, tol) &&
        _rwAabbOverlap(py, pd, a.cy, a.d, tol) &&
        _rwAabbOverlap(pz, ph, a.cz, a.h, tol)) {
      return true;
    }
  }
  return false;
}

// ═══════════════════════════════════════════════════════════════
// COORDINATION SEAM: discipline-vs-discipline arbitration (CoordinationHandler)
// ═══════════════════════════════════════════════════════════════
//
// The clash gate above keeps services out of STRUCTURE. CoordinationHandler (mep_coordination.js,
// docs/MEP_COORDINATION_RULESET.md) decides what happens when two MEP SERVICES of different disciplines
// share ceiling/riser space: WHO HOLDS, WHO YIELDS, by HOW MUCH (cited min-separation), and the MOVE.
// NON-INVENT: it acts (displaces a yielder) ONLY on VERIFIED rules; PENDING rules are logged as advisory.
// Revert-safe: this is an OPT-IN pass (rwCoordinate); the insert/emit paths above are untouched.

// our RouteWalker disc codes → CoordinationHandler disc codes.
var RW_DISC_TO_COORD = {
  CW: 'DWATER', SP: 'DRAIN', PLB: 'DWATER',   // CW=pressurised cold water, SP=gravity soil/waste
  ELEC: 'ELEC', DATA: 'DATA', ACMV: 'ACMV', FP: 'FP', STRUCT: 'STRUCT', MEP: null
};
function _rwToCoordDisc(d) { return RW_DISC_TO_COORD[d] !== undefined ? RW_DISC_TO_COORD[d] : null; }

// Discipline-aware STRUCTURE clearance (metres) for the clash gate. Only FP (sprinkler) carries a cited
// VERIFIED standoff from non-supporting structure (NFPA 13 §18.4.9, 50mm via CoordinationHandler); every
// other service keeps the default touch-but-don't-penetrate tol (no citation = no invented clearance).
function _rwStructTol(disc, coord) {
  if (coord && disc === 'FP') {
    var s = coord.minSeparation('FP', 'STRUCT');
    if (s && s.status === 'VERIFIED') return s.mm / 1000;  // positive = required standoff
  }
  return RW_ARC_CLASH_TOL;
}

// Closest distance between two 3D segments a={from,to}, b={from,to} (+ the closest points).
function _rwSegDist(a, b) {
  function sub(p, q) { return [p[0]-q[0], p[1]-q[1], p[2]-q[2]]; }
  function dot(p, q) { return p[0]*q[0] + p[1]*q[1] + p[2]*q[2]; }
  var d1 = sub(a.to, a.from), d2 = sub(b.to, b.from), r = sub(a.from, b.from);
  var A = dot(d1, d1), E = dot(d2, d2), F = dot(d2, r);
  var s, t, B = dot(d1, d2), C = dot(d1, r), den = A*E - B*B;
  s = den !== 0 ? Math.min(1, Math.max(0, (B*F - C*E) / den)) : 0;
  t = E !== 0 ? (B*s + F) / E : 0;
  t = Math.min(1, Math.max(0, t));
  s = A !== 0 ? Math.min(1, Math.max(0, (B*t - C) / A)) : 0;
  var p1 = [a.from[0]+d1[0]*s, a.from[1]+d1[1]*s, a.from[2]+d1[2]*s];
  var p2 = [b.from[0]+d2[0]*t, b.from[1]+d2[1]*t, b.from[2]+d2[2]*t];
  var dd = sub(p1, p2);
  return { dist: Math.sqrt(dot(dd, dd)), p1: p1, p2: p2 };
}

/**
 * Coordinate routed MEP segments of MULTIPLE disciplines against each other (the discipline-vs-discipline
 * gate). For every cross-discipline segment pair closer than their cited min-separation, ask
 * CoordinationHandler.arbitrate() who holds / who yields / how far / how. ENFORCED decisions DISPLACE the
 * yielding segment perpendicular to clear the separation; PENDING decisions are logged advisory (not moved).
 *
 * @param {Object} routesByDisc  { ACMV:[{from,to}], ELEC:[...], FP:[...] } RouteWalker disc codes; segments
 *                                are mutated in place when a move is enforced.
 * @param {Object} coord         CoordinationHandler (window.CoordinationHandler / mep_coordination.js).
 * @returns {Object} { rawClashes, resolvedClashes, enforced, advisory, decisions:[...] }
 */
function rwCoordinate(routesByDisc, coord) {
  if (!coord) { console.warn('§RW_COORD_FAIL no CoordinationHandler'); return null; }
  var discs = Object.keys(routesByDisc).filter(function (d) { return _rwToCoordDisc(d); });
  var decisions = [], enforced = 0, advisory = 0, raw = 0;

  function clashCount() {
    var n = 0;
    for (var i = 0; i < discs.length; i++) for (var j = i + 1; j < discs.length; j++) {
      var ca = _rwToCoordDisc(discs[i]), cb = _rwToCoordDisc(discs[j]);
      var sepM = coord.minSeparation(ca, cb).mm / 1000;
      var A = routesByDisc[discs[i]], Bs = routesByDisc[discs[j]];
      for (var x = 0; x < A.length; x++) for (var y = 0; y < Bs.length; y++) {
        if (_rwSegDist(A[x], Bs[y]).dist < sepM) n++;
      }
    }
    return n;
  }

  raw = clashCount();

  for (var i = 0; i < discs.length; i++) for (var j = i + 1; j < discs.length; j++) {
    var da = discs[i], db = discs[j];
    var ca = _rwToCoordDisc(da), cb = _rwToCoordDisc(db);
    var arb = coord.arbitrate(ca, cb);
    var sepM = arb.minSepMm / 1000;
    var holdDisc = arb.holds === ca ? da : db;       // which routewalker bucket holds
    var yieldDisc = arb.yields === ca ? da : db;     // which yields
    var holders = routesByDisc[holdDisc], yielders = routesByDisc[yieldDisc];
    var pairClashes = 0, pairMoved = 0;

    for (var y = 0; y < yielders.length; y++) {
      for (var h = 0; h < holders.length; h++) {
        var d = _rwSegDist(yielders[y], holders[h]);
        if (d.dist >= sepM) continue;
        pairClashes++;
        if (arb.enforce) {
          // displace the yielding segment to clear the cited separation (perpendicular push)
          var v = [d.p1[0]-d.p2[0], d.p1[1]-d.p2[1], d.p1[2]-d.p2[2]];
          var vl = Math.sqrt(v[0]*v[0] + v[1]*v[1] + v[2]*v[2]);
          if (vl < 1e-9) { v = [0, 0, 1]; vl = 1; }                 // degenerate (coincident) → push up
          var push = (sepM - d.dist) + 1e-4;
          var mv = [v[0]/vl*push, v[1]/vl*push, v[2]/vl*push];
          yielders[y].from = [yielders[y].from[0]+mv[0], yielders[y].from[1]+mv[1], yielders[y].from[2]+mv[2]];
          yielders[y].to   = [yielders[y].to[0]+mv[0],   yielders[y].to[1]+mv[1],   yielders[y].to[2]+mv[2]];
          yielders[y].coordMoved = true;
          pairMoved++; h = -1;   // re-test this yielder against all holders after the move
        }
      }
    }
    if (pairClashes) {
      (arb.enforce ? (enforced += pairMoved) : (advisory += pairClashes));
      decisions.push({ a: da, b: db, holds: holdDisc, yields: yieldDisc, minSepMm: arb.minSepMm,
        move: arb.move, enforce: arb.enforce, clashes: pairClashes, moved: pairMoved });
      console.log('§RW_COORD ' + da + '×' + db + ' clashes=' + pairClashes +
        ' holds=' + holdDisc + ' yields=' + yieldDisc + ' sep=' + arb.minSepMm + 'mm' +
        ' ' + (arb.enforce ? ('ENFORCED moved=' + pairMoved) : 'ADVISORY (rule not VERIFIED)'));
    }
  }

  var resolved = clashCount();
  console.log('§RW_COORD_SUMMARY raw=' + raw + ' resolved=' + resolved +
    ' enforcedMoves=' + enforced + ' advisoryClashes=' + advisory);
  return { rawClashes: raw, resolvedClashes: resolved, enforced: enforced, advisory: advisory, decisions: decisions };
}

/**
 * Enforce a discipline's cited clearance from STRUCTURE (the discipline-aware extension of the structural
 * clash gate). Only FP (sprinkler) carries a VERIFIED standoff (NFPA 13 §18.4.9 50mm via CoordinationHandler);
 * every other service keeps the default touch-but-don't-penetrate behaviour. Segments that violate the
 * required clearance are pushed off the offending box by the axis-of-least-penetration. Mutates `segs`.
 *
 * @param {Array}  segs        [{ from:[x,y,z], to:[x,y,z] }] route segments of one discipline.
 * @param {string} disc        RouteWalker disc code (FP / ELEC / ACMV / …).
 * @param {Array}  structBoxes [{ cx,cy,cz,w,d,h }] real ARC structural envelope boxes.
 * @param {Object} coord       CoordinationHandler.
 * @returns {Object} { raw, resolved, moved, tol, enforced }
 */
function rwClearStructure(segs, disc, structBoxes, coord) {
  var tol = _rwStructTol(disc, coord);          // FP → +0.05 (50mm standoff); else RW_ARC_CLASH_TOL (touch)
  var enforced = tol > 0;                        // a positive standoff is a VERIFIED, enforceable clearance
  var cross = RW_PIPE_CROSS / 1000;

  function clashesAt(seg) {                      // pipe midpoint + cross-section vs the structural boxes
    var mx = (seg.from[0]+seg.to[0])/2, my = (seg.from[1]+seg.to[1])/2, mz = (seg.from[2]+seg.to[2])/2;
    return _rwClashesWithArc(mx, my, mz, cross, cross, cross, structBoxes, tol);
  }
  function offending(seg) {                      // the box the pipe midpoint violates (for the push vector)
    var mx = (seg.from[0]+seg.to[0])/2, my = (seg.from[1]+seg.to[1])/2, mz = (seg.from[2]+seg.to[2])/2;
    for (var i = 0; i < structBoxes.length; i++) {
      var a = structBoxes[i];
      if (_rwAabbOverlap(mx, cross, a.cx, a.w, tol) && _rwAabbOverlap(my, cross, a.cy, a.d, tol) &&
          _rwAabbOverlap(mz, cross, a.cz, a.h, tol)) return a;
    }
    return null;
  }

  var raw = 0; segs.forEach(function (s) { if (clashesAt(s)) raw++; });
  var moved = 0;
  if (enforced) {
    segs.forEach(function (s) {
      var guard = 0;
      while (clashesAt(s) && guard++ < 8) {
        var a = offending(s); if (!a) break;
        var mx = (s.from[0]+s.to[0])/2, my = (s.from[1]+s.to[1])/2, mz = (s.from[2]+s.to[2])/2;
        // push out along the axis of least penetration (the cheapest way to reach the required standoff)
        var penX = (a.w/2 + cross/2 + tol) - Math.abs(mx - a.cx);
        var penY = (a.d/2 + cross/2 + tol) - Math.abs(my - a.cy);
        var mvx = 0, mvy = 0;
        if (penX <= penY) mvx = (mx >= a.cx ? 1 : -1) * (penX + 1e-4);
        else              mvy = (my >= a.cy ? 1 : -1) * (penY + 1e-4);
        s.from = [s.from[0]+mvx, s.from[1]+mvy, s.from[2]];
        s.to   = [s.to[0]+mvx,   s.to[1]+mvy,   s.to[2]];
        s.coordMoved = true;
      }
      if (s.coordMoved) moved++;
    });
  }
  var resolved = 0; segs.forEach(function (s) { if (clashesAt(s)) resolved++; });
  console.log('§RW_CLEAR_STRUCT disc=' + disc + ' tol=' + (tol*1000).toFixed(0) + 'mm ' +
    (enforced ? 'ENFORCED' : 'advisory(touch)') + ' raw=' + raw + ' resolved=' + resolved + ' moved=' + moved);
  return { raw: raw, resolved: resolved, moved: moved, tol: tol, enforced: enforced };
}


// ═══════════════════════════════════════════════════════════════
// PATH B: Room-based BOM placement
// ═══════════════════════════════════════════════════════════════

/**
 * Detect rooms from building DB.
 * Uses IfcSpace elements if present, falls back to storey-level generic rooms.
 */
function _rwDetectRooms(buildingDb, buildingName) {
  var rooms = [];

  // Try IfcSpace first
  try {
    var spaceRows = buildingDb.exec(
      "SELECT m.guid, m.element_name, m.storey, " +
      "t.center_x, t.center_y, t.center_z, t.bbox_x, t.bbox_y, t.bbox_z " +
      "FROM elements_meta m JOIN element_transforms t ON m.guid = t.guid " +
      "WHERE m.ifc_class = 'IfcSpace' AND m.building = '" + buildingName.replace(/'/g, "''") + "'"
    );
    if (spaceRows.length && spaceRows[0].values.length) {
      spaceRows[0].values.forEach(function(v) {
        rooms.push({
          id: v[0], name: v[1], storey: v[2],
          type: _rwClassifyRoom(v[1], v[6] * v[7]),
          cx: v[3], cy: v[4], cz: v[5],
          bx: v[6], by: v[7], bz: v[8]
        });
      });
      console.log('§RW_ROOMS source=IfcSpace count=' + rooms.length);
      return rooms;
    }
  } catch (e) { /* no IfcSpace */ }

  // Fallback: one generic room per storey from wall envelope
  try {
    var storeyRows = buildingDb.exec(
      "SELECT m.storey, " +
      "AVG(t.center_x), AVG(t.center_y), AVG(t.center_z), " +
      "MAX(t.bbox_x), MAX(t.bbox_y), MAX(t.bbox_z), " +
      "COUNT(*) " +
      "FROM elements_meta m JOIN element_transforms t ON m.guid = t.guid " +
      "WHERE m.building = '" + buildingName.replace(/'/g, "''") + "' " +
      "AND m.discipline = 'ARC' " +
      "GROUP BY m.storey"
    );
    if (storeyRows.length) {
      storeyRows[0].values.forEach(function(v) {
        var area = (v[4] || 10) * (v[5] || 10);
        rooms.push({
          id: 'STOREY_' + (v[0] || 'Unknown'),
          name: v[0] || 'Unknown',
          storey: v[0] || 'Unknown',
          type: _rwClassifyRoom(v[0], area),
          cx: v[1], cy: v[2], cz: v[3],
          bx: v[4] || 10, by: v[5] || 10, bz: v[6] || 3
        });
      });
    }
  } catch (e) { /* empty DB */ }

  console.log('§RW_ROOMS source=storey_fallback count=' + rooms.length);
  return rooms;
}

/**
 * Classify room type from name + area, matching ad_space_type values.
 */
function _rwClassifyRoom(name, areaSqm) {
  if (!name) name = '';
  var n = name.toUpperCase();

  // Name-based classification
  if (/TOILET|BATH|WC|SHOWER|RESTROOM/.test(n)) return 'BATHROOM';
  if (/KITCHEN|PANTRY|DAPUR/.test(n)) return 'KITCHEN';
  if (/MASTER.*BED|BED.*MASTER/.test(n)) return 'MASTER_BEDROOM';
  if (/BED|BILIK\s*TIDUR/.test(n)) return 'BEDROOM';
  if (/LIVING|LOUNGE|RUANG\s*TAMU/.test(n)) return 'LIVING';
  if (/DINING|MAKAN/.test(n)) return 'DINING';
  if (/CORRIDOR|HALLWAY|LORONG/.test(n)) return 'CORRIDOR';
  if (/LOBBY/.test(n)) return 'LOBBY';
  if (/OFFICE|PEJABAT/.test(n)) return 'OFFICE';
  if (/STORE|STOR/.test(n)) return 'STORAGE';
  if (/GARAGE|PARKING/.test(n)) return 'GARAGE';
  if (/STAIR/.test(n)) return 'STAIR';
  if (/DEPART|LOUNGE/.test(n)) return 'DEPARTURE_LOUNGE';
  if (/GATE/.test(n)) return 'GATE';
  if (/CONCOURSE/.test(n)) return 'CONCOURSE';
  if (/CLASS/.test(n)) return 'CLASSROOM';
  if (/ASSEMBLY|HALL|DEWAN/.test(n)) return 'ASSEMBLY_HALL';
  if (/CANTEEN|CAFE/.test(n)) return 'CANTEEN';

  // Area-based fallback
  if (areaSqm && areaSqm < 4) return 'BATHROOM';
  if (areaSqm && areaSqm < 12) return 'BEDROOM';
  if (areaSqm && areaSqm < 25) return 'OFFICE';
  if (areaSqm && areaSqm < 50) return 'LIVING';
  return 'GENERIC';
}

/**
 * Place MEP fixtures from BOM recipes into building DB.
 * Reads ad_space_type_mep_bom + ad_placement_offset + _shim_attributes.
 */
function _rwPlaceFromBOM(buildingDb, buildingName, rooms, arcEnvelope) {
  var placed = 0, refused = 0, refusedList = [];

  // Load placement offsets (keyed by rule name)
  var offsets = {};
  var offRows = _rwDb.exec("SELECT * FROM ad_placement_offset");
  if (offRows.length) {
    var cols = offRows[0].columns;
    offRows[0].values.forEach(function(v) {
      var o = {};
      cols.forEach(function(c, i) { o[c] = v[i]; });
      offsets[v[0]] = o;
    });
  }

  // Load shim attributes (keyed by product_value)
  var shims = {};
  var shimRows = _rwDb.exec("SELECT * FROM _shim_attributes");
  if (shimRows.length) {
    var scols = shimRows[0].columns;
    shimRows[0].values.forEach(function(v) {
      var s = {};
      scols.forEach(function(c, i) { s[c] = v[i]; });
      shims[v[0]] = s;
    });
  }

  rooms.forEach(function(room) {
    // Look up BOM recipe for this room type
    var bomRows = _rwDb.exec(
      "SELECT mep_product_id, qty_normal, placement_rule, host_surface, anchor_end " +
      "FROM ad_space_type_mep_bom WHERE space_type_id = '" + room.type.replace(/'/g, "''") + "'"
    );
    if (!bomRows.length) return;

    bomRows[0].values.forEach(function(v) {
      var product = v[0];
      var qty = v[1] || 1;
      var placementRule = v[2] || 'AUTO';
      var hostSurface = v[3] || 'WALL';
      var anchorEnd = v[4] || 'PANEL';

      var offset = offsets[placementRule] || offsets['AUTO'];
      if (!offset) return;

      var info = RW_IFC_MAP[product] || RW_IFC_MAP._DEFAULT;

      // WalkerDoctrine.md §10 / real_placement_resolver.js: the ONE shared gate every leaf placement routes
      // through instead of a hardcoded box. Real dims are the SAME for every q in this product's qty loop
      // (per-product, not per-instance), so resolve once per BOM row. NO MATCH -> honest refuse: this product
      // is skipped entirely for this room (never a fabricated 0.15x0.15x0.15 box) and counted in `refused`.
      var real;
      try {
        var RPR = (typeof window !== 'undefined' && window.RealPlacementResolver) ||
          (typeof globalThis !== 'undefined' && globalThis.RealPlacementResolver) || null;
        if (!RPR) throw new Error('RealPlacementResolver module not loaded');
        real = RPR.resolveRealPlacement({ discipline: info.disc, category: product, ifc_class: info.cls, productHint: product });
      } catch (e) {
        refused += qty;
        refusedList.push({ product: product, room: room.storey + '/' + room.type, qty: qty, reason: (e && e.message) || String(e) });
        console.error('§RW_BOM_PLACE_REFUSE product=' + product + ' room=' + room.storey + '/' + room.type +
          ' qty=' + qty + ' reason=' + ((e && e.message) || e) + ' — WALKER_GAP, no fabricated box, skipped');
        return;
      }

      for (var q = 0; q < qty; q++) {
        // Compute XYZ from room bbox + placement offset
        var pos = _rwComputePosition(room, offset, hostSurface, q, qty);

        // Check ARC clash (real dims, not a flat constant)
        if (_rwClashesWithArc(pos.x, pos.y, pos.z, real.width, real.depth, real.height, arcEnvelope)) continue;

        var guid = _rwGuid(product);
        _rwInsertElement(buildingDb, guid, info.cls,
          product + ' ' + room.storey + (qty > 1 ? ' #' + (q + 1) : ''),
          buildingName, room.storey, info.disc, info.rgba,
          pos.x, pos.y, pos.z,
          real.width, real.depth, real.height  // real ad_product_dim bbox — WalkerDoctrine.md §9/§10
        );
        placed++;
      }
    });
  });

  console.log('§RW_BOM_PLACE rooms=' + rooms.length + ' fixtures=' + placed + ' refused=' + refused);
  return { placed: placed, refused: refused, refusedList: refusedList };
}

/**
 * Compute XYZ position from room bbox + placement offset rule.
 * Implements the ad_placement_offset z_rule / x_ref / y_ref logic.
 */
function _rwComputePosition(room, offset, hostSurface, index, total) {
  var cx = room.cx, cy = room.cy, cz = room.cz;
  var hx = (room.bx || 4) / 2, hy = (room.by || 4) / 2, hz = (room.bz || 3) / 2;

  // X position
  var x = cx;
  if (offset.x_ref === 'MIN')       x = cx - hx + (offset.from_edge_x || 0);
  else if (offset.x_ref === 'MAX')  x = cx + hx - (offset.from_edge_x || 0);
  // For WALL_SPACED: distribute along wall
  if (total > 1 && hostSurface === 'WALL') {
    var wallLen = room.bx || 4;
    var spacing = wallLen / (total + 1);
    x = cx - hx + spacing * (index + 1);
  }

  // Y position
  var y = cy;
  if (offset.y_ref === 'MIN')       y = cy - hy + (offset.from_edge_y || 0);
  else if (offset.y_ref === 'MAX')  y = cy + hy - (offset.from_edge_y || 0);

  // Z position
  var z = cz;
  var zOff = offset.z_offset || 0;
  if (offset.z_rule === 'FLOOR')        z = cz - hz + zOff;
  else if (offset.z_rule === 'CEILING') z = cz + hz - zOff;
  else if (offset.z_rule === 'MID')     z = cz + zOff;

  return { x: x, y: y, z: z };
}


// ═══════════════════════════════════════════════════════════════
// PATH B (cont): Connect placed fixtures with pipe runs
// ═══════════════════════════════════════════════════════════════

/**
 * Generate pipe segments connecting placed fixtures to risers/stacks.
 * Reads the RW2D- fixtures just placed, groups by storey + anchor_end,
 * runs nearest-neighbour pairing to create pipe runs.
 */
function _rwConnectFixtures(buildingDb, buildingName, arcEnvelope) {
  var pipes = 0, clashSkipped = 0;

  // Read placed fixtures grouped by storey
  var fixRows;
  try {
    fixRows = buildingDb.exec(
      "SELECT m.guid, m.element_name, m.storey, m.discipline, " +
      "t.center_x, t.center_y, t.center_z " +
      "FROM elements_meta m JOIN element_transforms t ON m.guid = t.guid " +
      "WHERE m.guid LIKE 'RW2D-%' AND m.building = '" + buildingName.replace(/'/g, "''") + "' " +
      "AND m.ifc_class != 'IfcPipeSegment' " +
      "ORDER BY m.storey"
    );
  } catch (e) { return { pipes: 0, clashSkipped: 0 }; }
  if (!fixRows.length) return { pipes: 0, clashSkipped: 0 };

  // Group fixtures by storey
  var byStorey = {};
  fixRows[0].values.forEach(function(v) {
    var s = v[2] || 'Unknown';
    if (!byStorey[s]) byStorey[s] = [];
    byStorey[s].push({ guid: v[0], name: v[1], storey: s, disc: v[3], x: v[4], y: v[5], z: v[6] });
  });

  // For each storey, create a main run + branches
  Object.keys(byStorey).forEach(function(storey) {
    var fixes = byStorey[storey];
    if (fixes.length < 2) return;

    // Sort by X to create a main horizontal run
    fixes.sort(function(a, b) { return a.x - b.x; });

    // Connect sequential fixtures with pipe segments
    for (var i = 0; i < fixes.length - 1; i++) {
      var from = fixes[i], to = fixes[i + 1];
      var dx = to.x - from.x;
      var dy = to.y - from.y;
      var dz = to.z - from.z;
      var dist = Math.sqrt(dx * dx + dy * dy + dz * dz);

      if (dist === 0 || dist > RW_MAX_PAIR_DIST) continue;

      var midX = (from.x + to.x) / 2;
      var midY = (from.y + to.y) / 2;
      var midZ = (from.z + to.z) / 2;

      // Clash check
      if (_rwClashesWithArc(midX, midY, midZ, RW_PIPE_CROSS / 1000, RW_PIPE_CROSS / 1000, dist, arcEnvelope)) {
        clashSkipped++;
        continue;
      }

      // Determine pipe type from fixture discipline
      var pipeInfo = from.disc === 'PLB' ? RW_IFC_MAP.PIPE_SP : RW_IFC_MAP.PIPE_CW;
      var guid = _rwGuid('PIPE');
      _rwInsertElement(buildingDb, guid, pipeInfo.cls,
        'Pipe ' + storey + ' run ' + (i + 1),
        buildingName, storey, pipeInfo.disc, pipeInfo.rgba,
        midX, midY, midZ,
        Math.abs(dx) || RW_PIPE_CROSS / 1000,
        Math.abs(dy) || RW_PIPE_CROSS / 1000,
        Math.abs(dz) || RW_PIPE_CROSS / 1000
      );
      pipes++;
    }
  });

  console.log('§RW_CONNECT pipes=' + pipes + ' clashSkipped=' + clashSkipped);
  return { pipes: pipes, clashSkipped: clashSkipped };
}


// ═══════════════════════════════════════════════════════════════
// DB Write helpers
// ═══════════════════════════════════════════════════════════════

function _rwGuid(prefix) {
  _rwGuidCounter++;
  return RW_PREFIX + prefix + '-' + String(_rwGuidCounter).padStart(4, '0');
}

function _rwInsertElement(db, guid, ifcClass, name, building, storey, disc, rgba, cx, cy, cz, bx, by, bz) {
  try {
    db.run(
      "INSERT OR IGNORE INTO elements_meta (guid, ifc_class, element_name, building, storey, discipline, material_rgba) " +
      "VALUES (?, ?, ?, ?, ?, ?, ?)",
      [guid, ifcClass, name, building, storey, disc, rgba]
    );
    db.run(
      "INSERT OR IGNORE INTO element_transforms (guid, center_x, center_y, center_z, " +
      "rotation_x, rotation_y, rotation_z, bbox_x, bbox_y, bbox_z) " +
      "VALUES (?, ?, ?, ?, 0, 0, 0, ?, ?, ?)",
      [guid, cx, cy, cz, bx, by, bz]
    );
  } catch (e) {
    console.warn('§RW_INSERT_FAIL guid=' + guid + ' err=' + e.message);
  }
}


// ═══════════════════════════════════════════════════════════════
// IndexedDB cache for mep_rw.db
// ═══════════════════════════════════════════════════════════════

function _rwFetchCached(url) {
  return new Promise(function(resolve, reject) {
    var req = indexedDB.open('bim_ootb_cache', 1);
    req.onupgradeneeded = function() { req.result.createObjectStore('dbs'); };
    req.onsuccess = function() {
      var idb = req.result;
      var tx = idb.transaction('dbs', 'readonly');
      var get = tx.objectStore('dbs').get('rw_' + url);
      get.onsuccess = function() {
        if (get.result) {
          console.log('§RW_CACHE_HIT ' + url);
          resolve(get.result);
        } else {
          fetch(url).then(function(resp) {
            if (!resp.ok) throw new Error('HTTP ' + resp.status);
            return resp.arrayBuffer();
          }).then(function(buf) {
            try {
              var tx2 = idb.transaction('dbs', 'readwrite');
              tx2.objectStore('dbs').put(buf, 'rw_' + url);
            } catch (e) { /* cache write fail — continue */ }
            console.log('§RW_CACHE_WRITE ' + url + ' bytes=' + buf.byteLength);
            resolve(buf);
          }).catch(reject);
        }
      };
      get.onerror = function() {
        fetch(url).then(function(r) { return r.arrayBuffer(); }).then(resolve).catch(reject);
      };
    };
    req.onerror = function() {
      fetch(url).then(function(r) { return r.arrayBuffer(); }).then(resolve).catch(reject);
    };
  });
}
