// Usage: node filters/run_blurbrush.js   Blur brush: BB1-BB4, BB6a (pre-registered in witness_log/HYPOTHESES.md before this file existed). Needs the venv python with numpy+scipy (PYTHON env) and system Chrome (CHROMIUM env).
const fs = require('fs'), path = require('path'), { spawnSync } = require('child_process'), S = require('../stack.js'), Br = require('./brush.js'), { makeDirty } = require('../perf/dirty.js');
const OUT = path.join(__dirname, 'out'); fs.mkdirSync(OUT, { recursive: true }); const rec = [], fails = [], num = {}, F = Math.fround;
const chk = (id, name, value, cmp, limit) => { const pass = cmp === '<=' ? value <= limit : cmp === '>=' ? value >= limit : value === limit; rec.push({ id, name, value, cmp, limit, pass }); if (!pass) fails.push({ id, name, value, cmp, limit }); };
const rng = (seed) => { let s = seed >>> 0; return () => (s = (Math.imul(s, 1664525) + 1013904223) >>> 0) / 4294967296; }, r4 = (x) => Math.round(x * 1e4) / 1e4, r2 = (x) => Math.round(x * 100) / 100, now = () => Number(process.hrtime.bigint()) / 1e6;
const f32b = (a) => Buffer.from(a.buffer, a.byteOffset, a.byteLength), eqB = (a, b) => Buffer.compare(f32b(a), f32b(b)) === 0;
const softDab = (rnd, W, layer, rmin, rmax) => ({ op: 'dab', layer, x: r4(rnd() * W), y: r4(rnd() * W), r: r4(rmin + rnd() * (rmax - rmin)), c: [r4(rnd()), r4(rnd()), r4(rnd())], a: r4(0.2 + rnd() * 0.7) });
const newSt = (W, nl = 1) => { const st = S.newState(W); for (let i = 0; i < nl; i++) S.apply(st, { op: 'layer', id: i, mode: i === 0 ? 'normal' : ['multiply', 'screen', 'overlay'][i % 3], opacity: 0.9, mask: false }); return st; };
const content = (W, n, seed) => { const rnd = rng(seed), st = newSt(W); for (let i = 0; i < n; i++) S.apply(st, softDab(rnd, W, 0, 3, W * 0.15)); return st.L[0].pix; };
const run = (W, pix, ops, defect) => { const st = newSt(W); if (pix) st.L[0].pix.set(pix); for (const o of ops) Br.applyOp(st, o, defect); return st.L[0].pix; };
const L128 = content(128, 60, 4), one = { op: 'stroke', layer: 0, kind: 'blur', pts: [[60.4, 70.7]], r: 15, s: 0.8 }, bent = { op: 'stroke', layer: 0, kind: 'blur', pts: [[20.5, 30], [90, 60.3], [50, 105]], r: 12, s: 0.6 };
const jobs = [['bb1_one', [one]], ['bb1_stroke', [bent]]].map(([name, ops]) => ({ name, W: 128, input: path.join(OUT, name + '.in.f32'), ops, out: path.join(OUT, name + '.ref.f64') })); for (const j of jobs) fs.writeFileSync(j.input, f32b(L128)); fs.writeFileSync(path.join(OUT, 'spec_bb.json'), JSON.stringify({ jobs }));
const py = spawnSync(process.env.PYTHON || 'python3', ['-I', path.join(__dirname, 'check_brush_ref.py'), path.join(OUT, 'spec_bb.json')], { encoding: 'utf8' }); if (py.status !== 0) { console.error(py.stderr); process.exit(2); }
const ref = (n) => { const b = fs.readFileSync(path.join(OUT, n)); return new Float64Array(b.buffer, b.byteOffset, b.byteLength / 8); }, maxd = (a, r) => { let m = 0; for (let i = 0; i < a.length; i++) m = Math.max(m, Math.abs(a[i] - r[i])); return m; };
(async () => {
  const m1 = maxd(run(128, L128, [one]), ref('bb1_one.ref.f64')), m40 = maxd(run(128, L128, [bent]), ref('bb1_stroke.ref.f64')); num.BB1 = { one: m1, stroke: m40 };
  chk('BB1', `blur dab vs numpy/scipy: one dab max ${m1.toExponential(2)} (limit 5e-6)`, m1 <= 5e-6, '==', true); chk('BB1', `blur stroke (${require('./brush.js').positions(bent.pts, bent.r, 0.15).length} dabs) vs numpy/scipy: max ${m40.toExponential(2)} (limit 2e-5)`, m40 <= 2e-5, '==', true);
  { const bad = maxd(run(128, L128, [one], 'sigma'), ref('bb1_one.ref.f64')); num.BB1.negative = bad; chk('BB1', `negative control (sigma doubled) is detected: max ${bad.toExponential(2)} > 5e-6`, bad > 5e-6, '==', true); }
  { const Bl = require('./blur.js'), rnd = rng(77); let bad = 0, n = 0; for (let t = 0; t < 200; t++) { const W = [1, 5, 40, 64, 130][t % 5], pix = content(Math.max(W, 8), 20, t + 1), WW = Math.max(W, 8), sigma = [0.5, 1, 1.7, 3, 5, 9][(rnd() * 6) | 0], rw = 1 + ((rnd() * Math.min(WW, 50)) | 0), rh = 1 + ((rnd() * Math.min(WW, 50)) | 0), rx = (rnd() * (WW - rw + 1)) | 0, ry = (rnd() * (WW - rh + 1)) | 0;
      const a = new Float32Array(Bl.blurRectToRef(pix, WW, sigma, [rx, ry, rw, rh])), b = new Float32Array(Bl.blurRectTo(pix, WW, sigma, [rx, ry, rw, rh]).subarray(0, rw * rh * 4)); n++; if (!eqB(a, b)) bad++; }
    chk('BB7', `optimised blurRectTo == the reference implementation, bit for bit, on ${n} random rects/sigmas (incl. canvas edges and radius > layer)`, bad, '==', 0); }
  { const W = 128, id = run(W, L128, [{ ...bent, s: 0 }]); const U = new Float32Array(W * W * 4); for (let i = 0; i < W * W; i++) U.set([0.3, 0.2, 0.1, 0.6], i * 4); const u2 = run(W, U, [bent]); let um = 0; for (let i = 0; i < U.length; i++) um = Math.max(um, Math.abs(u2[i] - U[i]));
    const hi = [0, 0, 0, 0]; for (let i = 0; i < L128.length; i++) hi[i % 4] = Math.max(hi[i % 4], L128[i]); const o = run(W, L128, [bent]); let rv = 0; for (let i = 0; i < o.length; i++) rv = Math.max(rv, o[i] - hi[i % 4] - 1e-6, -o[i] - 1e-6);
    const pos = Br.positions(bent.pts, bent.r, 0.15); let far = 0; for (let y = 0; y < W; y++) for (let x = 0; x < W; x++) { const near = pos.some(([px, py]) => Math.hypot(x - Math.floor(px), y - Math.floor(py)) < bent.r + 1.5); if (!near) for (let k = 0; k < 4; k++) if (o[(y * W + x) * 4 + k] !== L128[(y * W + x) * 4 + k]) far++; }
    chk('BB2', 's = 0 is the identity (bitwise)', eqB(id, L128), '==', true); chk('BB2', `a uniform layer is unchanged (max change ${um.toExponential(2)} <= 1e-6)`, um <= 1e-6, '==', true); chk('BB2', 'every output channel within [0, max input channel] (convex)', rv <= 0, '==', true); chk('BB2', 'pixels farther than r+1.5 from every dab position are bitwise unchanged', far, '==', 0); }
  { const W = 128, line = new Float32Array(W * W * 4); for (let i = 0; i < W * W; i++) line.set([1, 1, 1, 1], i * 4); for (let y = 0; y < W; y++) line.set([0, 0, 0, 1], (y * W + 64) * 4);   // 1-px black vertical line on white
    const o = run(W, line, [{ op: 'stroke', layer: 0, kind: 'blur', pts: [[64.5, 64.5]], r: 20, s: 1 }]), peak = 1 - o[(64 * W + 64) * 4]; const E = new Float32Array(W * W * 4); for (let y = 0; y < W; y++) for (let x = 0; x < W; x++) E.set(x < 64 ? [0, 0, 0, 1] : [1, 1, 1, 1], (y * W + x) * 4);
    const grad = (a) => { let m = 0; const y = 64; for (let x = 20; x < 108; x++) m = Math.max(m, Math.abs(a[(y * W + x + 1) * 4] - a[(y * W + x) * 4])); return m; }, e2 = run(W, E, [{ op: 'stroke', layer: 0, kind: 'blur', pts: [[30, 64.5], [100, 64.5]], r: 24, s: 1 }]);
    num.BB3 = { line_peak_darkness_after: peak, edge_gradient_before: grad(E), edge_gradient_after: grad(e2) };
    chk('BB3', `1-px dark line: peak darkness ${peak.toFixed(3)} after one blur dab (was 1.0; limit <= 0.5)`, peak <= 0.5, '==', true); chk('BB3', `hard edge: max horizontal gradient ${grad(E).toFixed(2)} -> ${grad(e2).toFixed(3)} after a blur stroke across it along the stroke's centre row (limit <= 50% of before)`, grad(e2) <= 0.5 * grad(E), '==', true); }
  { const rnd = rng(11), W = 256; let bad = 0; for (let t = 0; t < 30; t++) { const n = 2 + ((rnd() * 20) | 0), pts = []; for (let i = 0; i < n; i++) pts.push([r2(rnd() * W), r2(rnd() * W)]);
      const o = { op: 'stroke', layer: 0, kind: 'blur', pts, r: 3 + rnd() * 20, s: r4(0.2 + rnd() * 0.8) }, base = content(W, 40, 7 + t), a = run(W, base, [o]), b = newSt(W); b.L[0].pix.set(base); const sb = Br.StrokeBuilder(b, { ...o, pts: [] }); for (const p of pts) { sb.push(p[0], p[1]); if (rnd() < 0.3) sb.push(p[0], p[1]); } if (!eqB(a, b.L[0].pix)) bad++; }
    chk('BB4', 'incremental blur-brush builder == batch stroke (30 random strokes, duplicate events mixed in)', bad, '==', 0); }
  { const rnd = rng(19), W = 256; let bad = 0, slices = 0; for (let t = 0; t < 30; t++) { const n = 2 + ((rnd() * 15) | 0), pts = []; for (let i = 0; i < n; i++) pts.push([r2(rnd() * W), r2(rnd() * W)]);
      const o = { op: 'stroke', layer: 0, kind: 'blur', pts, r: 3 + rnd() * 20, s: r4(0.2 + rnd() * 0.8) }, base = content(W, 40, 70 + t), a = run(W, base, [o]), b = newSt(W); b.L[0].pix.set(base); const sb = Br.StrokeBuilder(b, { ...o, pts: [] }); let fake = 0; const clock = () => (fake += 0.7);
      for (const p of pts) { sb.queue(p[0], p[1]); if (rnd() < 0.5) { slices++; sb.drain([0, 0.5, 2, 6, Infinity][(rnd() * 5) | 0], clock); } } while (sb.pending()) { slices++; sb.drain([0, 1, 3][(rnd() * 3) | 0], clock); } if (!eqB(a, b.L[0].pix)) bad++; }
    chk('BB8', `time-sliced queue/drain gives the same bytes as immediate application for any schedule (30 random strokes, ${slices} random drain slices incl. 0 ms budgets)`, bad, '==', 0); }
  { const W = 256, rnd = rng(31), ops = []; for (let i = 0; i < 2; i++) ops.push({ op: 'layer', id: i, mode: i ? 'multiply' : 'normal', opacity: 0.9, mask: false }); ops.push({ op: 'fill', layer: 0, c: [0.5, 0.5, 0.5], a: 1 }); for (let i = 0; i < 40; i++) ops.push(softDab(rnd, W, i % 2, 5, 40)); const cut = ops.length;
    ops.push({ op: 'stroke', layer: 0, kind: 'blur', pts: [[30, 40], [120, 200], [220, 60]], r: 16, s: 0.9 }, { op: 'stroke', layer: 1, kind: 'blur', pts: [[200, 30], [60, 130]], r: 25, s: 0.5 }); for (let i = 0; i < 10; i++) ops.push(softDab(rnd, W, i % 2, 5, 40));
    const fold = (o) => { const st = S.newState(W); for (const x of o) Br.applyOp(st, x); return st; }, f1 = fold(ops), f2 = fold(ops), h = S.hashF32(S.composite(f1)); const mid = fold(ops.slice(0, cut)), st = S.newState(W); for (const x of ops.slice(0, 2)) Br.applyOp(st, x); for (const k of Object.keys(mid.L)) st.L[k].pix.set(mid.L[k].pix); for (const x of ops.slice(cut)) Br.applyOp(st, x);
    chk('BB4', 'two folds of a log with blur strokes give the same hash', S.hashF32(S.composite(f2)) === h, '==', true); chk('BB4', 'hash chain verifies', S.verifyChain(JSON.parse(JSON.stringify(S.chain(ops)))), '==', -1); chk('BB4', 'checkpoint before the blur strokes + tail equals the full fold', S.hashF32(S.composite(st)) === h, '==', true);
    const lh = Object.keys(f1.L).map((k) => S.hashF32(f1.L[k].pix)), { chromium } = require('playwright-core'), br = await chromium.launch({ executablePath: process.env.CHROMIUM || '/opt/pw-browsers/chromium', args: ['--no-sandbox'] }), pg = await br.newPage(); await pg.goto('about:blank');
    for (const f of ['stack.js', 'filters/blur.js', 'filters/brush.js']) await pg.addScriptTag({ path: path.join(__dirname, '..', f) }); const ch = await pg.evaluate(({ ops, W }) => { const st = Stack.newState(W); for (const o of ops) Brush.applyOp(st, o); return Object.keys(st.L).map((k) => Stack.hashF32(st.L[k].pix)); }, { ops, W }); await br.close();
    chk('BB4', 'Node == Chromium: layer hashes after the log', JSON.stringify(ch) === JSON.stringify(lh), '==', true); }
  { const W = 512, rnd = rng(61), st = newSt(W, 3); S.apply(st, { op: 'fill', layer: 0, c: [0.5, 0.5, 0.5], a: 1 }); for (let l = 0; l < 3; l++) for (let k = 0; k < 8; k++) S.apply(st, softDab(rnd, W, l, 20, 120));
    const D = makeDirty(st); D.full(); let mism = 0; for (const o of [{ op: 'stroke', layer: 1, kind: 'blur', pts: [[60, 80], [200, 150.5], [180, 300]], r: 20, s: 1 }, { op: 'stroke', layer: 0, kind: 'blur', pts: [[300, 400], [450, 380]], r: 30, s: 0.6 }, { op: 'stroke', layer: 2, kind: 'blur', pts: [[5, 500], [500, 505]], r: 9, s: 1 }]) { Br.applyOp(st, o); D.after(o); if (!eqB(D.back, S.composite(st))) mism++; }
    chk('BB4', 'dirty-tile compositor bit-identical after 3 blur strokes (one touching the canvas edge)', mism, '==', 0); }
  { const W = 2048, rnd = rng(81), st = newSt(W, 1); S.apply(st, { op: 'fill', layer: 0, c: [0.5, 0.5, 0.5], a: 1 }); for (let k = 0; k < 60; k++) S.apply(st, softDab(rnd, W, 0, 20, 200)); const pts = []; for (let i = 0; i < 6; i++) pts.push([r2(300 + i * 60), r2(900 + Math.sin(i) * 40)]); const o = { op: 'stroke', layer: 0, kind: 'blur', pts, r: 20, s: 0.7 }, n = Br.positions(pts, 20, 0.15).length, t = [];
    for (let i = 0; i < 5; i++) { const a = now(); Br.applyOp(st, o); t.push(now() - a); } const med = t.sort((x, y) => x - y)[2]; num.BB6a = { dabs: n, apply_ms_median: med }; chk('BB6', `2048^2 layer: blur stroke of ${n} dabs (r=20) applies in ${med.toFixed(1)} ms median (limit 150; ${(med / n).toFixed(2)} ms per dab)`, +med.toFixed(1), '<=', 150); }
  const out = { n_checks: rec.length, gate: fails.length ? 'FAIL' : 'PASS', fails, numbers: num, checks: rec, node: process.version };
  fs.writeFileSync(path.join(OUT, 'blurbrush.json'), JSON.stringify(out, null, 1)); console.log(JSON.stringify({ ...out, checks: undefined }, null, 1)); process.exit(fails.length ? 1 : 0);
})();
