#!/usr/bin/env node
// gen_terminal_meta_patch.js (§S10, 4D_GANTT_TM_REFACTOR.md) — Terminal_meta.db carries a
// per-element-corrupted z/x/y rebase: 48,428 shared elements (guid = 'T0_Terminal_' + meta guid),
// modal rigid offset meta−extracted = (dx,dy,dz) via per-axis median, but 627 elements deviate
// >0.25m (walls to 11.3m) — enough to flip bearing relations (measured: a wall standing ON the
// plate in extracted sits 0.9m BELOW it in meta). Truth = extracted geometry; meta's datum is
// kept (geo.db meshes + positions.bin pair with it). Emits UPDATEs for every row deviating >EPS
// (0.05m — ScheduleGate's own equality tolerance; below it no predicate can change) snapping to
// extracted + modal offset. Idempotent by construction (absolute SET values).
'use strict';
const fs = require('fs'), path = require('path');
const OOTB = path.join(require('os').homedir(), 'bim-ootb');
const initSqlJs = require(path.join(OOTB, 'modeller', 'lib', 'sql-wasm.js'));
const EPS = 0.05;   // ScheduleGate.EPS, mirrored
async function main() {
  const SQL = await initSqlJs({ wasmBinary: fs.readFileSync(path.join(OOTB, 'modeller', 'lib', 'sql-wasm.wasm')) });
  const load = f => { const db = new SQL.Database(fs.readFileSync(path.join(OOTB, 'buildings', f)));
    const r = db.exec('SELECT guid, center_x, center_y, center_z FROM element_transforms');
    db.close(); return r[0].values; };
  const ex = load('Terminal_extracted.db'), me = load('Terminal_meta.db');
  const norm = g => String(g).replace(/^T0_Terminal_/, '');
  const exMap = new Map(ex.map(v => [norm(v[0]), v]));
  const ds = { x: [], y: [], z: [] };
  me.forEach(m => { const e = exMap.get(String(m[0])); if (!e) return;
    ds.x.push(m[1] - e[1]); ds.y.push(m[2] - e[2]); ds.z.push(m[3] - e[3]); });
  const med = a => { const s = a.slice().sort((x, y) => x - y); return s[Math.floor(s.length / 2)]; };
  const M = { x: med(ds.x), y: med(ds.y), z: med(ds.z) };
  const lines = [
    '-- §S10_META_TRANSFORM_REPAIR (2026-08-16, bim-compiler prompts/4D_GANTT_TM_REFACTOR.md §S10)',
    '-- Terminal_meta.db was produced with a per-element-corrupted rebase: most elements sit at the',
    '-- rigid offset (' + M.x.toFixed(3) + ', ' + M.y.toFixed(3) + ', ' + M.z.toFixed(3) + ') from Terminal_extracted.db (the extraction truth),',
    '-- but a tail deviates up to 11.3m (152 walls, 65 slabs, 59 beams...), flipping bearing',
    '-- relations for the scheduler (measured: walls standing ON the ground plate in truth sat',
    '-- 0.9m BELOW it here — 251 false bearing pairs against the plate alone). Every row deviating',
    '-- >0.05m (ScheduleGate.EPS) snaps to extracted-truth + the modal offset; meta datum kept so',
    '-- geo.db meshes / positions.bin stay paired. Generated by scripts/gen_terminal_meta_patch.js;',
    '-- absolute values = idempotent. Storey-field differences are intentional (oci_normalize) and untouched.'
  ];
  let n = 0, maxd = 0;
  me.forEach(m => {
    const e = exMap.get(String(m[0])); if (!e) return;
    const tx = e[1] + M.x, ty = e[2] + M.y, tz = e[3] + M.z;
    const d = Math.max(Math.abs(m[1] - tx), Math.abs(m[2] - ty), Math.abs(m[3] - tz));
    if (d > EPS) {
      n++; if (d > maxd) maxd = d;
      lines.push("UPDATE element_transforms SET center_x=" + tx.toFixed(6) + ", center_y=" + ty.toFixed(6) +
        ", center_z=" + tz.toFixed(6) + " WHERE guid='" + String(m[0]).replace(/'/g, "''") + "';");
    }
  });
  const out = process.env.OUT || (OOTB + '/buildings/patches/Terminal_meta.db.sql');
  fs.appendFileSync(out, '\n' + lines.join('\n') + '\n');
  console.log('§S10_PATCH_GEN rows=' + n + ' maxDev=' + maxd.toFixed(2) + 'm modal=(' +
    M.x.toFixed(3) + ',' + M.y.toFixed(3) + ',' + M.z.toFixed(3) + ') appended=' + out);
}
main().catch(e => { console.error(e); process.exit(2); });
