#!/usr/bin/env node
// §IFC_SURFACE_NAMES (bim-compiler prompts/PHOTOREAL_STILL_RENDER.md) — shipped buildings: the same extractor the browser import uses
// (viewer/ifc_surface_names.js), run over the SOURCE IFCs, written as an idempotent block in buildings/patches/<db>.sql (self-heal loader,
// scene.js _applyPendingPatch). Never a binary DB. material_name is UPDATED only where it is NULL/'' or a synthetic '≈ ' colour label.
// usage: node scripts/ifc_surface_patch.js --webifc <web-ifc pkg> --sqljs <sql.js pkg> --db Clinic_meta.db[,Clinic_extracted.db] [--dbdir buildings] a.ifc b.ifc ...
// Diffs against each target DB: UPDATE only where its material_name is NULL/''/'≈ …'; element_surfaces only for elements with 2+ styles.
const fs = require('fs'), path = require('path');
const args = process.argv.slice(2), opt = {}, files = [];
for (let i = 0; i < args.length; i++) { if (args[i].startsWith('--')) opt[args[i].slice(2)] = args[++i]; else files.push(args[i]); }
const W = require(opt.webifc || 'web-ifc'), SN = require(path.join(__dirname, '../viewer/ifc_surface_names.js'));
const q = s => s == null ? 'NULL' : "'" + String(s).replace(/'/g, "''") + "'";
(async () => {
  const api = new W.IfcAPI(); await api.Init(); const rows = {}; const lines = [];
  for (const f of files) {
    const t0 = Date.now(), m = api.OpenModel(new Uint8Array(fs.readFileSync(f)), { COORDINATE_TO_ORIGIN: false });
    const ctx = SN.build(api, W, m), els = [];
    api.StreamAllMeshes(m, fm => {
      const id = fm.expressID; let gl = null; try { gl = api.GetLine(m, id); } catch (e) { return; }
      if (!gl || !gl.GlobalId) return; els.push({ expressID: id, guid: gl.GlobalId.value });
      for (let j = 0; j < fm.geometries.size(); j++) { const g = fm.geometries.get(j); let tris = 0;
        try { const gd = api.GetGeometry(m, g.geometryExpressID); tris = gd.GetIndexDataSize() / 3; gd.delete && gd.delete(); } catch (e) {}
        SN.addPart(ctx, id, g.geometryExpressID, g.color, tris); }
    });
    // elements with no mesh still get their associated material name
    for (const oid of Object.keys(ctx.materialOfElement)) { const id = +oid; if (els.some(e => e.expressID === id)) continue; let gl = null; try { gl = api.GetLine(m, id); } catch (e) {} if (gl && gl.GlobalId) els.push({ expressID: id, guid: gl.GlobalId.value }); }
    for (const e of els) { const r = SN.resolve(ctx, e.expressID); if (!rows[e.guid]) rows[e.guid] = r; }
    lines.push(SN.statsLine(ctx, els) + ' file=' + path.basename(f) + ' ms=' + (Date.now() - t0));
    api.CloseModel(m);
  }
  const guids = Object.keys(rows), BEGIN = '-- §IFC_SURFACE_NAMES BEGIN (generated by scripts/ifc_surface_patch.js; re-run replaces this block)', END = '-- §IFC_SURFACE_NAMES END';
  const initSqlJs = require(opt.sqljs || 'sql.js'), SQL = await initSqlJs();
  for (const db of (opt.db || '').split(',').filter(Boolean)) {
    const dbPath = path.join(opt.dbdir || path.join(__dirname, '../buildings'), db), cur0 = {};
    if (fs.existsSync(dbPath)) { const d = new SQL.Database(fs.readFileSync(dbPath)); const r = d.exec('SELECT guid, material_name FROM elements_meta'); if (r.length) r[0].values.forEach(v => { cur0[v[0]] = v[1]; }); d.close(); }
    else { lines.push('§IFC_SURFACE_PATCH SKIP ' + db + ' (no DB at ' + dbPath + ' to diff against)'); continue; }
    const out = [BEGIN, '-- sources: ' + files.map(f => path.basename(f)).join(', '),
      'CREATE TABLE IF NOT EXISTS element_surfaces (guid TEXT, part INTEGER, style_name TEXT, rgba TEXT, tri_count INTEGER, PRIMARY KEY (guid, part));'];
    let nU = 0, nP = 0, nKeep = 0, nMiss = 0;
    for (const g of guids) { const r = rows[g];
      if (!(g in cur0)) { nMiss++; continue; }
      const c = cur0[g];
      // only where the DB holds no authored name (NULL, '' or a synthetic '≈ ' colour label) — an authored name is kept as is
      if (r.matName && (c == null || c === '' || /^≈ /.test(c))) { out.push("UPDATE elements_meta SET material_name=" + q(r.matName) + " WHERE guid=" + q(g) + " AND (material_name IS NULL OR material_name='' OR material_name LIKE '≈ %');"); nU++; } else if (r.matName) nKeep++;
      // the per-part fact is only new where an element carries 2+ distinct styles (frame / panel / sash / glazing …)
      // --surfaces 1 only: no renderer reads element_surfaces yet (the per-part split is a later step), and every patch row costs load time
      // on every open (Terminal: 22,481 rows); user IFC imports record them regardless.
      if (opt.surfaces !== '1') continue;
      const st = new Set(r.parts.map(p => p.style).filter(Boolean)); if (st.size < 2) continue;
      r.parts.forEach((p, i) => { out.push('INSERT OR REPLACE INTO element_surfaces VALUES (' + [q(g), i, q(p.style), q(p.rgba), p.tris | 0].join(',') + ');'); nP++; }); }
    out.push(END);
    const pf = path.join(opt.patches || path.join(__dirname, '../buildings/patches'), db + '.sql');
    let cur = fs.existsSync(pf) ? fs.readFileSync(pf, 'utf8') : '';
    const a = cur.indexOf(BEGIN), b = cur.indexOf(END);
    if (a >= 0 && b > a) cur = cur.slice(0, a) + cur.slice(b + END.length).replace(/^\n/, '');
    fs.writeFileSync(pf, cur.replace(/\n*$/, '\n') + out.join('\n') + '\n');
    lines.push('§IFC_SURFACE_PATCH wrote ' + pf + ' updates=' + nU + ' keptAuthored=' + nKeep + ' notInDb=' + nMiss + ' surfaceRows=' + nP + ' guids=' + guids.length);
  }
  console.log(lines.join('\n'));
})();
