#!/usr/bin/env node
// §WIND_FLIP baked (bim-compiler prompts/PHOTOREAL_STILL_RENDER.md "§WIND_FLIP — SPEC", 2026-10-02): run the SAME rule the viewer
// runs live (viewer/wind_flip.js) over a building's component_geometries and write the result as an idempotent block in
// buildings/patches/<db>.sql (self-heal loader, scene.js _applyPendingPatch). Rows = flagged geometries only + one '__census__' row
// carrying the rule id and the geometry count; scene.js A._windTableGet uses the table only when that rule matches. Never a binary DB.
// usage: node scripts/wind_flip_patch.js --geo Clinic_extracted.db --db Clinic_extracted.db,Clinic_meta.db [--dbdir buildings] [--sqljs <pkg>]
const fs = require('fs'), path = require('path');
const args = process.argv.slice(2), opt = {};
for (let i = 0; i < args.length; i++) if (args[i].startsWith('--')) opt[args[i].slice(2)] = args[++i];
const WF = require(path.join(__dirname, '../viewer/wind_flip.js'));
const BEGIN = '-- §WIND_FLIP BEGIN (generated by scripts/wind_flip_patch.js; re-run replaces this block)', END = '-- §WIND_FLIP END';
(async () => {
  const dir = opt.dbdir || path.join(__dirname, '../buildings'), SQL = await require(opt.sqljs || 'sql.js')();
  const t0 = Date.now(), g = new SQL.Database(fs.readFileSync(path.join(dir, opt.geo)));
  const st = g.prepare('SELECT geometry_hash, vertices, faces FROM component_geometries'); const flagged = []; let n = 0, edges = 0;
  while (st.step()) { const [h, v, f] = st.get(); if (!v || !f || v.byteLength < 36 || f.byteLength < 12) continue;
    const vArr = new Float32Array(v.buffer, v.byteOffset, v.byteLength / 4), fArr = new Uint32Array(f.buffer, f.byteOffset, f.byteLength / 4);
    const c = WF.count(WF.fromBlob(vArr), fArr); n++; if (c) { flagged.push([h, c]); edges += c; } }
  st.free(); g.close();
  const block = [BEGIN, '-- source: ' + opt.geo + ' geometries=' + n + ' flagged=' + flagged.length + ' conflictEdges=' + edges + ' rule=' + WF.RULE,
    'CREATE TABLE IF NOT EXISTS geometry_wind_flip (geometry_hash TEXT PRIMARY KEY, conflict_edges INTEGER, rule TEXT);',
    "INSERT OR REPLACE INTO geometry_wind_flip VALUES ('__census__', " + n + ", '" + WF.RULE + "');"]
    .concat(flagged.map(r => "INSERT OR REPLACE INTO geometry_wind_flip VALUES ('" + String(r[0]).replace(/'/g, "''") + "', " + r[1] + ", '" + WF.RULE + "');"), [END]).join('\n') + '\n';
  for (const db of (opt.db || '').split(',').filter(Boolean)) {
    const p = path.join(dir, 'patches', db + '.sql'); let cur = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : '';
    const i = cur.indexOf(BEGIN), j = cur.indexOf(END);
    if (i >= 0 && j > i) cur = cur.slice(0, i) + cur.slice(j + END.length).replace(/^\n/, '');
    if (cur && !cur.endsWith('\n')) cur += '\n';
    fs.writeFileSync(p, cur + block);
    console.log('§WIND_FLIP_PATCH ' + db + ' geo=' + opt.geo + ' geometries=' + n + ' flagged=' + flagged.length + ' conflictEdges=' + edges + ' bytes=' + Buffer.byteLength(block) + ' ms=' + (Date.now() - t0) + ' -> ' + p);
  }
})().catch(e => { console.error('§WIND_FLIP_PATCH FAIL ' + e.message); process.exit(1); });
