# Generates tools/upgrade_map.js from the buildingSMART EXPRESS schemas shipped in IfcOpenShell.
# Dev-time only (Node runtime has no python/ifcopenshell dependency). Spec: prompts/BIM_UTILITY_KNIFE.md U1.
import json, ifcopenshell.ifcopenshell_wrapper as w
b = w.schema_by_name('IFC4X3_ADD2')
def attrs(d): return [x.name() for x in d.all_attributes()]
def fills(d):
    """per target attr: '.NOTDEFINED.' if it is a REQUIRED enumeration that has NOTDEFINED, else '' (optional/other)."""
    out = []
    for x in d.all_attributes():
        f = ''
        if not x.optional():
            t = x.type_of_attribute()
            try:
                t = t.declared_type() if hasattr(t, 'declared_type') else t
                if hasattr(t, 'declared_type'): t = t.declared_type()
                items = [i.upper() for i in t.enumeration_items()]
                if 'NOTDEFINED' in items: f = '.NOTDEFINED.'
                else: f = '!' + items[0]          # first enum value, flagged for the report
            except Exception:
                f = '?'                           # required, not an enum: needs a hand rule
        out.append(f)
    return out
# Human-decided renames for entities that do not exist in 4.3 (every one is reported by the tool, never silent).
RENAME = {'IFCDOORSTYLE': 'IFCDOORTYPE', 'IFCWINDOWSTYLE': 'IFCWINDOWTYPE'}
b_names = {e.name().upper(): e for e in b.entities()}
def build(a):
  m, missing = {}, []
  for e in a.entities():
    n = e.name().upper()
    tgt = RENAME.get(n, n)
    if tgt not in b_names: missing.append(n); continue
    m[n] = {'to': tgt, 'from': attrs(e), 'attrs': attrs(b_names[tgt]), 'fill': fills(b_names[tgt]), 'req': [0 if x.optional() else 1 for x in b_names[tgt].all_attributes()]}
  return {'map': m, 'missing': missing}
out = {'rename': RENAME, 'from': {'IFC2X3': build(w.schema_by_name('IFC2X3')), 'IFC4': build(w.schema_by_name('IFC4'))}}
open('tools/upgrade_map.js', 'w').write('/* GENERATED by gen_upgrade_map.py from IfcOpenShell IFC2X3 + IFC4X3_ADD2 — do not edit */\n'
  '(function(g){g.BIM_UPGRADE_MAP=' + json.dumps(out, separators=(',', ':')) + ';})(typeof self!=="undefined"?self:globalThis);\n'
  'if(typeof module!=="undefined")module.exports=BIM_UPGRADE_MAP;\n')
for k,v in out['from'].items(): print(k,'mapped',len(v['map']),'missing',len(v['missing']))
