// Minimal ICC v4 matrix/TRC RGB profile writer (so a Display-P3 profile needs no external file).
(function (root) {
  const CM = typeof require !== 'undefined' ? require('./color_math.js') : root.ColorMath;
  const s15 = (v) => Math.round(v * 65536);
  function xyzTag(v) { const b = new DataView(new ArrayBuffer(20)); [...'XYZ '].forEach((c, i) => b.setUint8(i, c.charCodeAt(0))); v.forEach((x, i) => b.setInt32(8 + 4*i, s15(x))); return new Uint8Array(b.buffer); }
  function paraSRGB() { const b = new DataView(new ArrayBuffer(12 + 20)); [...'para'].forEach((c, i) => b.setUint8(i, c.charCodeAt(0))); b.setUint16(8, 3);
    [2.4, 1/1.055, 0.055/1.055, 1/12.92, 0.04045].forEach((x, i) => b.setInt32(12 + 4*i, s15(x))); return new Uint8Array(b.buffer); }
  function mluc(text) { const n = text.length*2, b = new DataView(new ArrayBuffer(28 + n)); [...'mluc'].forEach((c, i) => b.setUint8(i, c.charCodeAt(0)));
    b.setUint32(8, 1); b.setUint32(12, 12); b.setUint8(16, 101); b.setUint8(17, 110); b.setUint8(18, 85); b.setUint8(19, 83); b.setUint32(20, n); b.setUint32(24, 28);
    for (let i = 0; i < text.length; i++) b.setUint16(28 + 2*i, text.charCodeAt(i)); return new Uint8Array(b.buffer); }
  function chad(m) { const b = new DataView(new ArrayBuffer(8 + 36)); [...'sf32'].forEach((c, i) => b.setUint8(i, c.charCodeAt(0))); m.flat().forEach((x, i) => b.setInt32(8 + 4*i, s15(x))); return new Uint8Array(b.buffer); }
  // space: 'srgb' | 'p3' (sRGB transfer curve, D65 white adapted to D50 by Bradford)
  function matrixProfile(space, desc) {
    const M = CM.M[space], tags = [['desc', mluc(desc)], ['cprt', mluc('CC0 test profile generated by psd-oplog POC')], ['wtpt', xyzTag(CM.D50)],
      ['rXYZ', xyzTag([M[0][0], M[1][0], M[2][0]])], ['gXYZ', xyzTag([M[0][1], M[1][1], M[2][1]])], ['bXYZ', xyzTag([M[0][2], M[1][2], M[2][2]])],
      ['chad', chad(CM.CAT)], ['rTRC', paraSRGB()], ['gTRC', 'rTRC'], ['bTRC', 'rTRC']];
    const headerLen = 128, tableLen = 4 + 12 * tags.length; let off = headerLen + tableLen; const place = {}, bodies = [];
    for (const [sig, body] of tags) { if (typeof body === 'string') { place[sig] = place[body]; continue; } const pad = (4 - body.length % 4) % 4; place[sig] = [off, body.length]; bodies.push(body, new Uint8Array(pad)); off += body.length + pad; }
    const out = new DataView(new ArrayBuffer(off)), u8 = new Uint8Array(out.buffer), put = (o, s) => [...s].forEach((c, i) => u8[o + i] = c.charCodeAt(0));
    out.setUint32(0, off); out.setUint32(8, 0x04200000); put(12, 'mntr'); put(16, 'RGB '); put(20, 'XYZ '); out.setUint16(24, 2026); out.setUint16(26, 10); out.setUint16(28, 9); put(36, 'acsp');
    out.setInt32(68, s15(CM.D50[0])); out.setInt32(72, s15(CM.D50[1])); out.setInt32(76, s15(CM.D50[2]));
    out.setUint32(128, tags.length); tags.forEach(([sig], i) => { put(132 + 12*i, sig); out.setUint32(136 + 12*i, place[sig][0]); out.setUint32(140 + 12*i, place[sig][1]); });
    let p = headerLen + tableLen; for (const b of bodies) { u8.set(b, p); p += b.length; }
    return u8;
  }
  const api = { matrixProfile };
  if (typeof module !== 'undefined') module.exports = api; else root.IccWrite = api;
})(this);
